#==============================================================================
# wfsource/source/GNUMakefile.test
#==============================================================================

ifndef TEST_PROG
TEST_PROG = $(LIB_NAME)test
endif

ifndef DEBUGGER
DEBUGGER = gdb
endif
.PHONY : reset_target
reset_target : 

run_test : $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)
	-$(RUN) $^ $(TEST_PROG_PARAMS)

post_run :

link : $(OBJ_DIR) $(PIGS_LIB) $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)

.PHONY: test
test : $(LOCAL-PRECONDITIONS) LIBRARY_NAMES_DEFINES link reset_target run_test post_run


#TEST_LIBS += $(PIGSYS) $(MENU) $(PIGS_LIB_DIR)lib$(LIB_NAME).a
TEST_LIBS +=  $(PIGSYS) $(PIGS_LIB_DIR)lib$(LIB_NAME).a $(LIBS)
#TEST_LIBS += $(LIBS)
#TEST_LIBS += $(PIGSYS) $(CPPLIB) $(IFF) $(MATH) $(STREAMS) $(PIGS_OBJ_DIR)/$(LIB_NAME)/lib$(LIB_NAME).a

################################################################################

debug : $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)
	$(DEBUGGER) $^ $(TEST_PROG_PARAMS)

################################################################################

$(LIB_OBJ_DIR)$(TEST_PROG)$(EXE) : LIBRARY_NAMES_DEFINES $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ) $(TEST_OBJS) $(TEST_LIBS)
	@echo ------------------------------------------------------------------------------
	@echo Creating \> \> $@ \< \<
#	@echo ------------------------------------------------------------------------------
	@echo TEST_LIBS = $(TEST_LIBS)
	@echo ------------------------------------------------------------------------------
	gcc -o $@ $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ) $(TEST_OBJS) -Xlinker --start-group $(TEST_LIBS) -Xlinker --end-group $(LNARGS) $(SYS_LIBS)
