\ One actor per follower: school state/behaviour shared with school.fth; no clownfish part rig.
\ Constants/actor indices generated by tiger_barb.py. Positions remain in leader body lengths.
: sd-speed 2 ;
: sd-world>bl ( world centre -- bl ) - sd-bl / ;
: sd-oct ( a -- rev ) dup 1 swap - 0.04345 * 0.125 + * ;
: sd-atan2 ( y x -- rev )
  2dup abs swap abs + 0.000001 < if 2drop 0 else
    over abs over abs 2dup > if swap / sd-oct 0.25 swap - else / sd-oct then
    over 0 < if 0.5 swap - then rot 0 < if negate then nip then ;
: sd-wrap ( d -- d' ) dup 0.5 > if 1 - then dup -0.5 < if 1 + then ;
: sd-leader
  INDEXOF_X_POS fish-actor-player read-actor-mailbox sd-cx sd-world>bl
  INDEXOF_Y_POS fish-actor-player read-actor-mailbox sd-cy sd-world>bl
  INDEXOF_Z_POS fish-actor-player read-actor-mailbox sd-cz sd-world>bl
  dup sd-prev 2 + read-mailbox - MB_WANT 2 + sc!
  over sd-prev 1 + read-mailbox - MB_WANT 1 + sc!
  2 pick sd-prev read-mailbox - MB_WANT sc!
  MB_Z 0 sch! MB_Y 0 sch! MB_X 0 sch!
  MB_X 0 sch@ sd-prev write-mailbox MB_Y 0 sch@ sd-prev 1 + write-mailbox MB_Z 0 sch@ sd-prev 2 + write-mailbox
  MB_WANT vnorm fish-dt / dup sd-lspeed write-mailbox
  0.05 > if MB_WANT sc@ sd-lhead write-mailbox MB_WANT 1 + sc@ sd-lhead 1 + write-mailbox MB_WANT 2 + sc@ sd-lhead 2 + write-mailbox then
  sd-lhead read-mailbox MB_VX 0 sch! sd-lhead 1 + read-mailbox MB_VY 0 sch! sd-lhead 2 + read-mailbox MB_VZ 0 sch! ;
: sd-mode-update
  sd-lspeed read-mailbox 1 > if 1 sd-mode write-mailbox then
  sd-lspeed read-mailbox 0.45 < if 0 sd-mode write-mailbox then
  sd-mode read-mailbox sd-blend read-mailbox - fish-dt 2 * * sd-blend read-mailbox + fish-clamp01
  dup sd-blend write-mailbox sch-regime ;
: sd-dt ( k -- dt ) sd-times + 1 - read-mailbox sd-clock read-mailbox swap - 0.5 min ;
: sd-predict ( axis -- bl )
  dup MB_X + me sch@ swap MB_VX + me sch@
  sd-speed startle-gain * * me sd-dt * + ;
: sd-update ( k -- )
  \ Preserve the endpoint already reached along the OLD heading. sch-follow's
  \ new heading applies from now on, not retroactively over the previous gap.
  dup MB_ME sc!
  0 sd-predict sd-px write-mailbox
  1 sd-predict sd-py write-mailbox
  2 sd-predict sd-pz write-mailbox
  dup sd-dt 120 sd-speed sch-set-dt dup sch-follow
  sd-px read-mailbox MB_NX me sch!
  sd-py read-mailbox MB_NY me sch!
  sd-pz read-mailbox MB_NZ me sch!
  clamp-all dup sch-commit1
  sd-clock read-mailbox swap sd-times + 1 - write-mailbox ;
: sd-round-robin
  sd-budget sch-n 1 - min 0 do
    sd-ptr read-mailbox 1 + sd-update
    sd-ptr read-mailbox 1 + sch-n 1 - mod sd-ptr write-mailbox loop ;
: sd-pos ( axis centre -- world )
  >r dup sd-predict over MB_LOX + par@ max swap MB_HIX + par@ min sd-bl * r> + ;
: sd-actor me 1 - sd-act + read-mailbox ;
: sd-write ( value mailbox -- ) sd-actor write-actor-mailbox ;
: sd-ease-angle ( target current -- angle )
  \ Ease small changes, but cap large wall/reflection turns at 180 degrees/s.
  dup >r - sd-wrap fish-dt 8 * fish-clamp01 *
  fish-dt 0.5 * dup negate >r min r> max r> + sd-wrap ;
: sd-pose ( k -- )
  MB_ME sc!
  0 sd-cx sd-pos INDEXOF_X_POS sd-write
  1 sd-cy sd-pos INDEXOF_Y_POS sd-write
  2 sd-cz sd-pos INDEXOF_Z_POS sd-write
  0 INDEXOF_ROTATION_A sd-write
  MB_VZ me sch@ negate 0.16 *
  INDEXOF_ROTATION_B sd-actor read-actor-mailbox sd-ease-angle INDEXOF_ROTATION_B sd-write
  MB_VY me sch@ MB_VX me sch@ sd-atan2
  INDEXOF_ROTATION_C sd-actor read-actor-mailbox sd-ease-angle INDEXOF_ROTATION_C sd-write
  sd-animate if
    me sd-phases + 1 - dup read-mailbox fish-dt 3 * startle-gain * + fish-wrap dup rot write-mailbox
    0.04 startle-gain * sd-actor fish-deform
  then ;
: sd-pose-all sch-n 1 do i sd-pose loop ;
: sd-fish ( k -- )
  MB_ME sc!
  me 1 - 8 mod 3.5 - 0.75 * MB_X me sch!
  me 1 - dup 8 mod - 8 / 1.5 - 0.55 * MB_Y me sch!
  me 4 mod 1.5 - 0.65 * MB_Z me sch!
  me 0.13 * fish-cos MB_VX me sch! 0 MB_VY me sch! me 0.13 * fish-sin MB_VZ me sch!
  0 MB_STARTLE me sch!
  me 1 - 11 * 29 mod 28 / 0.15 * 0.45 + 0.525 / dup
  INDEXOF_X_SCALE sd-write dup INDEXOF_Y_SCALE sd-write INDEXOF_Z_SCALE sd-write
  me 0.211 * fish-wrap me sd-phases + 1 - write-mailbox ;
: sd-setup
  0.7 MB_RR par! -0.7071 MB_COSB par! 2.5 MB_KICK par!
  0 MB_DRO_SWARM par! 6 MB_DRA_SWARM par! 3 MB_DRO_SCHOOL par! 4 MB_DRA_SCHOOL par! 0 sch-regime
  1.25 MB_LEADW par! 0.6 MB_WALL par! 0.6 MB_STARTLE_T par!
  sd-hx negate MB_LOX par! sd-hy negate MB_LOX 1 + par! sd-hz negate MB_LOX 2 + par!
  sd-hx MB_HIX par! sd-hy MB_HIX 1 + par! sd-hz MB_HIX 2 + par!
  INDEXOF_X_POS fish-actor-player read-actor-mailbox sd-cx sd-world>bl sd-prev write-mailbox
  INDEXOF_Y_POS fish-actor-player read-actor-mailbox sd-cy sd-world>bl sd-prev 1 + write-mailbox
  INDEXOF_Z_POS fish-actor-player read-actor-mailbox sd-cz sd-world>bl sd-prev 2 + write-mailbox
  1 sd-lhead write-mailbox 0 sd-lhead 1 + write-mailbox 0 sd-lhead 2 + write-mailbox
  0 sd-clock write-mailbox 0 sd-ptr write-mailbox 0 sd-blend write-mailbox 0 sd-mode write-mailbox 0 sd-dart-prev write-mailbox
  sch-n 1 do 0 i sd-times + 1 - write-mailbox loop
  sd-actors sch-n 1 do i sd-fish loop 1 sd-flag write-mailbox ;
: sd-dart-check
  \ Observe displacement after physics: a button/timer alone is not a disturbance.
  \ 5 BL/s exceeds the normal swim burst (4.49 BL/s); wait for a real dart.
  aq-dart-t read-mailbox 0 > if
    sd-dart-prev read-mailbox 0 = sd-lspeed read-mailbox 5 > & if
      5 sch-startle-all 1 sd-dart-prev write-mailbox
    then
  else 0 sd-dart-prev write-mailbox then ;
: sd-tick
  sd-flag read-mailbox 0 = if sd-setup then
  sd-leader sd-mode-update sd-dart-check
  sd-clock read-mailbox fish-dt + sd-clock write-mailbox
  sd-frozen not if 4 profile-begin sd-round-robin 4 profile-end then
  5 profile-begin sd-pose-all 5 profile-end ;
