//! Emit textile's input INI from the asset registry.
//!
//! Subsumes the prep step's `ini.prp` expansion
//! (`wfsource/levels.src/ini.prp`). Textile-rs reads room membership by
//! looking up `[Rooms]` section keys — one line per room with a
//! comma-separated list of IFF filenames:
//!
//! ```ini
//! [Version]
//! levelcon = levcomp-rs
//!
//! [Rooms]
//! nRooms = <N>
//! Room0 = <iff1>,<iff2>,…
//! Room1 = <iff3>,<iff4>,…
//! Perm  = <iffA>,<iffB>,…
//! ```
//!
//! Two behaviours match the old `ini.prp` explicitly:
//! - Entries are comma-separated in registration order.
//! - `.map` and `.wav` filenames are filtered out (per `ini.prp:13`).
//!
//! Textile-rs's `main.rs:229-238` iterates `Room0, Room1, …` and then the
//! singular `Perm` pseudo-room; this emitter uses those exact key names
//! regardless of how `asset.inc`'s `ROOM_START(name,id)` was labelled,
//! so the `Permanents`-vs-`Perm` historical mismatch between asset.inc
//! and textile doesn't bite us.

use crate::asset_registry::{AssetRegistry, ROOM_PERM};
use std::fs;
use std::io;
use std::path::Path;

pub fn write(
    assets: &AssetRegistry,
    _level_name: &str,
    out_path: &Path,
) -> io::Result<()> {
    // Collect distinct non-PERM room indices in sorted order.
    let mut room_indices: Vec<i32> = assets.entries().iter()
        .map(|(_, id)| room_from_id(*id))
        .filter(|&r| r != ROOM_PERM)
        .collect();
    room_indices.sort();
    room_indices.dedup();

    let n_rooms = room_indices.last().map(|r| r + 1).unwrap_or(0);

    let mut s = String::new();
    s.push_str(";============================================================================\n");
    s.push_str("; textile input INI generated by levcomp-rs (subsumes prep's ini.prp)\n");
    s.push_str(";============================================================================\n");
    s.push_str("[Version]\n");
    s.push_str("levelcon = levcomp-rs\n");
    s.push('\n');
    s.push_str("[Rooms]\n");
    s.push_str(&format!("nRooms = {n_rooms}\n"));

    // `nRooms` is the upper bound of room indices; emit Room0..Room(N-1)
    // so textile's iteration loop finds every key, even empty ones (the
    // per-room `.tga`/`.ruv`/`.cyc` outputs still get produced for texture
    // rooms that carry no meshes — RM0 in snowgoons, for instance).
    for r in 0..n_rooms {
        let key = format!("Room{r}");
        let names = collect_names(assets, r);
        s.push_str(&format!("{key} = {names}\n"));
    }

    // PERM pseudo-room.
    let perm_names = collect_names(assets, ROOM_PERM);
    s.push_str(&format!("Perm = {perm_names}\n"));

    fs::write(out_path, s)
}

fn collect_names(assets: &AssetRegistry, room: i32) -> String {
    assets.entries().iter()
        .filter(|(name, id)| {
            room_from_id(*id) == room && !is_filtered(name)
        })
        .map(|(name, _)| name.as_str())
        .collect::<Vec<_>>()
        .join(",")
}

/// Mirrors `ini.prp`'s ROOM_ENTRY filter: skip `.map` and `.wav` entries.
fn is_filtered(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    lower.ends_with(".map") || lower.ends_with(".wav")
}

fn room_from_id(id: i32) -> i32 {
    let r = ((id as u32) >> 12) & 0xFFF;
    if r == 0xFFF { ROOM_PERM } else { r as i32 }
}
