//! Emit a `snowgoons.iff.txt`-shape LVAS text-IFF from the asset registry.
//!
//! Subsumes the `prep` step: combines what the asset registry knows (packed
//! asset IDs + filenames per room) with the deterministic LVAS skeleton
//! (TOC, ALGN boundaries, and file-include references to the `.lvl` payload
//! and per-room / permanent ASS-slot `.bin` payloads).
//!
//! Output shape (LVAS is the root chunk — see
//! `docs/investigations/2026-04-19-iffcomp-offsetof-arithmetic.md`):
//!
//! ```text
//! { 'LVAS'
//!     { 'TOC'
//!         'ASMP' .offsetof(::'LVAS'::'ASMP') .sizeof(::'LVAS'::'ASMP')
//!         'LVL'  .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'LVL')
//!         'PERM' .offsetof(::'LVAS'::'PERM') .sizeof(::'LVAS'::'PERM')
//!         'RM0'  .offsetof(::'LVAS'::'RM0')  .sizeof(::'LVAS'::'RM0')
//!         …                                             // one per room
//!         'FAKE' .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'ASMP')
//!     }
//!     { 'ALGN' .align(2048) }
//!     { 'ASMP'  …packed-ID { 'STR' "file.iff" } pairs… }
//!     { 'ALGN' .align(2048) }
//!     { 'LVL'  [ "<level>.lvl" ] }
//!     { 'ALGN' .align(2048) }
//!     { 'PERM' [ "perm.bin" ] }
//!     { 'ALGN' .align(2048) }
//!     { 'RM0'  [ "rm0.bin" ] }
//!     …                                                 // one per room
//!     { 'ALGN' .align(2048) }                           // trailing pad
//! }
//! ```
//!
//! Both ASMP emission and TOC entries iterate rooms in `[PERM, RM0, RM1, …]`
//! order, matching the natural iff2lvl / max2lev layout.

use crate::asset_registry::{AssetRegistry, ROOM_PERM};
use std::fs;
use std::io;
use std::path::Path;

/// Compose and write the LVAS text-IFF for `level_stem` into `out_path`.
///
/// `rooms` is the sorted list of room indices that should appear as TOC
/// entries and as chunks in the file (in addition to the always-present
/// PERM chunk). For snowgoons this is typically `[0, 1]` — both rooms get
/// an `ASS`-slot chunk (`rm0.bin` / `rm1.bin`) even if no meshes live in
/// `RM0`, since texture atlases still do.
///
/// The emitted file references sibling `.lvl` / `.bin` payloads by
/// bare filename; `iffcomp-rs` resolves these relative to its CWD, so
/// run `iffcomp -o=<stem>.iff <stem>.iff.txt` from the level directory.
pub fn write(
    assets: &AssetRegistry,
    level_stem: &str,
    rooms: &[i32],
    out_path: &Path,
) -> io::Result<()> {
    let mut s = String::new();
    s.push_str("//=============================================================================\n");
    s.push_str("// snowgoons.iff.txt — generated by levcomp-rs\n");
    s.push_str("// Subsumes the prep step. Build with:\n");
    s.push_str("//   iffcomp -o=<level>.iff <level>.iff.txt\n");
    s.push_str("// from this directory (sibling .lvl and .bin files are referenced by bare name).\n");
    s.push_str("//=============================================================================\n");

    // ── LVAS open ───────────────────────────────────────────────────────────
    s.push_str("{ 'LVAS'\n");

    // ── TOC ─────────────────────────────────────────────────────────────────
    // LVAS is outermost in this compile unit, so single-arg `.offsetof` is
    // both file-absolute and LVAS-header-relative — no subtraction needed.
    s.push_str("\t{ 'TOC'\n");
    s.push_str("\t\t'ASMP' .offsetof(::'LVAS'::'ASMP') .sizeof(::'LVAS'::'ASMP')\n");
    s.push_str("\t\t'LVL'  .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'LVL')\n");
    s.push_str("\t\t'PERM' .offsetof(::'LVAS'::'PERM') .sizeof(::'LVAS'::'PERM')\n");
    for &r in rooms {
        let id = format!("RM{r}");
        // Pad the two-char `RM0` form with a trailing space so the columns
        // line up with `ASMP` / `PERM`. Purely cosmetic.
        let id_col = if id.len() < 4 {
            format!("'{id}' ")
        } else {
            format!("'{id}'")
        };
        s.push_str(&format!(
            "\t\t{id_col} .offsetof(::'LVAS'::{id}) .sizeof(::'LVAS'::{id})\n",
            id_col = id_col,
            id = format!("'{}'", id)
        ));
    }
    // FAKE sentinel: oracle pairs LVL's (relative) offset with ASMP's size.
    s.push_str("\t\t'FAKE' .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'ASMP')\n");
    s.push_str("\t}\n");

    // ── ASMP ────────────────────────────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str("\t// Packed asset ID layout (see `wfsource/source/streams/asset.hp`):\n");
    s.push_str("\t//   bits [31:24]  `type`  — file fourcc code\n");
    s.push_str("\t//   bits [23:12]  `room`  — `fff` = permanent, `000..N` = `RMn`\n");
    s.push_str("\t//   bits [11:0]   `index` — 1-based slot per (room, type);\n");
    s.push_str("\t//                           `ffe` = palette, `fff` = atlas (reserved)\n");
    s.push_str("\t// Type codes (`wfsource/source/streams/assets.inc`):\n");
    s.push_str("\t//   `0 NUL`  `1 TGA`  `2 BMP`  `3 IFF`  `4 ___`\n");
    s.push_str("\t//   `5 RUV`  `6 WAV`  `7 CYC`  `8 CHR`  `9 MAP`\n");
    s.push_str("\t// Example: `$3fff001` = `IFF` + room `fff` (`PERM`) + slot `001`.\n");
    s.push_str("\t{ 'ASMP'\n");
    // PERM entries first, then per-room entries in `rooms` order.
    for (name, id) in assets.entries() {
        if room_from_id(*id) == ROOM_PERM {
            s.push_str(&format!(
                "\t\t${id:x}l {{ 'STR' \"{name}\" }}  // {decoded}\n",
                id = id,
                name = name,
                decoded = decode_id(*id),
            ));
        }
    }
    for &r in rooms {
        for (name, id) in assets.entries() {
            if room_from_id(*id) == r {
                s.push_str(&format!(
                    "\t\t${id:x}l {{ 'STR' \"{name}\" }}  // {decoded}\n",
                    id = id,
                    name = name,
                    decoded = decode_id(*id),
                ));
            }
        }
    }
    s.push_str("\t}\n");

    // ── LVL ─────────────────────────────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str(&format!("\t{{ 'LVL' [ \"{level_stem}.lvl\" ] }}\n"));

    // ── PERM + per-room ASS-slot payloads ───────────────────────────────────
    // Replicates the original iff.prp ROOM_START / ROOM_ENTRY macro
    // expansion (wfsource/levels.src/iff.prp:33-54): each texture / palette
    // / ruv / cyc / mesh file becomes its own `{ 'ASS' $<id>l [ "file" ] }`
    // chunk inside the room wrapper. Hardcoded asset IDs for the four
    // textile outputs; per-mesh IDs come from `assets` (i.e. the same
    // asset.inc LevelCon emitted). Scheme:
    //   palette  $1<room_hex>ffe ["pal<n>.tga" | "palPerm.tga"]
    //   texture  $1<room_hex>fff ["Room<n>.tga" | "Perm.tga"]
    //   rmuv     $5<room_hex>fff ["Room<n>.ruv" | "Perm.ruv"]
    //   ccyc     $7<room_hex>fff ["Room<n>.cyc" | "Perm.cyc"]
    // where room_hex = 3-digit hex of room index (or `fff` for PERM).
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str("\t{ 'PERM'\n");
    s.push_str("\t\t{ 'ASS' $1fffffel [ \"palPerm.tga\" ] }  // TGA PERM fff:ffe\n");
    s.push_str("\t\t{ 'ASS' $1ffffffl [ \"Perm.tga\" ] }     // TGA PERM fff:fff\n");
    s.push_str("\t\t{ 'ASS' $5ffffffl [ \"Perm.ruv\" ] }     // RUV PERM fff:fff\n");
    s.push_str("\t\t{ 'ASS' $7ffffffl [ \"Perm.cyc\" ] }     // CYC PERM fff:fff\n");
    for (name, id) in assets.entries() {
        if room_from_id(*id) == ROOM_PERM && !name.ends_with(".tga") {
            s.push_str(&format!(
                "\t\t{{ 'ASS' ${id:x}l [ \"{name}\" ] }}  // {decoded}\n",
                id = id,
                name = name,
                decoded = decode_id(*id),
            ));
        }
    }
    s.push_str("\t}\n");
    for &r in rooms {
        s.push_str("\t{ 'ALGN' .align(2048) }\n");
        s.push_str(&format!("\t{{ 'RM{r}'\n"));
        s.push_str(&format!("\t\t{{ 'ASS' $1{r:03x}ffel [ \"pal{r}.tga\" ] }}      // TGA RM{r} {r:03x}:ffe\n"));
        s.push_str(&format!("\t\t{{ 'ASS' $1{r:03x}fffl [ \"Room{r}.tga\" ] }}    // TGA RM{r} {r:03x}:fff\n"));
        s.push_str(&format!("\t\t{{ 'ASS' $5{r:03x}fffl [ \"Room{r}.ruv\" ] }}    // RUV RM{r} {r:03x}:fff\n"));
        s.push_str(&format!("\t\t{{ 'ASS' $7{r:03x}fffl [ \"Room{r}.cyc\" ] }}    // CYC RM{r} {r:03x}:fff\n"));
        for (name, id) in assets.entries() {
            if room_from_id(*id) == r && !name.ends_with(".tga") {
                s.push_str(&format!(
                    "\t\t{{ 'ASS' ${id:x}l [ \"{name}\" ] }}  // {decoded}\n",
                    id = id,
                    name = name,
                    decoded = decode_id(*id),
                ));
            }
        }
        s.push_str("\t}\n");
    }

    // ── trailing ALGN inside LVAS ───────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");

    // ── LVAS close ──────────────────────────────────────────────────────────
    s.push_str("}\n");

    fs::write(out_path, s)
}

/// Decode a packed asset ID into a readable `<FOURCC> <ROOM> <room:index>`
/// comment — type code (TGA/IFF/RUV/CYC/…) from bits [31:24], room from
/// [23:12], slot index from [11:0]. Emitted only as a `//` comment in the
/// generated `.iff.txt`, so iffcomp strips it and the compiled bytes are
/// unchanged.
fn decode_id(id: i32) -> String {
    let u = id as u32;
    let type_bits = ((u >> 24) & 0xFF) as u8;
    let room_bits = ((u >> 12) & 0xFFF) as u16;
    let idx_bits  = (u & 0xFFF) as u16;
    let type_str = match type_bits {
        0 => "NUL",
        1 => "TGA",
        2 => "BMP",
        3 => "IFF",
        4 => "___",
        5 => "RUV",
        6 => "WAV",
        7 => "CYC",
        8 => "CHR",
        9 => "MAP",
        _ => "???",
    };
    let room_str = if room_bits == 0xFFF {
        "PERM".to_string()
    } else {
        format!("RM{}", room_bits)
    };
    format!("{type_str} {room_str} {room_bits:03x}:{idx_bits:03x}")
}

/// Extract the room field from a packed asset ID. Mirrors the helper in
/// `asset_registry` but kept local to avoid exposing it there.
fn room_from_id(id: i32) -> i32 {
    let room_bits = ((id as u32) >> 12) & 0xFFF;
    if room_bits == 0xFFF { ROOM_PERM } else { room_bits as i32 }
}
