//! Emit a `snowgoons.iff.txt`-shape LVAS text-IFF from the asset registry.
//!
//! Subsumes the `prep` step: combines what the asset registry knows (packed
//! asset IDs + filenames per room) with the deterministic LVAS skeleton
//! (TOC, ALGN boundaries, and file-include references to the `.lvl` payload
//! and per-room / permanent ASS-slot `.bin` payloads).
//!
//! Output shape (LVAS is the root chunk — see
//! `docs/investigations/2026-04-19-iffcomp-offsetof-arithmetic.md`):
//!
//! ```text
//! { 'LVAS'
//!     { 'TOC'
//!         'ASMP' .offsetof(::'LVAS'::'ASMP') .sizeof(::'LVAS'::'ASMP')
//!         'LVL'  .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'LVL')
//!         'PERM' .offsetof(::'LVAS'::'PERM') .sizeof(::'LVAS'::'PERM')
//!         'RM0'  .offsetof(::'LVAS'::'RM0')  .sizeof(::'LVAS'::'RM0')
//!         …                                             // one per room
//!         'FAKE' .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'ASMP')
//!     }
//!     { 'ALGN' .align(2048) }
//!     { 'ASMP'  …packed-ID { 'STR' "file.iff" } pairs… }
//!     { 'ALGN' .align(2048) }
//!     { 'LVL'  [ "<level>.lvl" ] }
//!     { 'ALGN' .align(2048) }
//!     { 'PERM' [ "perm.bin" ] }
//!     { 'ALGN' .align(2048) }
//!     { 'RM0'  [ "rm0.bin" ] }
//!     …                                                 // one per room
//!     { 'ALGN' .align(2048) }                           // trailing pad
//! }
//! ```
//!
//! Both ASMP emission and TOC entries iterate rooms in `[PERM, RM0, RM1, …]`
//! order, matching the natural iff2lvl / max2lev layout.

use crate::asset_registry::{AssetRegistry, ROOM_PERM};
use std::fs;
use std::io;
use std::path::Path;

/// Compose and write the LVAS text-IFF for `level_stem` into `out_path`.
///
/// `rooms` is the sorted list of room indices that should appear as TOC
/// entries and as chunks in the file (in addition to the always-present
/// PERM chunk). For snowgoons this is typically `[0, 1]` — both rooms get
/// an `ASS`-slot chunk (`rm0.bin` / `rm1.bin`) even if no meshes live in
/// `RM0`, since texture atlases still do.
///
/// The emitted file references sibling `.lvl` / `.bin` payloads by
/// bare filename; `iffcomp-rs` resolves these relative to its CWD, so
/// run `iffcomp -o=<stem>.iff <stem>.iff.txt` from the level directory.
pub fn write(
    assets: &AssetRegistry,
    level_stem: &str,
    rooms: &[i32],
    out_path: &Path,
) -> io::Result<()> {
    let mut s = String::new();
    s.push_str("//=============================================================================\n");
    s.push_str("// snowgoons.iff.txt — generated by levcomp-rs\n");
    s.push_str("// Subsumes the prep step. Build with:\n");
    s.push_str("//   iffcomp -o=<level>.iff <level>.iff.txt\n");
    s.push_str("// from this directory (sibling .lvl and .bin files are referenced by bare name).\n");
    s.push_str("//=============================================================================\n");

    // ── LVAS open ───────────────────────────────────────────────────────────
    s.push_str("{ 'LVAS'\n");

    // ── TOC ─────────────────────────────────────────────────────────────────
    // LVAS is outermost in this compile unit, so single-arg `.offsetof` is
    // both file-absolute and LVAS-header-relative — no subtraction needed.
    s.push_str("\t{ 'TOC'\n");
    s.push_str("\t\t'ASMP' .offsetof(::'LVAS'::'ASMP') .sizeof(::'LVAS'::'ASMP')\n");
    s.push_str("\t\t'LVL'  .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'LVL')\n");
    s.push_str("\t\t'PERM' .offsetof(::'LVAS'::'PERM') .sizeof(::'LVAS'::'PERM')\n");
    for &r in rooms {
        let id = format!("RM{r}");
        // Pad the two-char `RM0` form with a trailing space so the columns
        // line up with `ASMP` / `PERM`. Purely cosmetic.
        let id_col = if id.len() < 4 {
            format!("'{id}' ")
        } else {
            format!("'{id}'")
        };
        s.push_str(&format!(
            "\t\t{id_col} .offsetof(::'LVAS'::{id}) .sizeof(::'LVAS'::{id})\n",
            id_col = id_col,
            id = format!("'{}'", id)
        ));
    }
    // FAKE sentinel: oracle pairs LVL's (relative) offset with ASMP's size.
    s.push_str("\t\t'FAKE' .offsetof(::'LVAS'::'LVL')  .sizeof(::'LVAS'::'ASMP')\n");
    s.push_str("\t}\n");

    // ── ASMP ────────────────────────────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str("\t{ 'ASMP'\n");
    // PERM entries first, then per-room entries in `rooms` order.
    for (name, id) in assets.entries() {
        if room_from_id(*id) == ROOM_PERM {
            s.push_str(&format!(
                "\t\t${id:x}l {{ 'STR' \"{name}\" }}\n",
                id = id,
                name = name
            ));
        }
    }
    for &r in rooms {
        for (name, id) in assets.entries() {
            if room_from_id(*id) == r {
                s.push_str(&format!(
                    "\t\t${id:x}l {{ 'STR' \"{name}\" }}\n",
                    id = id,
                    name = name
                ));
            }
        }
    }
    s.push_str("\t}\n");

    // ── LVL ─────────────────────────────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str(&format!("\t{{ 'LVL' [ \"{level_stem}.lvl\" ] }}\n"));

    // ── PERM + per-room ASS-slot payloads ───────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");
    s.push_str("\t{ 'PERM' [ \"perm.bin\" ] }\n");
    for &r in rooms {
        s.push_str("\t{ 'ALGN' .align(2048) }\n");
        s.push_str(&format!("\t{{ 'RM{r}' [ \"rm{r}.bin\" ] }}\n", r = r));
    }

    // ── trailing ALGN inside LVAS ───────────────────────────────────────────
    s.push_str("\t{ 'ALGN' .align(2048) }\n");

    // ── LVAS close ──────────────────────────────────────────────────────────
    s.push_str("}\n");

    fs::write(out_path, s)
}

/// Extract the room field from a packed asset ID. Mirrors the helper in
/// `asset_registry` but kept local to avoid exposing it there.
fn room_from_id(id: i32) -> i32 {
    let room_bits = ((id as u32) >> 12) & 0xFFF;
    if room_bits == 0xFFF { ROOM_PERM } else { room_bits as i32 }
}
