#!/usr/bin/env bash
# regen-headers.sh — restore the prep → .pp → .ht pipeline lost in 61761e4.
#
# Historical process (wfsource/source/oas/GNUmakefile @ a2784f6):
#   prep -DTYPEFILE_OAS=<stem> oadtypes.s <stem>.pp
#   perl cstruct.pl <stem>.pp > <stem>.ht
#
# cstruct.pl removed with the rest of the old build system. Reimplemented here
# as an inline awk one-pass filter (no perl dependency) that reproduces the
# same byte-identical output.
#
# Usage:
#   regen-headers.sh [OUTDIR]
#
# OUTDIR defaults to the oas source directory (regenerate in place).
# Pass a temp dir to validate without touching the source tree (the oracle test
# does this).
#
# Must be run from any directory; the script cd-s to its own directory so that
# prep's relative @include paths (oadtypes.s → types.h, <stem>.oas;
# objects.s → objects.mac) resolve correctly.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTDIR="${1:-$SCRIPT_DIR}"
PREP="$SCRIPT_DIR/../../../wftools/prep/prep"
BUILD_SH="$SCRIPT_DIR/../../../wftools/prep/build.sh"

# Build prep if missing (same pattern as oas2oad-rs/tests/oas_to_oad.rs).
if [ ! -x "$PREP" ]; then
    echo "prep not found — building via $(basename "$BUILD_SH") ..." >&2
    bash "$BUILD_SH"
fi

# Canonicalizer: faithful awk port of cstruct.pl (a2784f6).
# Per line: strip trailing whitespace, skip blanks, split on ", strip
# non-[A-Za-z0-9_] from inside-quote fields (odd array indices in 1-based awk),
# rejoin without quotes.  Text outside quotes (type keywords, comments, tabs)
# is untouched.
CSTRUCT_AWK='
  { sub(/[ \t\r]*$/,"") }
  length($0) {
    n = split($0, f, "\"")
    for (i = 2; i <= n; i += 2)
      gsub(/[^A-Za-z0-9_]/, "", f[i])
    s = ""
    for (i = 1; i <= n; i++) s = s f[i]
    print s
  }'

TMP=$(mktemp -d /tmp/regen-oas.XXXXXX)
trap 'rm -rf "$TMP"' EXIT

cd "$SCRIPT_DIR"

echo "Regenerating .ht headers..." >&2
count=0
for ht in *.ht; do
    stem="${ht%.ht}"
    "$PREP" -dTYPEFILE_OAS="$stem" oadtypes.s "$TMP/$stem.pp"
    awk "$CSTRUCT_AWK" "$TMP/$stem.pp" > "$OUTDIR/$stem.ht"
    count=$((count + 1))
done
echo "  $count .ht files written to $OUTDIR" >&2

echo "Regenerating objects.{c,e,h}..." >&2
"$PREP" objects.s  "$OUTDIR/objects.c"
"$PREP" objects.es "$OUTDIR/objects.e"
"$PREP" objects.hs "$OUTDIR/objects.h"
echo "  objects.c objects.e objects.h written to $OUTDIR" >&2

echo "Generating engine/mutation/kpropmap_generated.inc..." >&2
# In normal mode (OUTDIR == SCRIPT_DIR) write to the canonical source-tree location.
# In oracle/test mode (OUTDIR is a temp dir) write alongside the other outputs so the
# caller can diff against the committed file without touching the source tree.
if [ "$OUTDIR" = "$SCRIPT_DIR" ]; then
    KPROPMAP_INC="$SCRIPT_DIR/../../../engine/mutation/kpropmap_generated.inc"
else
    KPROPMAP_INC="$OUTDIR/kpropmap_generated.inc"
fi
# Parse data fields from a .ht struct file.
# $1/$2 = awk fields (type, name;); blk/BLK/Struct = awk -v variables.
GEN_FIELDS='
$1 == "fixed32" || $1 == "int32" {
    name = $2; sub(/[;\/].*/, "", name)
    if (name ~ /^[A-Za-z_][A-Za-z0-9_]*$/)
        printf "{\"" blk "." name "\", {PropInfo::" BLK ", offsetof(" Struct ", " name "), %s}},\n", ($1 == "fixed32" ? "true" : "false")
}'
{
    printf '// kpropmap_generated.inc — auto-generated by regen-headers.sh. DO NOT EDIT.\n'
    printf '// Regenerate: task gen-oas-headers\n'
    printf '// common block\n'
    awk -v blk=common   -v BLK=COMMON   -v Struct=_Common   "$GEN_FIELDS" "$OUTDIR/common.ht"
    printf '// movebloc block\n'
    awk -v blk=movebloc -v BLK=MOVEBLOC -v Struct=_Movement "$GEN_FIELDS" "$OUTDIR/movebloc.ht"
    printf '// mesh block\n'
    awk -v blk=mesh     -v BLK=MESH     -v Struct=_Mesh     "$GEN_FIELDS" "$OUTDIR/mesh.ht"
} > "$KPROPMAP_INC"
echo "  kpropmap_generated.inc written" >&2

echo "Generating engine/wf_edit/name_to_path_generated.inc..." >&2
if [ "$OUTDIR" = "$SCRIPT_DIR" ]; then
    NAMETOPATH_INC="$SCRIPT_DIR/../../../engine/wf_edit/name_to_path_generated.inc"
else
    NAMETOPATH_INC="$OUTDIR/name_to_path_generated.inc"
fi
# Parse OAD names from .inc files (the pre-prep sources, not the generated .ht structs).
# First arg of TYPEENTRY* is the OAD name exactly as stored in .lev/Doc.
# Struct member = OAD name with spaces removed.  is_float iff TYPEENTRYFIXED32.
# Skip TYPEENTRYXDATA_NOTES (no field-name arg) and structural macros.
GEN_NAMEPATH='
/TYPEENTRY/ && !/TYPEENTRYXDATA_NOTES/ && !/^[ \t]*@/ {
    line = $0
    sub(/.*TYPEENTRY[A-Z_0-9]+\(/, "", line) # strip up to first (
    sub(/[,)].*/, "", line)                  # keep first arg only
    oad = line; gsub(/^[ \t]+|[ \t]+$/, "", oad)
    member = oad; gsub(/ /, "", member)
    if (member ~ /^[A-Za-z_][A-Za-z0-9_]*$/)
        printf "{\"" oad "\", {\"" blk "." member "\", %s}},\n",
               ($0 ~ /TYPEENTRYFIXED32/) ? "true" : "false"
}'
{
    printf '// name_to_path_generated.inc — auto-generated by regen-headers.sh. DO NOT EDIT.\n'
    printf '// Regenerate: task gen-oas-headers\n'
    printf '// common block\n'
    awk -v blk=common   "$GEN_NAMEPATH" "$SCRIPT_DIR/common.inc"
    printf '// movebloc block\n'
    awk -v blk=movebloc "$GEN_NAMEPATH" "$SCRIPT_DIR/movebloc.inc"
    printf '// mesh block\n'
    awk -v blk=mesh     "$GEN_NAMEPATH" "$SCRIPT_DIR/mesh.inc"
} > "$NAMETOPATH_INC"
echo "  name_to_path_generated.inc written" >&2

echo "Done." >&2
