"""
blender_create_condo.py — convert the 205/639 + 205/640 condo model into a
walkable WorldFoundry level.

Source: ~/docs/aircon/units-639-640.blend (generated by ~/scripts/aircon-blender.py,
rebuild with `cd ~ && task aircon-blender`). Read only — never written.

Usage:
    blender --background --python blender_create_condo.py -- [path/to/units-639-640.blend]
    task build-level -- condo_639_640          # or just: task condo-level
    task run-condo

Pattern: wflevels/moon_site01/blender_create_moon.py — import the snowgoons
scaffold for infrastructure, strip its gameplay, add our geometry as `statplat`
mesh actors (Jolt builds a trimesh body from the render mesh, so walls/floors are
solid and doorways passable straight from the geometry), export.

Plan: docs/plans/2026-09-19-condo-639-640-level.md
"""

import math
import os
import re
import sys

import addon_utils
import bpy
from mathutils import Matrix, Vector

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO       = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
SNOWGOONS  = os.path.join(REPO, 'wflevels', 'snowgoons-blender', 'snowgoons-blender.lev')
OAD_DIR    = os.path.join(REPO, 'wftools', 'wf_oad', 'tests', 'fixtures')
LEVEL_NAME = os.environ.get('CONDO_LEVEL', 'condo_639_640')   # e.g. condo_639_640_tour for the tour build
OUT_DIR    = os.path.join(REPO, 'wflevels', LEVEL_NAME)
OUT_LEV    = os.path.join(OUT_DIR, LEVEL_NAME + '.lev')
OUT_BLEND  = os.path.join(OUT_DIR, LEVEL_NAME + '.blend')      # the assembled WF scene, for inspection in Blender
TOUR_PATH  = os.environ.get('CONDO_TOUR', '')                  # path .json → player walks it (see tour_forth below)

_argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
SRC_BLEND = os.path.abspath(os.path.expanduser(
    _argv[0] if _argv else os.environ.get('CONDO_BLEND', '~/docs/aircon/units-639-640.blend')))
if not os.path.isfile(SRC_BLEND):
    raise SystemExit(f"[condo] source .blend not found: {SRC_BLEND} "
                     f"(rebuild with `cd ~ && task aircon-blender`, or pass the path)")

# Collections to bring over. `640-midea-option-B-over-door` is the rejected
# alternative (hidden) and is never appended.
SRC_COLLECTIONS = ['205-639', '205-640', '640-midea-option-A-closet-wall']

# ── Level constants (metres, WF == Blender axes: X right, Y depth, Z up) ───────
WALL_H        = 2.7
GLASS_T       = 0.10    # source panes are 0.02 m — sub-decimetre slabs have gone
                        # invisible before (troubleshooting § "too thin in
                        # camera-depth axis"); 0.10 fills the wall opening exactly.
GROUND        = (-14.0, -22.0, 14.0, 6.0)   # x0, y0, x1, y1 of the site slab
GROUND_T      = 0.30
PLAYER_H      = 1.70
PLAYER_SPAWN  = tuple(float(v) for v in os.environ['CONDO_SPAWN'].split(',')) if os.environ.get('CONDO_SPAWN') \
                else (4.66, -17.0, 0.30)     # on the ground outside 639's front door (CONDO_SPAWN=x,y,z overrides)
TOUR = None
if TOUR_PATH:
    import json
    with open(TOUR_PATH) as _f:
        TOUR = json.load(_f)
    PLAYER_SPAWN = tuple(TOUR.get('spawn', PLAYER_SPAWN))
    os.environ.setdefault('CONDO_ACCEL', str(TOUR.get('accel', 105)))
    os.environ.setdefault('CONDO_DECEL', str(TOUR.get('decel', 0.85)))
CAM_OFFSET    = (0.0, -3.5, 9.0)             # doll-house view: 69° elevation from the south
LOOK_OFFSET   = (0.0, 0.0, 0.9)              # aim at the player's chest, not the feet
ROOM_CENTRE   = (0.0, -8.0, 6.0)
ROOM_HALF     = (15.0, 16.0, 10.0)
NUM_MAILBOXES = 100
SUN_ALT_DEG   = 50.0
SUN_AZ_DEG    = 30.0

# ── 1. Clean scene, enable add-on, import the snowgoons scaffold ─────────────
bpy.ops.wm.read_factory_settings(use_empty=True)
addon_utils.enable("wf_blender", default_set=False, persistent=False)
if not hasattr(bpy.ops.wf, 'import_level'):
    raise SystemExit("[condo] wf_blender add-on not available — install it "
                     "(task blender-install until the apt package exists)")
scene = bpy.context.scene

print(f"[condo] importing scaffold {SNOWGOONS}")
bpy.ops.wf.import_level(filepath=SNOWGOONS)

KEEP_CLASSES = {'director', 'camera', 'levelobj', 'matte', 'light',
                'room', 'camshot', 'target', 'player'}


def get_class(obj):
    schema = obj.get('wf_schema_path', '')
    return os.path.splitext(os.path.basename(schema))[0] if schema else ''


def find_by_class(cn):
    for obj in bpy.data.objects:
        if get_class(obj) == cn:
            return obj
    return None


def attach_schema(obj, oad_name):
    obj['wf_schema_path'] = os.path.join(OAD_DIR, oad_name + '.oad')


for obj in list(bpy.data.objects):
    if get_class(obj) not in KEEP_CLASSES:
        bpy.data.objects.remove(obj, do_unlink=True)
seen = set()
for obj in list(bpy.data.objects):
    cn = get_class(obj)
    if cn in seen:
        bpy.data.objects.remove(obj, do_unlink=True)
    else:
        seen.add(cn)
print("[condo] scaffold classes:", sorted({get_class(o) for o in bpy.data.objects}))
# Snowgoons meshes carried .tga textures; none of the survivors render (all
# Model Type 'None' below) except the player, whose mesh we replace.

# ── 2. Append the condo collections from the source .blend ───────────────────
before = set(bpy.data.objects)
for cname in SRC_COLLECTIONS:
    bpy.ops.wm.append(filepath=os.path.join(SRC_BLEND, 'Collection', cname),
                      directory=os.path.join(SRC_BLEND, 'Collection') + os.sep,
                      filename=cname, link=False)
appended = [o for o in bpy.data.objects if o not in before]
print(f"[condo] appended {len(appended)} objects from {os.path.basename(SRC_BLEND)}")
bpy.context.view_layer.update()


def sanitize(name):
    """Blender name → asset filename slug: lowercase, runs of non-alnum → '_'.

    The engine's asset string map holds 31 bytes per name (assets.cc
    ReadAssetMap asserts `BytesLeft() < 32`), so `<slug>.iff` must stay ≤ 30
    chars: long names are cut to 21 chars + a 4-hex hash of the full name.
    """
    import zlib
    slug = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')
    if len(slug) > 26:
        slug = f"{slug[:21].rstrip('_')}_{zlib.crc32(name.encode()) & 0xffff:04x}"
    return slug


def make_flat_material(name, rgb):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next((n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED'), None)
    if bsdf:
        bsdf.inputs['Base Color'].default_value = (*rgb, 1.0)
    mat.diffuse_color = (*rgb, 1.0)
    return mat


def bake_transform(obj):
    """Fold rotation+scale (and any parent transform) into the mesh verts, leaving
    only a translation on the object. The Jolt trimesh body is built from raw
    local verts and ignores actor scale/rotation (troubleshooting § "Per-actor
    scale"), and the render path shears a rotated non-uniform scale."""
    mw = obj.matrix_world.copy()
    obj.parent = None
    if obj.data.users > 1:
        obj.data = obj.data.copy()
    rs = mw.to_3x3()
    for v in obj.data.vertices:
        v.co = rs @ v.co
    obj.matrix_world = Matrix.Translation(mw.to_translation())
    obj.data.update()


# The engine computes each face normal at load as (v2−v0)×(v1−v0) and asserts its
# length > Scalar(0,4) ≈ 6.1e-5 in 1.15.16 fixed point (math/vector3.hpi:243,
# "Probably have a polygon which is too small") — i.e. any triangle with area
# < ~3e-5 m² aborts the level. Bevelled-curve corners produce exactly those.
MIN_FACE_AREA = 8e-5
_dropped = {'faces': 0}


def clean_mesh(mesh, recalc=True):
    import bmesh
    bm = bmesh.new()
    bm.from_mesh(mesh)
    bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
    bmesh.ops.triangulate(bm, faces=bm.faces)
    tiny = [f for f in bm.faces if f.calc_area() < MIN_FACE_AREA]
    if tiny:
        _dropped['faces'] += len(tiny)
        bmesh.ops.delete(bm, geom=tiny, context='FACES_ONLY')
        bmesh.ops.delete(bm, geom=[v for v in bm.verts if not v.link_faces], context='VERTS')
    if recalc:
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()


def curve_to_mesh(obj):
    """Bevelled POLY curve → tube mesh object of the same name (materials kept)."""
    dg = bpy.context.evaluated_depsgraph_get()
    ev = obj.evaluated_get(dg)
    me = bpy.data.meshes.new_from_object(ev, preserve_all_data_layers=True, depsgraph=dg)
    if not me.materials:
        for m in obj.data.materials:
            me.materials.append(m)
    me.name = obj.name
    cols = list(obj.users_collection)
    name, mw = obj.name, obj.matrix_world.copy()
    bpy.data.objects.remove(obj, do_unlink=True)
    new = bpy.data.objects.new(name, me)
    new.matrix_world = mw
    for c in cols:
        c.objects.link(new)
    return new


def as_statplat(obj):
    attach_schema(obj, 'statplat')
    obj['wf_Mobility']           = 'Anchored'
    obj['wf_Model Type']         = 'Mesh'
    obj['wf_Visibility Mailbox'] = 1
    # Actor NAME stays the Blender name; the mesh file gets a dot/hyphen-free slug
    # so the asset tools never see `foo.001.iff`.
    obj['wf_original_mesh_name'] = sanitize(obj.name) + '.iff'


def collection_hidden(obj):
    return any(c.hide_viewport or c.hide_render for c in obj.users_collection)


# ── 3. Classify and convert the appended objects ─────────────────────────────
mat_grey = make_flat_material('prop-grey', (0.80, 0.80, 0.82))
room_outlines = []      # (name, world bbox min, world bbox max)
stats = {'mesh': 0, 'curve': 0, 'room': 0, 'skipped': []}

for obj in list(appended):
    if obj.hide_viewport or obj.hide_render or collection_hidden(obj):
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if obj.type == 'CURVE':
        obj = curve_to_mesh(obj)
        bake_transform(obj)
        clean_mesh(obj.data, recalc=False)       # tube normals already point outward
        as_statplat(obj)
        stats['curve'] += 1
        continue
    if obj.type != 'MESH':
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if len(obj.data.polygons) == 0:
        # display-WIRE room outline: remember its world bbox, drop the object
        corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
        mn = Vector((min(c.x for c in corners), min(c.y for c in corners), min(c.z for c in corners)))
        mx = Vector((max(c.x for c in corners), max(c.y for c in corners), max(c.z for c in corners)))
        room_outlines.append((obj.name, mn, mx))
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    is_glass = any(m and m.name == 'glass' for m in obj.data.materials)
    if is_glass and abs(obj.scale.y) < 0.05:
        obj.scale.y = GLASS_T
        bpy.context.view_layer.update()
    bake_transform(obj)
    clean_mesh(obj.data)
    if not obj.data.materials:
        obj.data.materials.append(mat_grey)          # consumer units have no material
    as_statplat(obj)
    stats['mesh'] += 1

print(f"[condo] converted: {stats['mesh']} meshes, {stats['curve']} tubes, "
      f"{len(room_outlines)} room outlines; dropped {_dropped['faces']} sub-threshold faces; "
      f"skipped hidden: {stats['skipped']}")

# ── 4. Room outlines → named `target` locators (bbox = room, no Jolt body) ───
target_proto = find_by_class('target')
assert target_proto is not None, "snowgoons scaffold has no target"
target_proto.name = 'CamTarget'
for name, mn, mx in room_outlines:
    t = target_proto.copy()
    t.data = None
    t.name = name
    centre = (mn + mx) / 2.0
    t.location = centre
    t.rotation_euler = (0.0, 0.0, 0.0)
    t.scale = (1.0, 1.0, 1.0)
    half = (mx - mn) / 2.0
    t['wf_original_bbox'] = (-half.x, -half.y, -half.z, half.x, half.y, half.z)
    t['wf_had_authored_bbox'] = True
    t['wf_original_mesh_name'] = ''
    t['wf_Model Type'] = 'None'
    scene.collection.objects.link(t)
stats['room'] = len(room_outlines)

# ── 5. Site ground slab (so a front door never leads out of the room bbox) ───
# The ground has a hole exactly under each shell (outline taken from the shell's own
# slab-bottom faces), so it meets the unit floors edge-to-edge at z=0 and never overlaps them — coplanar overlap z-fights, and a
# lowered slab is a ledge Jolt's CharacterVirtual (no stair-step) treats as a wall.
# Built as a slab minus one closed PRISM per shell outline (EXACT boolean). Using the
# shells themselves as operands fails silently (they aren't closed solids — the solver
# merges their slab faces into the ground), and bmesh triangle_fill /
# mathutils.geometry.tessellate_polygon both mis-triangulate the concave loops.
def slab_outline(shell_obj, z_bottom=-0.15, tol=1e-3):
    """World-space boundary loops of the shell's slab-bottom faces, lifted to z=0."""
    me, mw = shell_obj.data, shell_obj.matrix_world
    wco = [mw @ v.co for v in me.vertices]
    slab = [pg for pg in me.polygons if all(abs(wco[i].z - z_bottom) < tol for i in pg.vertices)]
    assert slab, f"{shell_obj.name}: no slab-bottom faces at z={z_bottom}"
    count = {}
    for pg in slab:
        for e in pg.edge_keys:
            count[e] = count.get(e, 0) + 1
    edges = [e for e, c in count.items() if c == 1]
    return [((wco[a].x, wco[a].y, 0.0), (wco[b].x, wco[b].y, 0.0)) for a, b in edges]


def order_loop(edges):
    """Edge list (each vert degree 2) → one ordered closed polyline of (x, y, z)."""
    nxt = {}
    for a, b in edges:
        nxt.setdefault(a, []).append(b)
        nxt.setdefault(b, []).append(a)
    assert all(len(v) == 2 for v in nxt.values()), "slab outline is not a simple loop"
    start = edges[0][0]
    loop, prev, cur = [start], None, start
    while True:
        cand = [n for n in nxt[cur] if n != prev] or nxt[cur]
        prev, cur = cur, cand[0]
        if cur == start:
            break
        loop.append(cur)
    assert len(loop) == len(edges), f"outline loop {len(loop)} ≠ {len(edges)} edges (multiple loops?)"
    return loop


import bmesh as _bmesh


def prism_mesh(name, loop, z0, z1):
    """Closed manifold prism over an ordered (x, y) loop — a clean boolean operand."""
    bm = _bmesh.new()
    bot = [bm.verts.new((v[0], v[1], z0)) for v in loop]
    top = [bm.verts.new((v[0], v[1], z1)) for v in loop]
    bm.faces.new(bot)
    bm.faces.new(top)
    n = len(loop)
    for i in range(n):
        bm.faces.new((bot[i], bot[(i + 1) % n], top[(i + 1) % n], top[i]))
    _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    return me


gx0, gy0, gx1, gy1 = GROUND
_box = _bmesh.new()
_bmesh.ops.create_cube(_box, size=1.0)
_gbase = bpy.data.meshes.new('site-ground-base')
_box.to_mesh(_gbase)
_box.free()
ground = bpy.data.objects.new('site-ground', _gbase)
scene.collection.objects.link(ground)
ground.scale = (gx1 - gx0, gy1 - gy0, GROUND_T)
ground.location = ((gx0 + gx1) / 2.0, (gy0 + gy1) / 2.0, -GROUND_T / 2.0)
cutters, n_outline = [], 0
for shell_name in ('unit-639', 'unit-640'):
    shell = bpy.data.objects.get(shell_name)
    assert shell is not None, f"missing shell {shell_name}"
    edges = slab_outline(shell)
    n_outline += len(edges)
    cutter = bpy.data.objects.new('cut-' + shell_name, prism_mesh('cut-' + shell_name, order_loop(edges), -1.0, 1.0))
    scene.collection.objects.link(cutter)
    cutters.append(cutter)
    mod = ground.modifiers.new('cut-' + shell_name, 'BOOLEAN')
    mod.operation = 'DIFFERENCE'
    mod.object = cutter
    mod.solver = 'EXACT'
bpy.context.view_layer.update()
_dg = bpy.context.evaluated_depsgraph_get()
_gev = ground.evaluated_get(_dg)
gmesh_cut = bpy.data.meshes.new_from_object(_gev, depsgraph=_dg)
gmesh_cut.transform(_gev.matrix_world)           # bake scale/location: verts in world space
ground.modifiers.clear()
ground.data = gmesh_cut
ground.scale = (1.0, 1.0, 1.0)
ground.location = (0.0, 0.0, 0.0)
bpy.data.meshes.remove(_gbase)
for c in cutters:
    cm = c.data
    bpy.data.objects.remove(c, do_unlink=True)
    bpy.data.meshes.remove(cm)
gmesh = gmesh_cut
gmesh.name = 'site-ground'
gmesh.update()
gmesh.materials.append(make_flat_material('site-ground', (0.55, 0.58, 0.52)))
for poly in gmesh.polygons:
    poly.material_index = 0
clean_mesh(gmesh)
zs = [v.co.z for v in gmesh.vertices]
assert -GROUND_T - 1e-3 < min(zs) and max(zs) < 1e-3, f"site-ground z-range {min(zs)}..{max(zs)} — boolean cut went wrong"
as_statplat(ground)
print(f"[condo] site-ground: {n_outline} outline edges cut out, "
      f"{len(gmesh.vertices)} verts, {len(gmesh.polygons)} tris")

# ── 6. Player: 1.7 m figure, feet at local z=0, +X front marker ──────────────
def build_figure():
    mat_body = make_flat_material('figure-body', (0.20, 0.32, 0.55))
    mat_head = make_flat_material('figure-head', (0.90, 0.75, 0.60))
    mat_mark = make_flat_material('figure-front', (0.95, 0.25, 0.20))
    parts = []
    bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.20, depth=1.20, location=(0, 0, 0.60))
    parts.append((bpy.context.object, mat_body))
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.16, segments=10, ring_count=6, location=(0, 0, 1.50))
    parts.append((bpy.context.object, mat_head))
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0.20, 0, 1.10))
    mark = bpy.context.object
    mark.scale = (0.08, 0.16, 0.20)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    parts.append((mark, mat_mark))
    for o, m in parts:
        o.data.materials.clear()
        o.data.materials.append(m)
        for p in o.data.polygons:
            p.material_index = 0
    bpy.ops.object.select_all(action='DESELECT')
    for o, _ in parts:
        o.select_set(True)
    body = parts[0][0]
    bpy.context.view_layer.objects.active = body
    bpy.ops.object.join()
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
    min_z = min(v.co.z for v in body.data.vertices)
    for v in body.data.vertices:
        v.co.z -= min_z
    body.data.name = 'figure'
    return body


player = find_by_class('player')
assert player is not None, "snowgoons scaffold has no player"
_fig = build_figure()
player.name = 'Player'
player.data = _fig.data
bpy.data.objects.remove(_fig, do_unlink=True)
# The imported scaffold player carries snowgoons' authored bbox (`wf_original_bbox`,
# ±0.33 × ±0.36 × 0…2.0 m) and the exporter prefers it over the mesh — with it the
# Jolt capsule is 2.0 m tall and can't pass a 2.0 m door header. Drop it so the
# BOX3 (→ capsule radius 0.2, height 1.66) comes from the figure we just built.
for key in ('wf_original_bbox', 'wf_had_authored_bbox'):
    if key in player:
        del player[key]
player.location = PLAYER_SPAWN
player.scale = (1.0, 1.0, 1.0)
player.rotation_euler = (0.0, 0.0, math.pi / 2)      # face +Y: into the units, doom-stick strafe = screen X
player['wf_Mobility']              = 'Physics'
player['wf_Mass']                  = 70.0
player['wf_Model Type']            = 'Mesh'
player['wf_Visibility Mailbox']    = 1
# Calibrated on the bridge (motion profile of a straight walk): ground speed is
# the terminal velocity of `Running Acceleration` against `Running Deceleration`
# 0.85 — accel 8 → 0.31 m/s, 40 → 1.55 m/s, 80 → 3.0 m/s (≈ accel/26) — and
# `Max Ground Speed` never binds at these values. 40 = indoor walking pace.
# CONDO_ACCEL / CONDO_SPEED override for tour recordings (4 m/s ≈ accel 105).
player['wf_Running Acceleration']  = float(os.environ.get('CONDO_ACCEL', 40.0))
player['wf_Running Deceleration']  = float(os.environ.get('CONDO_DECEL', 0.85))   # 0.85 = long glide; tour uses more
player['wf_Max Ground Speed']      = float(os.environ.get('CONDO_SPEED', 4.0))
player['wf_Jumping Acceleration']  = 5.0          # a small hop, not a platformer jump
player['wf_Falling Acceleration']  = 9.81
player['wf_Air Acceleration']      = 0.0
player['wf_Max Air Speed']         = 4.0
player['wf_Horiz Air Drag']        = 1.5
player['wf_Turn Rate']             = 0.0          # LEFT/RIGHT strafe (doom-stick), no rotation
player['wf_Script Controls Input'] = 'True'

JOY_UP, JOY_DOWN, JOY_RIGHT, JOY_LEFT = 1 << 11, 1 << 12, 1 << 13, 1 << 14   # hal/sjoystic.h EJ_BUTTONB_*
MB_LEG, MB_HOLD_UNTIL, MB_DONE = 500, 501, 502   # global user mailboxes (2–999, shared)


def tour_forth(tour):
    """Compile the waypoint list into a per-tick zForth state machine.

    Global mailbox 500 holds the current leg. A move leg is a *servo*: it pushes
    the player toward the waypoint coordinate from either side (joystick bits by
    sign of the error) and advances only when the error is within `tol_m` AND the
    player's speed along that axis (X/YSPEED mailboxes) is below `stop_speed` —
    so momentum can never carry him past a doorway into a jamb (which "complete
    once past the target" did, run-dependently). A labelled waypoint adds a hold
    leg (bits 0) timed on INDEXOF_TIME via mailbox 501. The last leg sets mailbox
    502 = 1 so a recorder knows the tour is over. Position-based → replays the
    same at any frame rate.
    """
    hold = float(tour.get('hold_seconds', 0.5))
    tol = float(tour.get('tol_m', 0.12))
    stop_speed = float(tour.get('stop_speed', 0.4))
    legs = []                                   # (bits, axis, target, label)  bits = "+" direction bits
    px, py = tour['spawn'][0], tour['spawn'][1]
    for wp in tour['waypoints']:
        x, y = wp['at']
        dx, dy = x - px, y - py
        assert (abs(dx) < 1e-6) != (abs(dy) < 1e-6), f"leg to {wp['at']} must be axis-aligned (from {px, py})"
        legs.append(('X', x, None) if abs(dx) > 1e-6 else ('Y', y, None))
        if wp.get('room'):
            legs.append(('HOLD', hold, wp['room']))
        px, py = x, y
    lines = ["\\ wf", f"{MB_LEG} read-mailbox"]          # ( leg )
    for k, (kind, val, label) in enumerate(legs):
        nxt = k + 1
        if kind in ('X', 'Y'):
            pos_mb, spd_mb = (f'INDEXOF_{kind}_POS', f'INDEXOF_{kind}SPEED')
            plus, minus = (JOY_RIGHT, JOY_LEFT) if kind == 'X' else (JOY_UP, JOY_DOWN)
            # ( leg ) → err = pos − target; err > tol → push minus; err < −tol → push plus;
            # else stop, and advance once |speed| < stop_speed.
            lines.append(
                f"dup {k} = if {pos_mb} read-mailbox {val} - "
                f"dup {tol} > if drop {minus} INDEXOF_INPUT write-mailbox else "
                f"dup {-tol} < if drop {plus} INDEXOF_INPUT write-mailbox else "
                f"drop 0 INDEXOF_INPUT write-mailbox "
                f"{spd_mb} read-mailbox abs {stop_speed} < if drop {nxt} dup {MB_LEG} write-mailbox then "
                f"then then then")
        else:   # hold `val` seconds at the labelled room
            lines.append(
                f"dup {k} = if 0 INDEXOF_INPUT write-mailbox "
                f"{MB_HOLD_UNTIL} read-mailbox 0 = if INDEXOF_TIME read-mailbox {val} + {MB_HOLD_UNTIL} write-mailbox then "
                f"INDEXOF_TIME read-mailbox {MB_HOLD_UNTIL} read-mailbox >= if "
                f"0 {MB_HOLD_UNTIL} write-mailbox drop {nxt} dup {MB_LEG} write-mailbox then then")
    lines.append(f"dup {len(legs)} = if 0 INDEXOF_INPUT write-mailbox 1 {MB_DONE} write-mailbox then")
    lines.append("drop")
    return "\n".join(lines) + "\n", legs


if TOUR:
    _script, _legs = tour_forth(TOUR)
    player['wf_Script'] = _script
    player['wf_Falling Acceleration'] = 9.81
    print(f"[condo] tour: {len(_legs)} legs, {sum(1 for l in _legs if l[2])} room holds, "
          f"{len(_script)} bytes of Forth")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, LEVEL_NAME + '.legs.json'), 'w') as _f:
        json.dump([{'leg': i, 'kind': kind, 'target': val, 'room': lab} for i, (kind, val, lab) in enumerate(_legs)], _f, indent=1)
else:
    player['wf_Script'] = (
        "\\ wf\n"
        "INDEXOF_HARDWARE_JOYSTICK1_RAW read-mailbox INDEXOF_INPUT write-mailbox\n"
    )

# ── 7. Camera rig: relative doll-house shot ──────────────────────────────────
# BungeeCam: position = (camshot − Follow) + TrackObject; look-at = (Target − Follow)
# + TrackObject (movecam.cc SetCameraParametersFromShot / BungeeCameraHandler::update).
# With Follow = CamTarget at the origin the camshot's own position IS the offset.
target_proto.location = (0.0, 0.0, 0.0)
target_proto['wf_Model Type'] = 'None'
look_at = target_proto.copy()
look_at.data = None
look_at.name = 'LookAt'
look_at.location = LOOK_OFFSET
look_at['wf_Model Type'] = 'None'
scene.collection.objects.link(look_at)

camshot = find_by_class('camshot')
assert camshot is not None
camshot.name = 'cs_dollhouse'
camshot.location = CAM_OFFSET
camshot['wf_Position X'] = 'Relative'
camshot['wf_Position Y'] = 'Relative'
camshot['wf_Position Z'] = 'Relative'
camshot['wf_Rotation']   = 'Fixed'          # 'Track' would spin the offset by the player's heading
camshot['wf_FOV']        = 60.0
camshot['wf_Hither']     = 0.1
camshot['wf_Yon']        = 200.0
camshot['wf_Pan Time In Seconds'] = 0.5
camshot['wf_Model Type']   = 'None'
camshot['wf_Track Object'] = 'Player'
camshot['wf_Target']       = 'LookAt'
camshot['wf_Follow']       = 'CamTarget'

camera = find_by_class('camera')
assert camera is not None
camera.name = 'Camera'
camera.location = tuple(s + o for s, o in zip(PLAYER_SPAWN, CAM_OFFSET))   # start where the shot lands
camera['wf_Model Type'] = 'None'
camera['wf_FoggingColor']            = 0x000000    # indoor: no snowgoons Earth fog
camera['wf_FoggingStartDistance']    = 999.0
camera['wf_FoggingCompleteDistance'] = 1000.0

# ── 8. Lights, matte, director, levelobj ─────────────────────────────────────
light = find_by_class('light')
assert light is not None
light.name = 'Sun'
light.location = (0.0, -8.0, 8.0)
light.rotation_euler = (math.pi / 2 - math.radians(SUN_ALT_DEG), 0.0, math.radians(SUN_AZ_DEG))
light['wf_lightType']  = 'Directional'
light['wf_lightRed']   = 1.0
light['wf_lightGreen'] = 1.0
light['wf_lightBlue']  = 0.96
light['wf_Model Type'] = 'None'
ambient = light.copy()
ambient.data = light.data.copy() if light.data else None
scene.collection.objects.link(ambient)
ambient.name = 'AmbientLight'
ambient.location = (0.0, -8.0, 8.0)
ambient['wf_lightType']  = 'Ambient'
ambient['wf_lightRed']   = 0.45
ambient['wf_lightGreen'] = 0.45
ambient['wf_lightBlue']  = 0.50

matte = find_by_class('matte')
assert matte is not None
matte.name = 'Matte'
matte.location = (0.0, -8.0, 14.0)
matte['wf_Matte Type']         = 'Color'
matte['wf_Background Color']   = 0x9FB8D0
matte['wf_Visibility Mailbox'] = 1
matte['wf_Model Type']         = 'None'

director = find_by_class('director')
if director:
    director.name = 'Director'
    director['wf_Model Type'] = 'None'

levelobj = find_by_class('levelobj')
assert levelobj is not None
levelobj.name = 'Level'
levelobj['wf_Num Mailboxes'] = NUM_MAILBOXES
levelobj['wf_Model Type'] = 'None'

# ── 9. Room bounds ───────────────────────────────────────────────────────────
room = find_by_class('room')
assert room is not None
room.name = 'room_condo'
room.location = ROOM_CENTRE
hx, hy, hz = ROOM_HALF
rel = (-hx, -hy, -hz, hx, hy, hz)
room['wf_original_bbox'] = rel
rv = [(rel[0], rel[1], rel[2]), (rel[3], rel[1], rel[2]), (rel[3], rel[4], rel[2]), (rel[0], rel[4], rel[2]),
      (rel[0], rel[1], rel[5]), (rel[3], rel[1], rel[5]), (rel[3], rel[4], rel[5]), (rel[0], rel[4], rel[5])]
rf = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
rmesh = bpy.data.meshes.new('RoomBounds')
rmesh.from_pydata(rv, [], rf)
rmesh.update()
old = room.data
room.data = rmesh
if old and old.users == 0:
    bpy.data.meshes.remove(old)
# The room mesh is only a bbox visualisation: hide it (eye off) and draw it as wire
# so it never occludes the level in the saved .blend. The exporter writes it anyway.
room.display_type = 'WIRE'
room.hide_render = True
room.hide_set(True)
# Other non-rendering infrastructure draws as wire too (level-building.md § Blender
# Viewport Display by Object Type).
for o in scene.objects:
    if o.get('wf_schema_path') and get_class(o) in ('camera', 'camshot', 'target', 'light',
                                                    'matte', 'levelobj', 'director'):
        o.display_type = 'WIRE'

# Every actor centre must be strictly inside the room bbox or levcomp drops it
# from the render list (troubleshooting § "falls outside every room bbox").
bpy.context.view_layer.update()          # matrix_world is stale until the depsgraph runs
lo = tuple(c - h + 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
hi = tuple(c + h - 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
outside = [o.name for o in scene.objects
           if o.get('wf_schema_path') and get_class(o) != 'room'
           and not all(lo[i] < o.matrix_world.to_translation()[i] < hi[i] for i in range(3))]
assert not outside, f"actors outside room bbox {lo}..{hi}: {outside}"

# ── 10. Export ───────────────────────────────────────────────────────────────
wf_objects = [o for o in scene.objects if o.get('wf_schema_path')]
os.makedirs(OUT_DIR, exist_ok=True)
_wrapper = os.path.join(OUT_DIR, LEVEL_NAME + '-standalone.iff.txt')
if LEVEL_NAME != 'condo_639_640' and not os.path.exists(_wrapper):
    with open(os.path.join(SCRIPT_DIR, 'condo_639_640-standalone.iff.txt')) as _src, open(_wrapper, 'w') as _dst:
        _dst.write(_src.read().replace('condo_639_640', LEVEL_NAME))
bpy.ops.wm.save_as_mainfile(filepath=OUT_BLEND)
print(f"[condo] saved assembled scene → {OUT_BLEND}")
print(f"[condo] exporting {len(wf_objects)} actors → {OUT_LEV}")
bpy.ops.wf.export_level(filepath=OUT_LEV)
print("[condo] done:", stats)
