"""
blender_create_condo.py — convert the 205/639 + 205/640 condo model into a
walkable WorldFoundry level.

Source: ~/docs/aircon/units-639-640.blend (generated by ~/scripts/aircon-blender.py,
rebuild with `cd ~ && task aircon-blender`). Read only — never written.

Usage:
    blender --background --python blender_create_condo.py -- [path/to/units-639-640.blend]
    task build-level -- condo_639_640          # or just: task condo-level
    task run-condo

Pattern: wflevels/moon_site01/blender_create_moon.py — import the snowgoons
scaffold for infrastructure, strip its gameplay, add our geometry as `statplat`
mesh actors (Jolt builds a trimesh body from the render mesh, so walls/floors are
solid and doorways passable straight from the geometry), export.

Plan: docs/plans/2026-09-19-condo-639-640-level.md
"""

import math
import os
import re
import sys

import addon_utils
import bmesh
import bpy
from mathutils import Matrix, Vector

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO       = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
SNOWGOONS  = os.path.join(REPO, 'wflevels', 'snowgoons-blender', 'snowgoons-blender.lev')
OAD_DIR    = os.path.join(REPO, 'wftools', 'wf_oad', 'tests', 'fixtures')
LEVEL_NAME = os.environ.get('CONDO_LEVEL', 'condo_639_640')   # e.g. condo_639_640_tour for the tour build
OUT_DIR    = os.path.join(REPO, 'wflevels', LEVEL_NAME)
OUT_LEV    = os.path.join(OUT_DIR, LEVEL_NAME + '.lev')
OUT_BLEND  = os.path.join(OUT_DIR, LEVEL_NAME + '.blend')      # the assembled WF scene, for inspection in Blender
TOUR_PATH  = os.environ.get('CONDO_TOUR', '')                  # path .json → player walks it (see tour_forth below)

_argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
SRC_BLEND = os.path.abspath(os.path.expanduser(
    _argv[0] if _argv else os.environ.get('CONDO_BLEND', '~/docs/aircon/units-639-640.blend')))
if not os.path.isfile(SRC_BLEND):
    raise SystemExit(f"[condo] source .blend not found: {SRC_BLEND} "
                     f"(rebuild with `cd ~ && task aircon-blender`, or pass the path)")

# Collections to bring over. `640-midea-option-B-over-door` is the rejected
# alternative (hidden) and is never appended.
SRC_COLLECTIONS = ['205-639', '205-640', '640-midea-option-A-closet-wall']

# ── Level constants (metres, WF == Blender axes: X right, Y depth, Z up) ───────
WALL_H        = 2.7
GLASS_T       = 0.10    # source panes are 0.02 m — sub-decimetre slabs have gone
                        # invisible before (troubleshooting § "too thin in
                        # camera-depth axis"); 0.10 fills the wall opening exactly.
# Real-world placement (pin, compass ↔ axes, 6th-floor elevation, texture sizes) is shared
# with make_site_textures.py so the sky/ground textures and the geometry can't disagree.
sys.path.insert(0, SCRIPT_DIR)
from site_constants import UNIT_Z, SLAB_T, GROUND_HALF, SKY_R           # noqa: E402
CORRIDOR      = (-9.0, -17.4, 9.0, -15.4)   # x0, y0, x1, y1: open-air corridor outside both front doors
PARAPET_H     = 1.1                          # railing on its outer edge — a 16 m drop otherwise
PARAPET_T     = 0.15
PLAYER_H      = 1.70
PLAYER_SPAWN  = tuple(float(v) for v in os.environ['CONDO_SPAWN'].split(',')) if os.environ.get('CONDO_SPAWN') \
                else (4.66, -14.5, 0.30)     # just inside 639's front door — the unit is on the 6th floor, so
                                             # the level starts in the condo, not on the street (CONDO_SPAWN=x,y,z overrides)
TOUR = None
if TOUR_PATH:
    import json
    with open(TOUR_PATH) as _f:
        TOUR = json.load(_f)
    PLAYER_SPAWN = tuple(TOUR.get('spawn', PLAYER_SPAWN))
    os.environ.setdefault('CONDO_ACCEL', str(TOUR.get('accel', 105)))
    os.environ.setdefault('CONDO_DECEL', str(TOUR.get('decel', 0.85)))
CAM_OFFSET    = tuple(float(v) for v in os.environ['CONDO_CAM'].split(',')) if os.environ.get('CONDO_CAM') \
                else (0.0, -3.5, 9.0)        # doll-house view: 69° elevation from the east (CONDO_CAM=x,y,z
                                             # overrides, e.g. 0,-1.5,1.2 for a low shot that sees the sky dome)
LOOK_OFFSET   = tuple(float(v) for v in os.environ['CONDO_LOOK'].split(',')) if os.environ.get('CONDO_LOOK') \
                else (0.0, 0.0, 0.9)         # aim at the player's chest, not the feet (CONDO_LOOK=x,y,z overrides)
ROOM_CENTRE   = (0.0, -8.0, 12.0)            # z −4…28: ground quad and dome centres, the lifted units, the camera
ROOM_HALF     = (170.0, 170.0, 16.0)         # levcomp places an actor by its mesh-bbox centre: the merged
                                             # site-buildings mesh (±150 m) must land inside (moon_site01 uses ±505 m)
NUM_MAILBOXES = 100
SUN_ALT_DEG   = 50.0
SUN_AZ_DEG    = 30.0
# Fill light: the engine's idle 2nd directional slot, aimed roughly opposite the
# sun so walls the sun misses still get a directional term (CONDO_FILL_AZ_DEG /
# CONDO_FILL_INTENSITY override). CONDO_AMBIENT sets the flat ambient level.
FILL_AZ_DEG    = float(os.environ.get('CONDO_FILL_AZ_DEG', 195.0))
FILL_ALT_DEG   = 35.0
FILL_INTENSITY = float(os.environ.get('CONDO_FILL_INTENSITY', 0.35))  # 0 = off; see § 8
AMBIENT        = float(os.environ.get('CONDO_AMBIENT', 0.38))


def wf_light_aim(alt_deg: float, az_deg: float):
    """Blender `rotation_euler` that aims a WF Directional Light.

    `Light::Set` (wfsource/source/game/light.hpi) takes the light's direction as
    the actor's **local +X axis** in world space: `dir = Rz(C)·Ry(B)·Rx(A)·(1,0,0)`.
    Rotating +X about X is a no-op, so the long-standing
    `(pi/2 - alt, 0, az)` recipe put the altitude in the one angle that cannot
    move the axis — every light authored that way came out exactly horizontal
    (`dir = (cos az, sin az, 0)`), and the only reason levels looked lit from
    above was a separate engine bug that leaked the actor's *position* into the
    direction vector.  Both are written up in
    docs/plans/2026-09-20-engine-multi-directional-light-fix.md.

    Altitude belongs in **B** (the Y euler):

        Ry(B)·(1,0,0)       = ( cos B, 0, -sin B)
        Rz(C)·Ry(B)·(1,0,0) = ( cos B·cos C, cos B·sin C, -sin B)

    so B = altitude tips the beam downward by that many degrees, and C = azimuth
    keeps its existing meaning (the compass bearing the light *travels toward*).
    """
    return (0.0, math.radians(alt_deg), math.radians(az_deg))

# ── 1. Clean scene, enable add-on, import the snowgoons scaffold ─────────────
bpy.ops.wm.read_factory_settings(use_empty=True)
addon_utils.enable("wf_blender", default_set=False, persistent=False)
if not hasattr(bpy.ops.wf, 'import_level'):
    raise SystemExit("[condo] wf_blender add-on not available — install it "
                     "(task blender-install until the apt package exists)")
scene = bpy.context.scene

print(f"[condo] importing scaffold {SNOWGOONS}")
bpy.ops.wf.import_level(filepath=SNOWGOONS)

KEEP_CLASSES = {'director', 'camera', 'levelobj', 'matte', 'light',
                'room', 'camshot', 'target', 'player'}


def get_class(obj):
    schema = obj.get('wf_schema_path', '')
    return os.path.splitext(os.path.basename(schema))[0] if schema else ''


def find_by_class(cn):
    for obj in bpy.data.objects:
        if get_class(obj) == cn:
            return obj
    return None


def attach_schema(obj, oad_name):
    obj['wf_schema_path'] = os.path.join(OAD_DIR, oad_name + '.oad')


for obj in list(bpy.data.objects):
    if get_class(obj) not in KEEP_CLASSES:
        bpy.data.objects.remove(obj, do_unlink=True)
seen = set()
for obj in list(bpy.data.objects):
    cn = get_class(obj)
    if cn in seen:
        bpy.data.objects.remove(obj, do_unlink=True)
    else:
        seen.add(cn)
print("[condo] scaffold classes:", sorted({get_class(o) for o in bpy.data.objects}))
# Snowgoons meshes carried .tga textures; none of the survivors render (all
# Model Type 'None' below) except the player, whose mesh we replace.

# ── 2. Append the condo collections from the source .blend ───────────────────
before = set(bpy.data.objects)
for cname in SRC_COLLECTIONS:
    bpy.ops.wm.append(filepath=os.path.join(SRC_BLEND, 'Collection', cname),
                      directory=os.path.join(SRC_BLEND, 'Collection') + os.sep,
                      filename=cname, link=False)
appended = [o for o in bpy.data.objects if o not in before]
print(f"[condo] appended {len(appended)} objects from {os.path.basename(SRC_BLEND)}")
bpy.context.view_layer.update()


def sanitize(name):
    """Blender name → asset filename slug: lowercase, runs of non-alnum → '_'.

    The engine's asset string map holds 31 bytes per name (assets.cc
    ReadAssetMap asserts `BytesLeft() < 32`), so `<slug>.iff` must stay ≤ 30
    chars: long names are cut to 21 chars + a 4-hex hash of the full name.
    """
    import zlib
    slug = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')
    if len(slug) > 26:
        slug = f"{slug[:21].rstrip('_')}_{zlib.crc32(name.encode()) & 0xffff:04x}"
    return slug


def make_flat_material(name, rgb):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next((n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED'), None)
    if bsdf:
        bsdf.inputs['Base Color'].default_value = (*rgb, 1.0)
    mat.diffuse_color = (*rgb, 1.0)
    return mat


def bake_transform(obj):
    """Fold rotation+scale (and any parent transform) into the mesh verts, leaving
    only a translation on the object. The Jolt trimesh body is built from raw
    local verts and ignores actor scale/rotation (troubleshooting § "Per-actor
    scale"), and the render path shears a rotated non-uniform scale."""
    mw = obj.matrix_world.copy()
    obj.parent = None
    if obj.data.users > 1:
        obj.data = obj.data.copy()
    rs = mw.to_3x3()
    for v in obj.data.vertices:
        v.co = rs @ v.co
    obj.matrix_world = Matrix.Translation(mw.to_translation())
    obj.data.update()


# The engine computes each face normal at load as (v2−v0)×(v1−v0) and asserts its
# length > Scalar(0,4) ≈ 6.1e-5 in 1.15.16 fixed point (math/vector3.hpi:243,
# "Probably have a polygon which is too small") — i.e. any triangle with area
# < ~3e-5 m² aborts the level. Bevelled-curve corners produce exactly those.
MIN_FACE_AREA = 8e-5
_dropped = {'faces': 0}


def clean_mesh(mesh, recalc=True):
    import bmesh
    bm = bmesh.new()
    bm.from_mesh(mesh)
    bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
    bmesh.ops.triangulate(bm, faces=bm.faces)
    tiny = [f for f in bm.faces if f.calc_area() < MIN_FACE_AREA]
    if tiny:
        _dropped['faces'] += len(tiny)
        bmesh.ops.delete(bm, geom=tiny, context='FACES_ONLY')
        bmesh.ops.delete(bm, geom=[v for v in bm.verts if not v.link_faces], context='VERTS')
    if recalc:
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()


def curve_to_mesh(obj):
    """Bevelled POLY curve → tube mesh object of the same name (materials kept)."""
    dg = bpy.context.evaluated_depsgraph_get()
    ev = obj.evaluated_get(dg)
    me = bpy.data.meshes.new_from_object(ev, preserve_all_data_layers=True, depsgraph=dg)
    if not me.materials:
        for m in obj.data.materials:
            me.materials.append(m)
    me.name = obj.name
    cols = list(obj.users_collection)
    name, mw = obj.name, obj.matrix_world.copy()
    bpy.data.objects.remove(obj, do_unlink=True)
    new = bpy.data.objects.new(name, me)
    new.matrix_world = mw
    for c in cols:
        c.objects.link(new)
    return new


def as_statplat(obj):
    attach_schema(obj, 'statplat')
    obj['wf_Mobility']           = 'Anchored'
    obj['wf_Model Type']         = 'Mesh'
    obj['wf_Visibility Mailbox'] = 1
    # Actor NAME stays the Blender name; the mesh file gets a dot/hyphen-free slug
    # so the asset tools never see `foo.001.iff`.
    obj['wf_original_mesh_name'] = sanitize(obj.name) + '.iff'


def collection_hidden(obj):
    return any(c.hide_viewport or c.hide_render for c in obj.users_collection)


# ── 3. Classify and convert the appended objects ─────────────────────────────
mat_grey = make_flat_material('prop-grey', (0.80, 0.80, 0.82))
room_outlines = []      # (name, world bbox min, world bbox max)
stats = {'mesh': 0, 'curve': 0, 'room': 0, 'skipped': []}

for obj in list(appended):
    if obj.hide_viewport or obj.hide_render or collection_hidden(obj):
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if obj.type == 'CURVE':
        obj = curve_to_mesh(obj)
        bake_transform(obj)
        clean_mesh(obj.data, recalc=False)       # tube normals already point outward
        as_statplat(obj)
        stats['curve'] += 1
        continue
    if obj.type != 'MESH':
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if len(obj.data.polygons) == 0:
        # display-WIRE room outline: remember its world bbox, drop the object
        corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
        mn = Vector((min(c.x for c in corners), min(c.y for c in corners), min(c.z for c in corners)))
        mx = Vector((max(c.x for c in corners), max(c.y for c in corners), max(c.z for c in corners)))
        room_outlines.append((obj.name, mn, mx))
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    is_glass = any(m and m.name == 'glass' for m in obj.data.materials)
    if is_glass and abs(obj.scale.y) < 0.05:
        obj.scale.y = GLASS_T
        bpy.context.view_layer.update()
    bake_transform(obj)
    clean_mesh(obj.data)
    if not obj.data.materials:
        obj.data.materials.append(mat_grey)          # consumer units have no material
    as_statplat(obj)
    stats['mesh'] += 1

print(f"[condo] converted: {stats['mesh']} meshes, {stats['curve']} tubes, "
      f"{len(room_outlines)} room outlines; dropped {_dropped['faces']} sub-threshold faces; "
      f"skipped hidden: {stats['skipped']}")

# ── 3b. Floors: darker shade of the owning unit's colour ───────────────────
# Floor and walls share one material per unit in the source, so from the
# doll-house camera the floor, wall faces and wall tops merge into one mass.
# Give each shell's floor-top faces (normal +Z at z≈0) their own material: the
# face's current colour scaled by FLOOR_SHADE (per face, so 640's 639-blue
# master suite keeps a blue — darker — floor). CONDO_FLOOR_SHADE overrides.
FLOOR_SHADE = float(os.environ.get('CONDO_FLOOR_SHADE', 0.55))


def darken_floors(obj, shade):
    me = obj.data
    if not me.materials or shade >= 0.999:
        return 0
    floor_mats = {}          # source material index → darkened material index
    n = 0
    for pg in me.polygons:
        if pg.normal.z < 0.9 or abs(pg.center.z) > 1e-3:
            continue
        src_i = pg.material_index
        if src_i not in floor_mats:
            src = me.materials[src_i]
            r, g, b, _a = src.diffuse_color
            dark = make_flat_material(f'floor-{src.name}-{shade:.2f}', (r * shade, g * shade, b * shade))
            me.materials.append(dark)
            floor_mats[src_i] = len(me.materials) - 1
        pg.material_index = floor_mats[src_i]
        n += 1
    return n


for shell_name in ('unit-639', 'unit-640'):
    shell = bpy.data.objects.get(shell_name)
    if shell:
        print(f"[condo] {shell_name}: {darken_floors(shell, FLOOR_SHADE)} floor faces at shade {FLOOR_SHADE}")

# ── 3c. Seams: fake the contact AO the engine cannot compute ────────────────
# The renderer is pure per-vertex `ambient + Σ directional·max(0,N·L)` with no
# shadows and no AO (gfx/glpipeline/backend_modern.cc), so two walls meeting at
# 90° and a wall meeting the ceiling are shaded identically — the corner is
# invisible. Same per-face-material-tint trick as darken_floors(), but the face
# selector is "close to a seam" instead of "floor top":
#   (a) a thin z-band of every wall at the floor (z≈0) and ceiling (z≈WALL_H);
#   (b) a thin strip either side of a *concave* wall/wall corner edge.
# Walls are authored as single full-height quads (z 0→2.7), so there is nothing
# to select until the mesh is cut: bisect first, then tint the offcuts.
SEAM_SHADE = float(os.environ.get('CONDO_SEAM_SHADE', 0.75))
SEAM_BAND  = 0.12       # metres of darkened strip either side of a seam
_VERT_N    = 0.30       # |normal.z| below this counts as a wall face
_PERP_N    = 0.35       # |dot(nA,nB)| below this counts as a ~90° corner


def darken_seams(obj, shade, band=SEAM_BAND):
    """Retint a `band`-wide strip of each wall along the floor line, the ceiling
    line and every concave wall/wall corner. Returns (floor, ceiling, corner)
    face counts. Geometry is only subdivided, never moved, so the Jolt trimesh
    surface — and therefore collision — is unchanged."""
    me = obj.data
    if not me.materials or shade >= 0.999:
        return (0, 0, 0)

    bm = bmesh.new()
    bm.from_mesh(me)

    def is_wall(f):
        return abs(f.normal.z) < _VERT_N

    # (a) horizontal cuts at the top of the floor band and the bottom of the
    # ceiling band — one bisect each, across the whole shell.
    for z in (band, WALL_H - band):
        bmesh.ops.bisect_plane(
            bm, geom=list(bm.verts) + list(bm.edges) + list(bm.faces),
            plane_co=(0.0, 0.0, z), plane_no=(0.0, 0.0, 1.0),
            clear_inner=False, clear_outer=False)
    bm.normal_update()

    # (b) concave wall/wall corners: a vertical edge with exactly two wall faces
    # whose normals are ~perpendicular, and whose neighbour sits *in front of*
    # this face's normal (dot(nA, cB - cA) > 0 ⇒ interior corner, not an outside
    # one). Cut each of the two faces parallel to the shared edge, `band` away.
    corner_lines = []
    for e in list(bm.edges):
        if len(e.link_faces) != 2:
            continue
        ev = e.verts[1].co - e.verts[0].co
        if ev.length < 1e-6 or abs(ev.normalized().z) < 0.9:
            continue                                  # not a vertical edge
        fa, fb = e.link_faces
        if not (is_wall(fa) and is_wall(fb)):
            continue
        if abs(fa.normal.dot(fb.normal)) > _PERP_N:
            continue                                  # not a ~90° meeting
        if fa.normal.dot(fb.calc_center_median() - fa.calc_center_median()) <= 0:
            continue                                  # convex (outside) corner
        p = e.verts[0].co.copy()
        corner_lines.append((p.x, p.y))
        for f in (fa, fb):
            # in-plane horizontal direction, pointing from the edge into the face
            d = f.normal.cross(Vector((0.0, 0.0, 1.0)))
            if d.length < 1e-6:
                continue
            d.normalize()
            if d.dot(f.calc_center_median() - p) < 0:
                d = -d
            bmesh.ops.bisect_plane(
                bm, geom=list(f.verts) + list(f.edges) + [f],
                plane_co=p + d * band, plane_no=d,
                clear_inner=False, clear_outer=False)
    bm.normal_update()

    bm.to_mesh(me)
    bm.free()
    me.update()

    # Tint pass on the now-subdivided mesh. One darkened material per source
    # material (same dedup as darken_floors), never one per polygon.
    seam_mats = {}
    counts = {'floor': 0, 'ceil': 0, 'corner': 0}
    for pg in me.polygons:
        if abs(pg.normal.z) >= _VERT_N:
            continue
        c = pg.center
        if c.z <= 1e-4 or c.z >= WALL_H - 1e-4:
            continue                                  # skirt / cap, not a wall
        if c.z < band:
            kind = 'floor'
        elif c.z > WALL_H - band:
            kind = 'ceil'
        elif any(abs(c.x - lx) < band and abs(c.y - ly) < band for lx, ly in corner_lines):
            kind = 'corner'
        else:
            continue
        src_i = pg.material_index
        if src_i not in seam_mats:
            src = me.materials[src_i]
            r, g, b, _a = src.diffuse_color
            dark = make_flat_material(f'seam-{src.name}-{shade:.2f}',
                                      (r * shade, g * shade, b * shade))
            me.materials.append(dark)
            seam_mats[src_i] = len(me.materials) - 1
        pg.material_index = seam_mats[src_i]
        counts[kind] += 1
    return (counts['floor'], counts['ceil'], counts['corner'])


for shell_name in ('unit-639', 'unit-640'):
    shell = bpy.data.objects.get(shell_name)
    if shell:
        nf, nc, nk = darken_seams(shell, SEAM_SHADE)
        print(f"[condo] {shell_name}: {nf} floor-seam, {nc} ceiling-seam, {nk} corner-seam "
              f"faces at shade {SEAM_SHADE} (band {SEAM_BAND} m)")

# ── 4. Room outlines → named `target` locators (bbox = room, no Jolt body) ───
target_proto = find_by_class('target')
assert target_proto is not None, "snowgoons scaffold has no target"
target_proto.name = 'CamTarget'
for name, mn, mx in room_outlines:
    t = target_proto.copy()
    t.data = None
    t.name = name
    centre = (mn + mx) / 2.0
    t.location = centre
    t.rotation_euler = (0.0, 0.0, 0.0)
    t.scale = (1.0, 1.0, 1.0)
    half = (mx - mn) / 2.0
    t['wf_original_bbox'] = (-half.x, -half.y, -half.z, half.x, half.y, half.z)
    t['wf_had_authored_bbox'] = True
    t['wf_original_mesh_name'] = ''
    t['wf_Model Type'] = 'None'
    scene.collection.objects.link(t)
stats['room'] = len(room_outlines)

# ── 5. Site: corridor outside the doors, the ground map far below, the sky dome ──
# The units are on the 6th floor (UNIT_Z = 15.75 m), so "outside the front door" is the
# building's open-air corridor, not the ground: a slab strip with a parapet. The ground is a
# textured quad at world z = 0 (condo_ground.tga, OSM flat map, ±GROUND_HALF m) and the sky
# an inverted sphere with an equirectangular panorama (condo_sky.tga) — both generated by
# make_site_textures.py from site-osm.json, both routed to the PERM atlas like the moon's
# skydome (Moves Between Rooms). Everything else is authored at z = 0 and lifted in § 9b.
import bmesh as _bmesh


def box_mesh(name, x0, y0, z0, x1, y1, z1):
    """Closed box, outward in Blender's hand — the exporter adapts to the engine's
    (level-building.md § winding)."""
    bm = _bmesh.new()
    _bmesh.ops.create_cube(bm, size=1.0)
    for v in bm.verts:
        v.co = ((x0 + x1) / 2 + v.co.x * (x1 - x0), (y0 + y1) / 2 + v.co.y * (y1 - y0), (z0 + z1) / 2 + v.co.z * (z1 - z0))
    _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    return me


def add_flat_actor(name, mesh, rgb):
    mesh.materials.append(make_flat_material(name, rgb))
    obj = bpy.data.objects.new(name, mesh)
    scene.collection.objects.link(obj)
    clean_mesh(mesh, recalc=False)
    as_statplat(obj)
    return obj


def make_textured_material(name, tga):
    """White BSDF base + image texture: the WF fragment shader samples the texture only
    when the vertex colour is white (`step(0.99, min(rgb))`, backend_modern.cc kFS)."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
    tex = mat.node_tree.nodes.new('ShaderNodeTexImage')
    tex.image = bpy.data.images.load(os.path.join(SCRIPT_DIR, tga))
    mat.node_tree.links.new(tex.outputs['Color'], bsdf.inputs['Base Color'])
    bsdf.inputs['Base Color'].default_value = (1.0, 1.0, 1.0, 1.0)
    mat.diffuse_color = (1.0, 1.0, 1.0, 1.0)
    return mat


for tga in ('condo_ground.tga', 'condo_sky.tga'):
    if not os.path.isfile(os.path.join(SCRIPT_DIR, tga)):
        raise SystemExit(f"[condo] missing {tga} — run `task condo-textures` (make_site_textures.py render)")

cx0, cy0, cx1, cy1 = CORRIDOR
corridor = add_flat_actor('corridor', box_mesh('corridor', cx0, cy0, -SLAB_T, cx1, cy1, 0.0), (0.62, 0.62, 0.60))
parapet = add_flat_actor('corridor-parapet',
                         box_mesh('corridor-parapet', cx0, cy0 - PARAPET_T, 0.0, cx1, cy0, PARAPET_H), (0.70, 0.70, 0.68))

# WF texture V runs top-down: gfx/material.cc CalcVRAMuv maps v = 0 to the texture's first
# (top) row and the exporter passes Blender's uv.y through unflipped — the opposite of
# Blender/GL, where v = 0 is the bottom row. So "image top" is v = 0 here.
# Ground map: one quad, UV so image top (north = +X) is v = 0 and image right (east = −Y) is u = 1.
_gm = bpy.data.meshes.new('site-map')
_g = GROUND_HALF
# Winding pinned to +Z in Blender's hand (counter-clockwise seen from above); a recalc on a
# lone open quad is a coin toss. The exporter adapts the hand to the engine's.
_gm.from_pydata([(-_g, -_g, 0.0), (_g, -_g, 0.0), (_g, _g, 0.0), (-_g, _g, 0.0)], [], [(0, 1, 2, 3)])
_uv = _gm.uv_layers.new(name='UVMap')
for li, loop in enumerate(_gm.loops):
    x, y, _z = _gm.vertices[loop.vertex_index].co
    _uv.data[li].uv = (0.5 - y / (2 * _g), 0.5 - x / (2 * _g))
_gm.update()
_gm.materials.append(make_textured_material('site-map', 'condo_ground.tga'))
site_map = bpy.data.objects.new('site-map', _gm)
scene.collection.objects.link(site_map)
clean_mesh(_gm, recalc=False)                     # triangulate only — keep the pinned winding
as_statplat(site_map)
site_map['wf_Moves Between Rooms'] = 'True'


def build_skydome(radius, segs=48, rings=24):
    """Lat/long sphere with explicit UVs: column j at compass θ = 360·j/segs, level position
    (R cosθ cosφ, −R sinθ cosφ, R sinφ) since +X is north and +Y west; u = θ/360, v = (90−φ)/180
    (WF v = 0 is the top row = zenith, see the site-map note above). Faces are wound inward in
    Blender's hand (the player is inside); the exporter adapts the hand.
    One extra seam column (segs+1 vertex columns) so no face straddles u = 1 → 0. Faces are
    wound inward (the player is inside)."""
    verts, uvs = [], []
    for i in range(rings + 1):
        phi = math.radians(-90.0 + 180.0 * i / rings)
        for j in range(segs + 1):
            th = math.radians(360.0 * j / segs)
            verts.append((radius * math.cos(th) * math.cos(phi), -radius * math.sin(th) * math.cos(phi), radius * math.sin(phi)))
            uvs.append((j / segs, 1.0 - i / rings))
    faces = []
    cols = segs + 1
    for i in range(rings):
        for j in range(segs):
            a, b, c, d = i * cols + j, i * cols + j + 1, (i + 1) * cols + j + 1, (i + 1) * cols + j
            if i == 0:
                faces.append((a, d, c))          # pole triangles (a == b position-wise)
            elif i == rings - 1:
                faces.append((a, d, b))
            else:
                faces.append((a, d, c, b))
    me = bpy.data.meshes.new('skydome')
    me.from_pydata(verts, [], faces)
    uv = me.uv_layers.new(name='UVMap')
    for li, loop in enumerate(me.loops):
        uv.data[li].uv = uvs[loop.vertex_index]
    me.update()
    bm = _bmesh.new()
    bm.from_mesh(me)
    _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)   # outward first …
    _bmesh.ops.reverse_faces(bm, faces=bm.faces)          # … then inward: the player stands inside
    bm.to_mesh(me)
    bm.free()
    me.update()
    return me


_sky = build_skydome(SKY_R)
_sky.materials.append(make_textured_material('skydome', 'condo_sky.tga'))
skydome = bpy.data.objects.new('skydome', _sky)
scene.collection.objects.link(skydome)
skydome.location = (0.0, -8.0, UNIT_Z)          # world-space: the viewpoint the panorama was painted from
clean_mesh(_sky, recalc=False)
as_statplat(skydome)
skydome['wf_Moves Between Rooms'] = 'True'
# Mass 0 ⇒ Actor::CanCollide() is false (actor.cc:1079: collisionTable[kind] && Mass > 0).
# Camera obstacle avoidance is a *bbox* overlap pass, and the dome's bbox is the whole
# level — with a mass the camera "hit" it every tick and climbed (BungeeCameraHandler
# ClimbRate) until every shot was 12 m higher than authored.
skydome['wf_Mass'] = 0.0
# ── 5b. The neighbourhood: near buildings as prisms, a podium under the units ──
# make_site_textures.py writes site-buildings.json — every OSM footprint within GEOM_R
# (150 m) in level metres with a height by building type — and leaves those out of the
# sky panorama. One merged mesh actor, Mass 0 (the physics camera's bbox pass ignores it),
# world-space. Plan: docs/plans/2026-09-19-condo-site-surroundings.md
import json as _json

with open(os.path.join(SCRIPT_DIR, 'site-buildings.json')) as _f:
    _near = _json.load(_f)['buildings']


def prism(bm, loop, z0, z1, mat_wall, mat_roof):
    """Closed prism over an (x, y) loop; returns the face count or 0 when the loop is degenerate."""
    pts = [(x, y) for x, y in loop]
    if len(pts) > 1 and pts[0] == pts[-1]:
        pts = pts[:-1]
    if len(pts) < 3:
        return 0
    try:
        bot = [bm.verts.new((x, y, z0)) for x, y in pts]
        top = [bm.verts.new((x, y, z1)) for x, y in pts]
        # No bottom face: it would be coplanar with the ground quad and share the base edge
        # with it, and the depth test then flickers along every building's foot ("z-fighting
        # where the buildings meet the ground"). An open-bottomed prism is never seen from
        # below. The normal recalc needs a closed shell, so cap it, recalc, then delete the cap.
        fb = bm.faces.new(bot); ft = bm.faces.new(top)
        fb.material_index = mat_wall; ft.material_index = mat_roof
        n = len(pts)
        faces = [fb, ft]
        for i in range(n):
            f = bm.faces.new((bot[i], bot[(i + 1) % n], top[(i + 1) % n], top[i]))
            f.material_index = mat_wall
            faces.append(f)
        # Outward, per prism, while it is still a closed manifold of its own (a global recalc
        # after welding shared shophouse vertices turned rows into one non-manifold blob and
        # flipped walls at random). Blender's hand; the exporter adapts to the engine's.
        _bmesh.ops.recalc_face_normals(bm, faces=faces)
        _bmesh.ops.delete(bm, geom=[fb], context='FACES_ONLY')
        return n + 1
    except ValueError:            # self-touching outline → duplicate face; leave what was built
        return 0


_bm = _bmesh.new()
_nb, _skipped = 0, 0
for b in _near:
    if prism(_bm, b['pts'], 0.0, float(b['h']), 0, 1):
        _nb += 1
    else:
        _skipped += 1
_nm = bpy.data.meshes.new('site-buildings')
_bm.to_mesh(_nm); _bm.free()
_nm.materials.append(make_flat_material('site-walls', (0.78, 0.74, 0.68)))
_nm.materials.append(make_flat_material('site-roofs', (0.62, 0.60, 0.57)))
site_buildings = bpy.data.objects.new('site-buildings', _nm)
scene.collection.objects.link(site_buildings)
clean_mesh(_nm, recalc=False)                             # triangulate (concave footprints OK), drop slivers
as_statplat(site_buildings)
site_buildings['wf_Mass'] = 0.0
print(f"[condo] site-buildings: {_nb} prisms, {len(_nm.polygons)} tris (skipped {_skipped})")

# The podium: floors 1–5 under the units + corridor, so the doll-house is the top of a building.
cx0, cy0, cx1, cy1 = CORRIDOR
# Inset 5 cm from every surface it would otherwise share a plane with: the ground quad
# below (z 0.05), the parapet's east face and the units' side walls (x/y), the slab bottoms
# above (top 2 cm under them) — coincident faces flicker.
_ins = 0.05
site_podium = add_flat_actor('site-podium',
                             box_mesh('site-podium', min(cx0, -7.95) + _ins, cy0 - PARAPET_T + _ins, _ins,
                                      max(cx1, 8.05) - _ins, 0.05 - _ins, UNIT_Z - SLAB_T - 0.02),
                             (0.72, 0.72, 0.70))
site_podium['wf_Mass'] = 0.0

NOT_LIFTED = {site_map.name, skydome.name, site_buildings.name, site_podium.name, 'room_condo', 'Matte'}   # world-space
print(f"[condo] site: corridor {cx1 - cx0:.0f}×{cy1 - cy0:.0f} m + parapet, site-map ±{_g:.0f} m, "
      f"skydome R={SKY_R:.0f} m {len(_sky.vertices)} verts {len(_sky.polygons)} tris; units → z={UNIT_Z}")

# ── 6. Player: 1.7 m figure, feet at local z=0, +X front marker ──────────────
def build_figure():
    mat_body = make_flat_material('figure-body', (0.20, 0.32, 0.55))
    mat_head = make_flat_material('figure-head', (0.90, 0.75, 0.60))
    mat_mark = make_flat_material('figure-front', (0.95, 0.25, 0.20))
    parts = []
    bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.20, depth=1.20, location=(0, 0, 0.60))
    parts.append((bpy.context.object, mat_body))
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.16, segments=10, ring_count=6, location=(0, 0, 1.50))
    parts.append((bpy.context.object, mat_head))
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0.20, 0, 1.10))
    mark = bpy.context.object
    mark.scale = (0.08, 0.16, 0.20)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    parts.append((mark, mat_mark))
    for o, m in parts:
        o.data.materials.clear()
        o.data.materials.append(m)
        for p in o.data.polygons:
            p.material_index = 0
    bpy.ops.object.select_all(action='DESELECT')
    for o, _ in parts:
        o.select_set(True)
    body = parts[0][0]
    bpy.context.view_layer.objects.active = body
    bpy.ops.object.join()
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
    min_z = min(v.co.z for v in body.data.vertices)
    for v in body.data.vertices:
        v.co.z -= min_z
    body.data.name = 'figure'
    return body


player = find_by_class('player')
assert player is not None, "snowgoons scaffold has no player"
_fig = build_figure()
player.name = 'Player'
player.data = _fig.data
bpy.data.objects.remove(_fig, do_unlink=True)
# The imported scaffold player carries snowgoons' authored bbox (`wf_original_bbox`,
# ±0.33 × ±0.36 × 0…2.0 m) and the exporter prefers it over the mesh — with it the
# Jolt capsule is 2.0 m tall and can't pass a 2.0 m door header. Drop it so the
# BOX3 (→ capsule radius 0.2, height 1.66) comes from the figure we just built.
for key in ('wf_original_bbox', 'wf_had_authored_bbox'):
    if key in player:
        del player[key]
player.location = PLAYER_SPAWN
player.scale = (1.0, 1.0, 1.0)
player.rotation_euler = (0.0, 0.0, math.pi / 2)      # face +Y: into the units, doom-stick strafe = screen X
player['wf_Mobility']              = 'Physics'
player['wf_Mass']                  = 70.0
player['wf_Model Type']            = 'Mesh'
player['wf_Visibility Mailbox']    = 1
# Calibrated on the bridge (motion profile of a straight walk): ground speed is
# the terminal velocity of `Running Acceleration` against `Running Deceleration`
# 0.85 — accel 8 → 0.31 m/s, 40 → 1.55 m/s, 80 → 3.0 m/s (≈ accel/26) — and
# `Max Ground Speed` never binds at these values. 40 = indoor walking pace.
# CONDO_ACCEL / CONDO_SPEED override for tour recordings (4 m/s ≈ accel 105).
player['wf_Running Acceleration']  = float(os.environ.get('CONDO_ACCEL', 40.0))
player['wf_Running Deceleration']  = float(os.environ.get('CONDO_DECEL', 0.85))   # 0.85 = long glide; tour uses more
player['wf_Max Ground Speed']      = float(os.environ.get('CONDO_SPEED', 4.0))
player['wf_Jumping Acceleration']  = 5.0          # a small hop, not a platformer jump
player['wf_Falling Acceleration']  = 9.81
player['wf_Air Acceleration']      = 0.0
player['wf_Max Air Speed']         = 4.0
player['wf_Horiz Air Drag']        = 1.5
player['wf_Turn Rate']             = 0.0          # LEFT/RIGHT strafe (doom-stick), no rotation
player['wf_Script Controls Input'] = 'True'

JOY_UP, JOY_DOWN, JOY_RIGHT, JOY_LEFT = 1 << 11, 1 << 12, 1 << 13, 1 << 14   # hal/sjoystic.h EJ_BUTTONB_*
MB_LEG, MB_HOLD_UNTIL, MB_DONE = 500, 501, 502   # global user mailboxes (2–999, shared)


def tour_forth(tour):
    """Compile the waypoint list into a per-tick zForth state machine.

    Global mailbox 500 holds the current leg. A move leg is a *servo*: it pushes
    the player toward the waypoint coordinate from either side (joystick bits by
    sign of the error) and advances only when the error is within `tol_m` AND the
    player's speed along that axis (X/YSPEED mailboxes) is below `stop_speed` —
    so momentum can never carry him past a doorway into a jamb (which "complete
    once past the target" did, run-dependently). A labelled waypoint adds a hold
    leg (bits 0) timed on INDEXOF_TIME via mailbox 501. The last leg sets mailbox
    502 = 1 so a recorder knows the tour is over. Position-based → replays the
    same at any frame rate.
    """
    hold = float(tour.get('hold_seconds', 0.5))
    tol = float(tour.get('tol_m', 0.12))
    stop_speed = float(tour.get('stop_speed', 0.4))
    legs = []                                   # (bits, axis, target, label)  bits = "+" direction bits
    px, py = tour['spawn'][0], tour['spawn'][1]
    for wp in tour['waypoints']:
        x, y = wp['at']
        dx, dy = x - px, y - py
        assert (abs(dx) < 1e-6) != (abs(dy) < 1e-6), f"leg to {wp['at']} must be axis-aligned (from {px, py})"
        legs.append(('X', x, None) if abs(dx) > 1e-6 else ('Y', y, None))
        if wp.get('room'):
            legs.append(('HOLD', float(wp.get('hold', hold)), wp['room']))   # per-waypoint `hold` overrides hold_seconds
        px, py = x, y
    lines = ["\\ wf", f"{MB_LEG} read-mailbox"]          # ( leg )
    for k, (kind, val, label) in enumerate(legs):
        nxt = k + 1
        if kind in ('X', 'Y'):
            pos_mb, spd_mb = (f'INDEXOF_{kind}_POS', f'INDEXOF_{kind}SPEED')
            plus, minus = (JOY_RIGHT, JOY_LEFT) if kind == 'X' else (JOY_UP, JOY_DOWN)
            # ( leg ) → err = pos − target; err > tol → push minus; err < −tol → push plus;
            # else stop, and advance once |speed| < stop_speed.
            lines.append(
                f"dup {k} = if {pos_mb} read-mailbox {val} - "
                f"dup {tol} > if drop {minus} INDEXOF_INPUT write-mailbox else "
                f"dup {-tol} < if drop {plus} INDEXOF_INPUT write-mailbox else "
                f"drop 0 INDEXOF_INPUT write-mailbox "
                f"{spd_mb} read-mailbox abs {stop_speed} < if drop {nxt} dup {MB_LEG} write-mailbox then "
                f"then then then")
        else:   # hold `val` seconds at the labelled room
            lines.append(
                f"dup {k} = if 0 INDEXOF_INPUT write-mailbox "
                f"{MB_HOLD_UNTIL} read-mailbox 0 = if INDEXOF_TIME read-mailbox {val} + {MB_HOLD_UNTIL} write-mailbox then "
                f"INDEXOF_TIME read-mailbox {MB_HOLD_UNTIL} read-mailbox >= if "
                f"0 {MB_HOLD_UNTIL} write-mailbox drop {nxt} dup {MB_LEG} write-mailbox then then")
    lines.append(f"dup {len(legs)} = if 0 INDEXOF_INPUT write-mailbox 1 {MB_DONE} write-mailbox then")
    lines.append("drop")
    return "\n".join(lines) + "\n", legs


if TOUR:
    _script, _legs = tour_forth(TOUR)
    player['wf_Script'] = _script
    player['wf_Falling Acceleration'] = 9.81
    print(f"[condo] tour: {len(_legs)} legs, {sum(1 for l in _legs if l[2])} room holds, "
          f"{len(_script)} bytes of Forth")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, LEVEL_NAME + '.legs.json'), 'w') as _f:
        json.dump([{'leg': i, 'kind': kind, 'target': val, 'room': lab} for i, (kind, val, lab) in enumerate(_legs)], _f, indent=1)
else:
    player['wf_Script'] = (
        "\\ wf\n"
        "INDEXOF_HARDWARE_JOYSTICK1_RAW read-mailbox INDEXOF_INPUT write-mailbox\n"
    )

# ── 7. Camera rig: relative doll-house shot ──────────────────────────────────
# BungeeCam: position = (camshot − Follow) + TrackObject; look-at = (Target − Follow)
# + TrackObject (movecam.cc SetCameraParametersFromShot / BungeeCameraHandler::update).
# With Follow = CamTarget at the origin the camshot's own position IS the offset.
target_proto.location = (0.0, 0.0, 0.0)
target_proto['wf_Model Type'] = 'None'
look_at = target_proto.copy()
look_at.data = None
look_at.name = 'LookAt'
look_at.location = LOOK_OFFSET
look_at['wf_Model Type'] = 'None'
scene.collection.objects.link(look_at)

camshot = find_by_class('camshot')
assert camshot is not None
camshot.name = 'cs_dollhouse'
camshot.location = CAM_OFFSET
camshot['wf_Position X'] = 'Relative'
camshot['wf_Position Y'] = 'Relative'
camshot['wf_Position Z'] = 'Relative'
camshot['wf_Rotation']   = 'Fixed'          # 'Track' would spin the offset by the player's heading
camshot['wf_FOV']        = 60.0
camshot['wf_Hither']     = 0.1
camshot['wf_Yon']        = 200.0
camshot['wf_Pan Time In Seconds'] = 0.5
camshot['wf_Model Type']   = 'None'
camshot['wf_Track Object'] = 'Player'
camshot['wf_Target']       = 'LookAt'
camshot['wf_Follow']       = 'CamTarget'

camera = find_by_class('camera')
assert camera is not None
camera.name = 'Camera'
camera.location = tuple(s + o for s, o in zip(PLAYER_SPAWN, CAM_OFFSET))   # start where the shot lands
camera['wf_Model Type'] = 'None'
camera['wf_FoggingColor']            = 0x000000    # indoor: no snowgoons Earth fog
camera['wf_FoggingStartDistance']    = 999.0
camera['wf_FoggingCompleteDistance'] = 1000.0

# ── 7b. Balcony camera: step onto 639's patio and the shot cuts to Bangkok ──────
# Two ActBoxOR zones write their camshot's object index to a mailbox every tick the
# player overlaps them (game/actboxor.cc — it never clears); the Director forwards the
# mailbox to INDEXOF_CAMSHOT and zeroes it. In bungee-cam mode the handler re-reads
# INDEXOF_CAMSHOT each tick and never clears it (movecam.cc BungeeCameraHandler), so
# the last written shot sticks: interior zone → cs_dollhouse, patio zone → cs_balcony.
# The zones are adjacent, not overlapping; the Director reads the patio's mailbox last
# so it wins on a boundary tick.
#
# cs_balcony is the player's POV: Relative offset (0, 1.5, 1.7) — 1.5 m ahead of the player
# at eye height, which on the patio puts the camera just past the pony wall in free air.
# That matters because the camera is a physics body that climbs whenever its bbox overlaps a
# collidable actor (BungeeCameraHandler ClimbRate): inside the patio it would hit the player
# or the walls and sail upward. movecam.cc SetCameraParametersFromShot: position =
# (camshot − Follow) + Player, direction = Target − camshot, both in world space.
MB_ZONE_INTERIOR, MB_ZONE_BALCONY, MB_BALCONY_T0 = 98, 99, 97   # 97: level time the player stepped onto the patio (0 = not there)
BALCONY_ROOMS = ('639-patio', '639-patio-recessed')
_bal = [(mn, mx) for name, mn, mx in room_outlines if name in BALCONY_ROOMS]
assert len(_bal) == len(BALCONY_ROOMS), f"balcony outlines missing: {[n for n, _, _ in room_outlines]}"
bal_min = Vector((min(mn.x for mn, _ in _bal), min(mn.y for mn, _ in _bal), 0.0))
bal_max = Vector((max(mx.x for _, mx in _bal), max(mx.y for _, mx in _bal), WALL_H))
BALCONY_CAM     = (0.0, 1.5, 1.7)       # POV: offset from the player — eye height, past the pony wall
BALCONY_LOOK0   = (-6.0, 9.5, -0.3)     # sweep start (world, relative to CamTarget): south-west, 14° down — the street
BALCONY_LOOK1   = (6.0, 9.5, 2.7)       # sweep end: north-west, 7° up — the towers and the sky
BALCONY_SWEEP_S = 5.0                   # the pan takes this long, then holds (tour patio holds add the same 5 s)


def add_locator(name, location, bbox_min=None, bbox_max=None):
    """target-class locator (no mesh, no Jolt body); an authored bbox makes it a zone."""
    o = target_proto.copy()
    o.data = None
    o.name = name
    o.location = location
    o.rotation_euler = (0.0, 0.0, 0.0)
    o.scale = (1.0, 1.0, 1.0)
    o['wf_Model Type'] = 'None'
    o['wf_original_mesh_name'] = ''
    if bbox_min is not None:
        half = (bbox_max - bbox_min) / 2.0
        o['wf_original_bbox'] = (-half.x, -half.y, -half.z, half.x, half.y, half.z)
        o['wf_had_authored_bbox'] = True
    scene.collection.objects.link(o)
    return o


def add_zone(name, mn, mx, mailbox, shot_name):
    z = add_locator(name, (mn + mx) / 2.0, mn, mx)
    attach_schema(z, 'actboxor')
    z['wf_MovementClass']      = 17               # Actor::ActBoxOR_KIND (actboxor.cc:67 asserts it; the
                                                  # target prototype carries 3 and the exporter copies it)
    z['wf_Mobility']           = 'Anchored'
    z['wf_MailBox']            = mailbox
    z['wf_Object']             = shot_name
    z['wf_Activated By']       = 'Actor'
    z['wf_Activated By Actor'] = 'Player'
    z['wf_Activated By Class'] = ''
    return z


def add_pov_camera(tag, cam_offset, look0, look1, zone_min, zone_max, zone_mb, t0_mb, sweep_s=BALCONY_SWEEP_S):
    """A first-person camshot `cs_<tag>` switched on by the ActBoxOR `zone-<tag>` (mailbox
    `zone_mb`), looking at `<Tag>Look` — a scripted platform (the moon's launch_tracker
    pattern) that slides from look0 to look1 over `sweep_s` seconds timed from mailbox
    `t0_mb` (the Director writes the level time on entry, zeroes it on exit), so every
    visit pans the skybox the same way. Offsets are Relative to the player / relative to
    CamTarget at the origin (movecam.cc: position = (camshot − Follow) + Player,
    direction = Target − camshot); the look target animates whichever of X/Y differs
    between look0 and look1, plus Z, through its own INDEXOF_*_POS mailboxes."""
    name = tag.capitalize() + 'Look'
    look = bpy.data.objects.new(name, bpy.data.meshes.new(name))
    scene.collection.objects.link(look)
    attach_schema(look, 'platform')
    look.location = look0
    look['wf_Mobility']   = 'Anchored'
    look['wf_Model Type'] = 'None'
    look['wf_Mass']       = 0.0
    axis = 'X' if abs(look1[0] - look0[0]) > abs(look1[1] - look0[1]) else 'Y'
    a0, a1 = (look0[0], look1[0]) if axis == 'X' else (look0[1], look1[1])
    z0, z1 = look0[2] + UNIT_Z, look1[2] + UNIT_Z
    look['wf_Script'] = (
        "\\ wf\n"
        f"{t0_mb} read-mailbox dup 0 <> if INDEXOF_TIME read-mailbox swap - "      # ( elapsed )
        f"dup {sweep_s} > if drop {sweep_s} then {sweep_s} / "                     # ( t 0..1 )
        f"dup {a1 - a0} * {a0} + INDEXOF_{axis}_POS write-mailbox "
        f"{z1 - z0} * {z0} + INDEXOF_Z_POS write-mailbox "
        f"else drop {a0} INDEXOF_{axis}_POS write-mailbox {z0} INDEXOF_Z_POS write-mailbox then\n"
    )
    cs = camshot.copy()
    cs.data = None
    cs.name = 'cs_' + tag
    cs.location = cam_offset
    for k in ('wf_Position X', 'wf_Position Y', 'wf_Position Z'):
        cs[k] = 'Relative'
    cs['wf_Rotation'] = 'Fixed'
    cs['wf_Target']   = name
    cs['wf_Follow']   = 'CamTarget'
    cs['wf_Track Object'] = 'Player'
    cs['wf_Pan Time In Seconds'] = 0.7
    scene.collection.objects.link(cs)
    zone = add_zone('zone-' + tag, Vector(zone_min), Vector(zone_max), zone_mb, cs.name)
    print(f"[condo] {tag} POV camera: zone x {zone_min[0]:.2f}…{zone_max[0]:.2f} y {zone_min[1]:.2f}…{zone_max[1]:.2f}, "
          f"cs_{tag} at {cam_offset}, look {look0} → {look1} over {sweep_s} s")
    return cs, look, zone


pad = 0.1
cs_balcony, balcony_look, zone_balcony = add_pov_camera(
    'balcony', BALCONY_CAM, BALCONY_LOOK0, BALCONY_LOOK1,
    bal_min - Vector((pad, pad, 0.5)), bal_max + Vector((pad, pad, 0.5)), MB_ZONE_BALCONY, MB_BALCONY_T0)

# Master-bedroom window (plan: docs/plans/2026-09-19-condo-master-window-pov.md). 640's
# master bedroom has its curved glass along the unit's −X (compass south) wall; the zone is
# the strip within MASTER_STRIP_W of it. The camera sits 1.8 m further in −X — past the glass
# and past unit-640's actor bbox (min x −7.95), so the physics camera has nothing to hit.
MB_ZONE_MASTER, MB_MASTER_T0 = 95, 96
MASTER_ROOM   = '640-master-bed'
MASTER_STRIP_W = 1.6
MASTER_CAM    = (-1.8, 0.0, 1.7)
MASTER_LOOK0  = (-9.5, -6.0, -0.3)      # south-east, 2° down — Soi 34 and Sathu Pradit Road
MASTER_LOOK1  = (-9.5, 6.0, 2.7)        # south-west, 14° up — the river loop and the sky
_mb = next(((mn, mx) for name, mn, mx in room_outlines if name == MASTER_ROOM), None)
assert _mb is not None, f"{MASTER_ROOM} outline missing"
cs_master, master_look, zone_master = add_pov_camera(
    'master', MASTER_CAM, MASTER_LOOK0, MASTER_LOOK1,
    (_mb[0].x - pad, _mb[0].y - pad, -0.5), (_mb[0].x + MASTER_STRIP_W, _mb[1].y + pad, WALL_H + 0.5),
    MB_ZONE_MASTER, MB_MASTER_T0)

cx0, cy0, cx1, cy1 = CORRIDOR
zone_interior = add_zone('zone-interior', Vector((min(cx0, -8.2), cy0 - 0.5, -0.5)),
                         Vector((max(cx1, 8.2), bal_min.y - pad, WALL_H + 0.5)),
                         MB_ZONE_INTERIOR, 'cs_dollhouse')

# ── 7c. 639-project-rm patio wall: telescoping glass doors, not a wall ───────
# Plan: docs/plans/2026-09-20-condo-project-room-telescoping-doors.md
#
# THE WALL, corrected 2026-09-20. The first pass targeted the room's x ≈ 7.8 face
# (the compass-north one, where `639-window-1` sits) and was wrong: that is a
# genuine exterior wall with nothing beyond it, carried by `unit-639`'s shell mesh
# (49 collidable faces), and `639-window-1` is a real window on it. Left alone.
#
# The door wall is the room's **y = −2.0 face**, the one it shares with the two
# already-modelled patio rooms that together span its whole width:
#   639-patio-recessed  x 2.70…5.40, y −2.0…0.0
#   639-patio           x 5.40…7.80, y −2.0…0.0
# Both are real floored, enclosed, ceilinged rooms in `unit-639`'s shell (floor
# faces at z = 0, perimeter walls to z = 2.7), so opening this wall exposes nothing
# and **no new balcony geometry is needed**.
#
# On that face `unit-639`'s shell carries only 3 stray faces in the x 3.5…8.0 band
# (all at the far x ≈ 7.95 corner) — the wall is a single separate object,
# `639-front-strip-S-wall-jamb2` (6 polys, x 3.65…7.80, y −2.05…−1.95, z 0…2.70).
# It is the S-wall run's last solid segment; its two door openings (the
# `…-door-header` pairs at x 0.30…1.10 and 2.85…3.65) both front the guest side.
# So the correction is object-level, not shell surgery: shrink jamb2 back to the
# x 3.65…3.80 slice that fronts the guest bedroom, and put the doors across the
# project room's own x 3.80…7.80 frontage.
#
# MECHANISM (2026-09-20, 2nd iteration — real sliding motion, real collision).
# Three individual statplat panel actors, all solid at the ordinary wall Mass
# (the `statplat` schema default of 75, movebloc.inc:15 — `as_statplat()` leaves
# `Mass` unset exactly as every other wall in this file does). One is fixed in
# the gather bay; the other two physically slide along X between the gather bay
# and their closed bays, driven by a per-tick lerp in the Director's Forth that
# writes their `INDEXOF_X_POS` mailbox — the `fsn_flydown()` t/SECS pattern
# (engine/stubs/scripting_zforth.cc:189-201), triggered off the same
# `zone-project-doors` ActBoxOR proximity mailboxes as before.
#
# COLLISION IS NOW REAL, and that is the point of this iteration. Superseded:
# the `Visibility Mailbox` two-state swap with `Mass 0` on both states, which
# could only ever be a visual cue (`Actor::CanCollide()` never consults
# visibility, actor.cc:1081). Because these panels carry real Mass and are
# StatPlats, each gets a trimesh Jolt body (actor.cc:747-762 + BindAssets,
# actor.cc:543-590), and `PhysicalAttributes::Update()`
# (physics/jolt/physical.hpi:22-28) pushes `_position` into that body
# unconditionally every physics frame for every actor on the update list
# (`Actor::CanUpdate()` returns true for all, actor.cc:1070). So a scripted
# position write moves the collision with the mesh, in real time — no engine
# change, no collision-toggle mailbox. When the doors are closed the panels are
# solid objects standing in the doorway; when open they are simply somewhere
# else.
#
# DEVIATION FROM THE PLAN, forced by the engine and recorded in the plan's
# Verification: the plan says the two movable panels each carry their own
# per-tick script. A StatPlat cannot — `actor.cc:752-754` hard-asserts
# "No scripts allowed on StatPlat's" and "No local mailboxes allowed on
# StatPlat's" — and the actor kinds that *can* script (anchored Platform /
# Target / …) get no Jolt body at all (only StatPlats, MOBILITY_PHYSICS
# characters and anchored mesh Generators do), so they would not collide. The
# Director therefore drives the panels by index with `write-actor-mailbox`
# (zForth custom syscall 2, `( val idx actor_idx -- )`), the same primitive
# qbert uses for its per-cube fan-out. Same lerp, same trigger, same result.
#
# ON by default since the wall correction: CONDO_DOORS=0 builds the plain wall back.
CONDO_DOORS = os.environ.get('CONDO_DOORS', '1') not in ('', '0', 'false', 'False')
MB_DOOR_ZONE, MB_DOOR_VISITED = 92, 91     # 90–94 are free: the other local zone
MB_DOOR_CLOSING, MB_DOOR_T1   = 93, 94     # mailboxes in this level are 95–99
#   91 visited-latch   92 ActBoxOR zone
#   93 target state: 0 = open (the load-time default, mailboxes are 0), 1 = closed
#   94 level time at which the in-flight slide finishes (0 at load ⇒ already settled)
DOOR_ROOM    = '639-project-rm'
DOOR_WALL    = '639-front-strip-S-wall-jamb2'
DOOR_PANELS  = 3
DOOR_TRACK_D = 0.11          # centre-to-centre spacing of the three tracks, in Y
DOOR_ZONE_D  = 1.6           # how far either side of the wall the proximity strip reaches
DOOR_SLIDE_S = 2.0           # seconds for a full open or close — reads as a real door
# The Director addresses the movable panels by runtime actor index, which is NOT
# something to count by hand out of the .lev (docs/level-design-troubleshooting.md
# § "Runtime actor indices do NOT match the .lev OBJECT ordering"). It is taken
# from the export list's own ordering in § 9c, after every actor exists, plus
# DOOR_ACTOR_IDX_BIAS — the constant offset between that list position and the
# engine's index, measured once with `wf_game --debug-print-actors` and asserted
# in the plan's Verification step 1b.
DOOR_ACTOR_IDX_BIAS = int(os.environ.get('CONDO_DOOR_IDX_BIAS', '1'))
_door_forth_fn = None        # Director clause factory; None unless the doors are built

if CONDO_DOORS:
    _door_room = next(((mn, mx) for name, mn, mx in room_outlines if name == DOOR_ROOM), None)
    assert _door_room is not None, f"{DOOR_ROOM} outline missing"
    _dr_mn, _dr_mx = _door_room

    _wall = bpy.data.objects.get(DOOR_WALL)
    assert _wall is not None, f"{DOOR_WALL} missing — the source .blend changed shape"
    _wc = [_wall.matrix_world @ Vector(c) for c in _wall.bound_box]
    _wx0, _wx1 = min(c.x for c in _wc), max(c.x for c in _wc)
    DOOR_Y = sum(c.y for c in _wc) / len(_wc)    # keep the glass on the surveyed wall plane (−2.00)

    _glass = bpy.data.materials.get('glass')
    assert _glass is not None, "no `glass` material in the appended source"

    # This wall runs along X: x 3.80 (compass south, the guest-bedroom corner) →
    # x 7.80 (compass north, the 639-patio corner). 4.00 m, three equal bays.
    DOOR_X0, DOOR_X1 = _dr_mn.x, _dr_mx.x
    DOOR_W = (DOOR_X1 - DOOR_X0) / DOOR_PANELS   # 1.33 m per panel (assumption, see the plan)

    # Shrink jamb2 to the slice that fronts the guest bedroom (x 3.65…3.80); the
    # project room's own frontage becomes the doorway. The mesh is already baked to
    # world space (bake_transform in § 3), so remap its X linearly — that keeps the
    # object's material and poly structure intact.
    _sx = (DOOR_X0 - _wx0) / (_wx1 - _wx0)
    _tx = _wall.matrix_world.translation.x     # bake_transform leaves only a translation
    for _v in _wall.data.vertices:
        _v.co.x = (_wx0 + (_v.co.x + _tx - _wx0) * _sx) - _tx
    _wall.data.update()
    print(f"[condo] {DOOR_ROOM}: {DOOR_WALL} trimmed x {_wx0:.2f}…{_wx1:.2f} → "
          f"{_wx0:.2f}…{DOOR_X0:.2f}; x {DOOR_X0:.2f}…{DOOR_X1:.2f} becomes telescoping doors")

    def _door_panel(name, track, x0, x1):
        """One solid glass panel actor, baked in world space on its own Y track.

        Mass is deliberately left unset: `as_statplat()` gives it the statplat
        schema default (75, movebloc.inc:15), which is what every ordinary wall
        in this level carries, so the panel collides like a wall.
        """
        bm = _bmesh.new()
        yc = DOOR_Y + (track - (DOOR_PANELS - 1) / 2.0) * DOOR_TRACK_D
        cube = _bmesh.ops.create_cube(bm, size=1.0)['verts']
        for v in cube:
            v.co = ((x0 + x1) / 2 + v.co.x * (x1 - x0), yc + v.co.y * GLASS_T,
                    WALL_H / 2 + v.co.z * WALL_H)
        _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        me = bpy.data.meshes.new(name)
        bm.to_mesh(me)
        bm.free()
        me.materials.append(_glass)
        obj = bpy.data.objects.new(name, me)
        scene.collection.objects.link(obj)
        clean_mesh(me, recalc=False)
        as_statplat(obj)
        return obj

    # The gather bay is the last one (x 6.47…7.80). Which end they gather at is the
    # one genuinely cosmetic choice here: this wall's faces point ±Y, so neither end
    # is literally "east" under the level's `+X north / −Y east` convention. The
    # x = 7.80 end wins because it is the corner the wide main patio (x 5.40…7.80)
    # starts from, so the stack opens onto the usable patio rather than onto the
    # narrow recessed nook by the guest bedroom.
    DOOR_GATHER_X0 = DOOR_X1 - DOOR_W

    # Geometry is baked at the panel's OPEN position, so zero offset = open = the
    # load-time default. The Director writes a negative X offset to close. (The
    # X_POS mailbox on a world-baked mesh is an additive offset, not an absolute
    # world X — docs/level-design-troubleshooting.md § 6.)
    #
    # Panel 2 (own track, own bay) is the fixed one and is never scripted; panels
    # 0 and 1 slide out to their own closed bays.
    door_panels, door_shift = [], []
    for _i in range(DOOR_PANELS):
        _p = _door_panel(f'639-project-door-panel-{_i}', _i, DOOR_GATHER_X0, DOOR_X1)
        door_panels.append(_p)
        door_shift.append((DOOR_X0 + _i * DOOR_W) - DOOR_GATHER_X0)   # 0 for the fixed panel
    assert abs(door_shift[DOOR_PANELS - 1]) < 1e-6, "the last bay must be the gather bay"

    # Proximity zone: the strip within DOOR_ZONE_D either side of the wall, so the doors
    # open whether the player approaches from the room or back from the patio. It writes
    # its own mailbox only (no camshot forwarding), so it cannot disturb zone-interior /
    # zone-balcony / zone-master, which overlap it.
    zone_doors = add_zone('zone-project-doors',
                          Vector((DOOR_X0 - pad, DOOR_Y - DOOR_ZONE_D, -0.5)),
                          Vector((DOOR_X1 + pad, DOOR_Y + DOOR_ZONE_D, WALL_H + 0.5)),
                          MB_DOOR_ZONE, door_panels[0].name)

    # Director clause, per tick:
    #   1. want := 0 (open) while the player is in the strip, or until the strip has
    #      ever been entered; 1 (closed) once they have visited and left. Mailboxes
    #      are 0 at load, so the level opens with the doors **open**, gathered at
    #      x 7.80 (plan § Context, user direction 1).
    #   2. On a change of `want`, latch it in mb 93 and stamp mb 94 with the level
    #      time the slide will finish (now + DOOR_SLIDE_S).
    #   3. f := 1 − (deadline − now)/DOOR_SLIDE_S, clamped 0…1 — the fraction of the
    #      current slide already travelled. At load mb 94 = 0 < now, so f = 1 and the
    #      panels are already settled at their target; no start-of-level animation.
    #   4. c := "closedness" = f when closing, 1 − f when opening; each movable
    #      panel's X offset is c × its closed-minus-open shift.
    def _door_forth_fn(idx0):
        return (
            f"{MB_DOOR_ZONE} read-mailbox 0 <> if "
            f"1 {MB_DOOR_VISITED} write-mailbox 0 {MB_DOOR_ZONE} write-mailbox 0 "
            f"else {MB_DOOR_VISITED} read-mailbox 0 = if 0 else 1 then then "
            f"dup {MB_DOOR_CLOSING} read-mailbox <> if "
            f"dup {MB_DOOR_CLOSING} write-mailbox "
            f"INDEXOF_TIME read-mailbox {DOOR_SLIDE_S} + {MB_DOOR_T1} write-mailbox then "
            f"1 {MB_DOOR_T1} read-mailbox INDEXOF_TIME read-mailbox - {DOOR_SLIDE_S} / - "
            f"dup 1 > if drop 1 then dup 0 < if drop 0 then "
            f"swap 0 = if 1 swap - then "
            + "".join(f"dup {door_shift[_i]:.4f} * INDEXOF_X_POS "
                      f"{idx0 + _i} write-actor-mailbox "
                      for _i in range(DOOR_PANELS - 1))
            + "drop\n")
    print(f"[condo] {DOOR_ROOM} telescoping doors: {DOOR_PANELS} solid panels "
          f"({DOOR_W:.2f} m each, statplat default Mass); panel {DOOR_PANELS - 1} fixed at "
          f"x {DOOR_GATHER_X0:.2f}…{DOOR_X1:.2f}, panels 0…{DOOR_PANELS - 2} slide "
          f"{', '.join(f'{s:+.2f} m' for s in door_shift[:-1])} to close the "
          f"x {DOOR_X0:.2f}…{DOOR_X1:.2f} frontage over {DOOR_SLIDE_S:.1f} s; "
          f"z 0.00…{WALL_H:.2f} at y {DOOR_Y:.2f}, tracks {DOOR_TRACK_D:.2f} m apart; "
          f"mailboxes zone {MB_DOOR_ZONE} visited {MB_DOOR_VISITED} closing {MB_DOOR_CLOSING} "
          f"deadline {MB_DOOR_T1}")
else:
    print(f"[condo] {DOOR_ROOM} telescoping doors: OFF (CONDO_DOORS=0 set; the plain "
          f"{DOOR_WALL} stays — see docs/plans/2026-09-20-condo-project-room-telescoping-doors.md)")

# ── 8. Lights, matte, director, levelobj ─────────────────────────────────────
light = find_by_class('light')
assert light is not None
light.name = 'Sun'
light.location = (0.0, -8.0, 8.0)
light.rotation_euler = wf_light_aim(SUN_ALT_DEG, SUN_AZ_DEG)
light['wf_lightType']  = 'Directional'
light['wf_lightRed']   = 1.0
light['wf_lightGreen'] = 1.0
light['wf_lightBlue']  = 0.96
light['wf_Model Type'] = 'None'
ambient = light.copy()
ambient.data = light.data.copy() if light.data else None
scene.collection.objects.link(ambient)
ambient.name = 'AmbientLight'
ambient.location = (0.0, -8.0, 8.0)
ambient['wf_lightType']  = 'Ambient'
# 0.45 → 0.38 (still inside the 0.3–0.5 fill band documented in
# docs/level-building.md § "Lighting"): the flat ambient term carries less of the
# image so the two directional terms — and the gradient between differently
# angled walls — read more strongly. Same slightly-cool grey ratio as before.
ambient['wf_lightRed']   = AMBIENT
ambient['wf_lightGreen'] = AMBIENT
ambient['wf_lightBlue']  = AMBIENT * (0.50 / 0.45)

# Second directional slot — ON by default since 2026-09-20.
#
# History, because it was mis-diagnosed once: this looked like "the 2nd and 3rd
# Light actors are read as AMBIENT regardless of what is authored", since adding
# a third `light` actor killed wf_game on `assert(ambientLightIndex < 1)`
# (game/level.cc:1200) even with all three authored `lightType = Directional`.
# The level data was never wrong. `wfsource/source/oas/levelcon.h` had
# AMBIENT_LIGHT=0 / DIRECTIONAL_LIGHT=1, the reverse of the `"Directional|Ambient"`
# enum in light.oas that every tool writes — so *every* light in *every* level
# went into the wrong slot, and two Directionals became two ambients. Fixed in
# docs/plans/2026-09-20-engine-multi-directional-light-fix.md, together with the
# position leak in Light::Set that made these beams point at the ceiling.
if FILL_INTENSITY > 0.0:
    fill = light.copy()
    fill.data = light.data.copy() if light.data else None
    scene.collection.objects.link(fill)
    fill.name = 'FillLight'
    fill.location = (0.0, -8.0, 8.0)
    fill.rotation_euler = wf_light_aim(FILL_ALT_DEG, FILL_AZ_DEG)
    fill['wf_lightType']  = 'Directional'
    fill['wf_lightRed']   = FILL_INTENSITY * 0.85
    fill['wf_lightGreen'] = FILL_INTENSITY * 0.92
    fill['wf_lightBlue']  = FILL_INTENSITY * 1.00
    fill['wf_Model Type'] = 'None'
    print(f"[condo] lights: Sun az {SUN_AZ_DEG}° alt {SUN_ALT_DEG}°, FillLight az {FILL_AZ_DEG}° "
          f"alt {FILL_ALT_DEG}° intensity {FILL_INTENSITY}, Ambient {AMBIENT:.2f}")
else:
    print(f"[condo] lights: Sun az {SUN_AZ_DEG}° alt {SUN_ALT_DEG}°, Ambient {AMBIENT:.2f}; "
          f"FillLight disabled (CONDO_FILL_INTENSITY=0)")

matte = find_by_class('matte')
assert matte is not None
matte.name = 'Matte'
matte.location = (0.0, -8.0, 14.0)
matte['wf_Matte Type']         = 'Color'
matte['wf_Background Color']   = 0x9FB8D0
matte['wf_Visibility Mailbox'] = 1
matte['wf_Model Type']         = 'None'

director = find_by_class('director')
assert director is not None, "snowgoons scaffold has no director (needed for the camera zones)"
director.name = 'Director'
director['wf_Model Type'] = 'None'
# Camera-zone multiplexer (replaces snowgoons' 100/99/98 version): forward each zone's
# mailbox to INDEXOF_CAMSHOT and zero it, patio last so it wins on a boundary tick.
# Mailbox 97 holds the level time the patio zone was entered (for BalconyLook's sweep) and
# is zeroed the first tick the zone stops writing.
def _zone_forward(zone_mb, t0_mb=None):
    s = f"{zone_mb} read-mailbox dup 0 <> if INDEXOF_CAMSHOT write-mailbox 0 {zone_mb} write-mailbox "
    if t0_mb:
        s += f"{t0_mb} read-mailbox 0 = if INDEXOF_TIME read-mailbox {t0_mb} write-mailbox then else drop 0 {t0_mb} write-mailbox then\n"
    else:
        s += "else drop then\n"
    return s


# Interior first, the window zones after it, so a window shot wins while its strip is
# occupied (the strips lie inside the interior zone).
director['wf_Script'] = ("\\ wf\n" + _zone_forward(MB_ZONE_INTERIOR)
                         + _zone_forward(MB_ZONE_BALCONY, MB_BALCONY_T0)
                         + _zone_forward(MB_ZONE_MASTER, MB_MASTER_T0))
# The telescoping-door clause is appended in § 9c, once the export ordering (and
# therefore each panel's runtime actor index) is known.

levelobj = find_by_class('levelobj')
assert levelobj is not None
levelobj.name = 'Level'
levelobj['wf_Num Mailboxes'] = NUM_MAILBOXES
levelobj['wf_Model Type'] = 'None'

# ── 9. Room bounds ───────────────────────────────────────────────────────────
room = find_by_class('room')
assert room is not None
room.name = 'room_condo'
room.location = ROOM_CENTRE
hx, hy, hz = ROOM_HALF
rel = (-hx, -hy, -hz, hx, hy, hz)
room['wf_original_bbox'] = rel
rv = [(rel[0], rel[1], rel[2]), (rel[3], rel[1], rel[2]), (rel[3], rel[4], rel[2]), (rel[0], rel[4], rel[2]),
      (rel[0], rel[1], rel[5]), (rel[3], rel[1], rel[5]), (rel[3], rel[4], rel[5]), (rel[0], rel[4], rel[5])]
rf = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
rmesh = bpy.data.meshes.new('RoomBounds')
rmesh.from_pydata(rv, [], rf)
rmesh.update()
old = room.data
room.data = rmesh
if old and old.users == 0:
    bpy.data.meshes.remove(old)
# The room mesh is only a bbox visualisation: hide it (eye off) and draw it as wire
# so it never occludes the level in the saved .blend. The exporter writes it anyway.
room.display_type = 'WIRE'
room.hide_render = True
room.hide_set(True)
# Other non-rendering infrastructure draws as wire too (level-building.md § Blender
# Viewport Display by Object Type).
for o in scene.objects:
    if o.get('wf_schema_path') and get_class(o) in ('camera', 'camshot', 'target', 'light',
                                                    'matte', 'levelobj', 'director'):
        o.display_type = 'WIRE'

# ── 9b. Lift to the 6th floor ────────────────────────────────────────────────
# Everything above was authored with the unit floor at z = 0 (slab_outline, darken_floors
# and the tour's spawn all assume it); the ground map and the dome are world-space already.
# The camera rig (cs_dollhouse, CamTarget, LookAt) is relative — position = (camshot − Follow)
# + TrackObject — so lifting all three by the same amount changes nothing.
for o in scene.objects:
    if o.get('wf_schema_path') and o.name not in NOT_LIFTED:
        o.location.z += UNIT_Z

# Every actor centre must be strictly inside the room bbox or levcomp drops it
# from the render list (troubleshooting § "falls outside every room bbox").
bpy.context.view_layer.update()          # matrix_world is stale until the depsgraph runs
lo = tuple(c - h + 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
hi = tuple(c + h - 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
outside = [o.name for o in scene.objects
           if o.get('wf_schema_path') and get_class(o) != 'room'
           and not all(lo[i] < o.matrix_world.to_translation()[i] < hi[i] for i in range(3))]
assert not outside, f"actors outside room bbox {lo}..{hi}: {outside}"

# ── 9c. Door panels: resolve runtime actor indices, finish the Director clause ─
# The exporter writes actors in this exact list order, and the engine's runtime
# index is that position plus DOOR_ACTOR_IDX_BIAS. Doing it here — rather than
# guessing from creation order back in § 7c — means adding or removing any actor
# anywhere in this file re-derives the indices instead of silently aiming the
# door script at the wrong actor.
wf_objects = [o for o in scene.objects if o.get('wf_schema_path')]
if _door_forth_fn is not None:
    _panel_pos = [wf_objects.index(p) for p in door_panels]
    assert _panel_pos == list(range(_panel_pos[0], _panel_pos[0] + DOOR_PANELS)), \
        f"door panels are not contiguous in the export list: {_panel_pos}"
    DOOR_PANEL0_ACTOR_IDX = _panel_pos[0] + DOOR_ACTOR_IDX_BIAS
    director['wf_Script'] += _door_forth_fn(DOOR_PANEL0_ACTOR_IDX)
    print(f"[condo] {DOOR_ROOM} telescoping doors: movable panels are runtime actors "
          f"{DOOR_PANEL0_ACTOR_IDX}…{DOOR_PANEL0_ACTOR_IDX + DOOR_PANELS - 2} "
          f"(export positions {_panel_pos[0]}…{_panel_pos[-1]} + bias {DOOR_ACTOR_IDX_BIAS}); "
          f"verify with `wf_game --debug-print-actors`")

# ── 10. Export ───────────────────────────────────────────────────────────────
os.makedirs(OUT_DIR, exist_ok=True)
_wrapper = os.path.join(OUT_DIR, LEVEL_NAME + '-standalone.iff.txt')
if LEVEL_NAME != 'condo_639_640':
    if not os.path.exists(_wrapper):
        with open(os.path.join(SCRIPT_DIR, 'condo_639_640-standalone.iff.txt')) as _src, open(_wrapper, 'w') as _dst:
            _dst.write(_src.read().replace('condo_639_640', LEVEL_NAME))
    # textile-rs reads textures and textile.flags from the level dir, so a derived build
    # (the tour) gets fresh copies of the site textures every run.
    import shutil
    for _f in ('condo_ground.tga', 'condo_sky.tga', 'textile.flags'):
        shutil.copyfile(os.path.join(SCRIPT_DIR, _f), os.path.join(OUT_DIR, _f))
bpy.ops.wm.save_as_mainfile(filepath=OUT_BLEND)
print(f"[condo] saved assembled scene → {OUT_BLEND}")
print(f"[condo] exporting {len(wf_objects)} actors → {OUT_LEV}")
bpy.ops.wf.export_level(filepath=OUT_LEV)
print("[condo] done:", stats)
