"""
blender_create_condo.py — convert the 205/639 + 205/640 condo model into a
walkable WorldFoundry level.

Source: ~/docs/aircon/units-639-640.blend (generated by ~/scripts/aircon-blender.py,
rebuild with `cd ~ && task aircon-blender`). Read only — never written.

Usage:
    blender --background --python blender_create_condo.py -- [path/to/units-639-640.blend]
    task build-level -- condo_639_640          # or just: task condo-level
    task run-condo

Pattern: wflevels/moon_site01/blender_create_moon.py — import the snowgoons
scaffold for infrastructure, strip its gameplay, add our geometry as `statplat`
mesh actors (Jolt builds a trimesh body from the render mesh, so walls/floors are
solid and doorways passable straight from the geometry), export.

Plan: docs/plans/2026-09-19-condo-639-640-level.md
"""

import math
import os
import re
import sys

import addon_utils
import bpy
from mathutils import Matrix, Vector

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO       = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
SNOWGOONS  = os.path.join(REPO, 'wflevels', 'snowgoons-blender', 'snowgoons-blender.lev')
OAD_DIR    = os.path.join(REPO, 'wftools', 'wf_oad', 'tests', 'fixtures')
LEVEL_NAME = os.environ.get('CONDO_LEVEL', 'condo_639_640')   # e.g. condo_639_640_tour for the tour build
OUT_DIR    = os.path.join(REPO, 'wflevels', LEVEL_NAME)
OUT_LEV    = os.path.join(OUT_DIR, LEVEL_NAME + '.lev')
OUT_BLEND  = os.path.join(OUT_DIR, LEVEL_NAME + '.blend')      # the assembled WF scene, for inspection in Blender
TOUR_PATH  = os.environ.get('CONDO_TOUR', '')                  # path .json → player walks it (see tour_forth below)

_argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
SRC_BLEND = os.path.abspath(os.path.expanduser(
    _argv[0] if _argv else os.environ.get('CONDO_BLEND', '~/docs/aircon/units-639-640.blend')))
if not os.path.isfile(SRC_BLEND):
    raise SystemExit(f"[condo] source .blend not found: {SRC_BLEND} "
                     f"(rebuild with `cd ~ && task aircon-blender`, or pass the path)")

# Collections to bring over. `640-midea-option-B-over-door` is the rejected
# alternative (hidden) and is never appended.
SRC_COLLECTIONS = ['205-639', '205-640', '640-midea-option-A-closet-wall']

# ── Level constants (metres, WF == Blender axes: X right, Y depth, Z up) ───────
WALL_H        = 2.7
GLASS_T       = 0.10    # source panes are 0.02 m — sub-decimetre slabs have gone
                        # invisible before (troubleshooting § "too thin in
                        # camera-depth axis"); 0.10 fills the wall opening exactly.
# Real-world placement (pin, compass ↔ axes, 6th-floor elevation, texture sizes) is shared
# with make_site_textures.py so the sky/ground textures and the geometry can't disagree.
sys.path.insert(0, SCRIPT_DIR)
from site_constants import UNIT_Z, SLAB_T, GROUND_HALF, SKY_R           # noqa: E402
CORRIDOR      = (-9.0, -17.4, 9.0, -15.4)   # x0, y0, x1, y1: open-air corridor outside both front doors
PARAPET_H     = 1.1                          # railing on its outer edge — a 16 m drop otherwise
PARAPET_T     = 0.15
PLAYER_H      = 1.70
PLAYER_SPAWN  = tuple(float(v) for v in os.environ['CONDO_SPAWN'].split(',')) if os.environ.get('CONDO_SPAWN') \
                else (4.66, -14.5, 0.30)     # just inside 639's front door — the unit is on the 6th floor, so
                                             # the level starts in the condo, not on the street (CONDO_SPAWN=x,y,z overrides)
TOUR = None
if TOUR_PATH:
    import json
    with open(TOUR_PATH) as _f:
        TOUR = json.load(_f)
    PLAYER_SPAWN = tuple(TOUR.get('spawn', PLAYER_SPAWN))
    os.environ.setdefault('CONDO_ACCEL', str(TOUR.get('accel', 105)))
    os.environ.setdefault('CONDO_DECEL', str(TOUR.get('decel', 0.85)))
CAM_OFFSET    = tuple(float(v) for v in os.environ['CONDO_CAM'].split(',')) if os.environ.get('CONDO_CAM') \
                else (0.0, -3.5, 9.0)        # doll-house view: 69° elevation from the east (CONDO_CAM=x,y,z
                                             # overrides, e.g. 0,-1.5,1.2 for a low shot that sees the sky dome)
LOOK_OFFSET   = tuple(float(v) for v in os.environ['CONDO_LOOK'].split(',')) if os.environ.get('CONDO_LOOK') \
                else (0.0, 0.0, 0.9)         # aim at the player's chest, not the feet (CONDO_LOOK=x,y,z overrides)
ROOM_CENTRE   = (0.0, -8.0, 12.0)            # z −4…28: ground quad and dome centres, the lifted units, the camera
ROOM_HALF     = (15.0, 18.0, 16.0)           # y −26…10: the corridor and the balcony camera's look target
NUM_MAILBOXES = 100
SUN_ALT_DEG   = 50.0
SUN_AZ_DEG    = 30.0

# ── 1. Clean scene, enable add-on, import the snowgoons scaffold ─────────────
bpy.ops.wm.read_factory_settings(use_empty=True)
addon_utils.enable("wf_blender", default_set=False, persistent=False)
if not hasattr(bpy.ops.wf, 'import_level'):
    raise SystemExit("[condo] wf_blender add-on not available — install it "
                     "(task blender-install until the apt package exists)")
scene = bpy.context.scene

print(f"[condo] importing scaffold {SNOWGOONS}")
bpy.ops.wf.import_level(filepath=SNOWGOONS)

KEEP_CLASSES = {'director', 'camera', 'levelobj', 'matte', 'light',
                'room', 'camshot', 'target', 'player'}


def get_class(obj):
    schema = obj.get('wf_schema_path', '')
    return os.path.splitext(os.path.basename(schema))[0] if schema else ''


def find_by_class(cn):
    for obj in bpy.data.objects:
        if get_class(obj) == cn:
            return obj
    return None


def attach_schema(obj, oad_name):
    obj['wf_schema_path'] = os.path.join(OAD_DIR, oad_name + '.oad')


for obj in list(bpy.data.objects):
    if get_class(obj) not in KEEP_CLASSES:
        bpy.data.objects.remove(obj, do_unlink=True)
seen = set()
for obj in list(bpy.data.objects):
    cn = get_class(obj)
    if cn in seen:
        bpy.data.objects.remove(obj, do_unlink=True)
    else:
        seen.add(cn)
print("[condo] scaffold classes:", sorted({get_class(o) for o in bpy.data.objects}))
# Snowgoons meshes carried .tga textures; none of the survivors render (all
# Model Type 'None' below) except the player, whose mesh we replace.

# ── 2. Append the condo collections from the source .blend ───────────────────
before = set(bpy.data.objects)
for cname in SRC_COLLECTIONS:
    bpy.ops.wm.append(filepath=os.path.join(SRC_BLEND, 'Collection', cname),
                      directory=os.path.join(SRC_BLEND, 'Collection') + os.sep,
                      filename=cname, link=False)
appended = [o for o in bpy.data.objects if o not in before]
print(f"[condo] appended {len(appended)} objects from {os.path.basename(SRC_BLEND)}")
bpy.context.view_layer.update()


def sanitize(name):
    """Blender name → asset filename slug: lowercase, runs of non-alnum → '_'.

    The engine's asset string map holds 31 bytes per name (assets.cc
    ReadAssetMap asserts `BytesLeft() < 32`), so `<slug>.iff` must stay ≤ 30
    chars: long names are cut to 21 chars + a 4-hex hash of the full name.
    """
    import zlib
    slug = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')
    if len(slug) > 26:
        slug = f"{slug[:21].rstrip('_')}_{zlib.crc32(name.encode()) & 0xffff:04x}"
    return slug


def make_flat_material(name, rgb):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next((n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED'), None)
    if bsdf:
        bsdf.inputs['Base Color'].default_value = (*rgb, 1.0)
    mat.diffuse_color = (*rgb, 1.0)
    return mat


def bake_transform(obj):
    """Fold rotation+scale (and any parent transform) into the mesh verts, leaving
    only a translation on the object. The Jolt trimesh body is built from raw
    local verts and ignores actor scale/rotation (troubleshooting § "Per-actor
    scale"), and the render path shears a rotated non-uniform scale."""
    mw = obj.matrix_world.copy()
    obj.parent = None
    if obj.data.users > 1:
        obj.data = obj.data.copy()
    rs = mw.to_3x3()
    for v in obj.data.vertices:
        v.co = rs @ v.co
    obj.matrix_world = Matrix.Translation(mw.to_translation())
    obj.data.update()


# The engine computes each face normal at load as (v2−v0)×(v1−v0) and asserts its
# length > Scalar(0,4) ≈ 6.1e-5 in 1.15.16 fixed point (math/vector3.hpi:243,
# "Probably have a polygon which is too small") — i.e. any triangle with area
# < ~3e-5 m² aborts the level. Bevelled-curve corners produce exactly those.
MIN_FACE_AREA = 8e-5
_dropped = {'faces': 0}


def clean_mesh(mesh, recalc=True):
    import bmesh
    bm = bmesh.new()
    bm.from_mesh(mesh)
    bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
    bmesh.ops.triangulate(bm, faces=bm.faces)
    tiny = [f for f in bm.faces if f.calc_area() < MIN_FACE_AREA]
    if tiny:
        _dropped['faces'] += len(tiny)
        bmesh.ops.delete(bm, geom=tiny, context='FACES_ONLY')
        bmesh.ops.delete(bm, geom=[v for v in bm.verts if not v.link_faces], context='VERTS')
    if recalc:
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()


def curve_to_mesh(obj):
    """Bevelled POLY curve → tube mesh object of the same name (materials kept)."""
    dg = bpy.context.evaluated_depsgraph_get()
    ev = obj.evaluated_get(dg)
    me = bpy.data.meshes.new_from_object(ev, preserve_all_data_layers=True, depsgraph=dg)
    if not me.materials:
        for m in obj.data.materials:
            me.materials.append(m)
    me.name = obj.name
    cols = list(obj.users_collection)
    name, mw = obj.name, obj.matrix_world.copy()
    bpy.data.objects.remove(obj, do_unlink=True)
    new = bpy.data.objects.new(name, me)
    new.matrix_world = mw
    for c in cols:
        c.objects.link(new)
    return new


def as_statplat(obj):
    attach_schema(obj, 'statplat')
    obj['wf_Mobility']           = 'Anchored'
    obj['wf_Model Type']         = 'Mesh'
    obj['wf_Visibility Mailbox'] = 1
    # Actor NAME stays the Blender name; the mesh file gets a dot/hyphen-free slug
    # so the asset tools never see `foo.001.iff`.
    obj['wf_original_mesh_name'] = sanitize(obj.name) + '.iff'


def collection_hidden(obj):
    return any(c.hide_viewport or c.hide_render for c in obj.users_collection)


# ── 3. Classify and convert the appended objects ─────────────────────────────
mat_grey = make_flat_material('prop-grey', (0.80, 0.80, 0.82))
room_outlines = []      # (name, world bbox min, world bbox max)
stats = {'mesh': 0, 'curve': 0, 'room': 0, 'skipped': []}

for obj in list(appended):
    if obj.hide_viewport or obj.hide_render or collection_hidden(obj):
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if obj.type == 'CURVE':
        obj = curve_to_mesh(obj)
        bake_transform(obj)
        clean_mesh(obj.data, recalc=False)       # tube normals already point outward
        as_statplat(obj)
        stats['curve'] += 1
        continue
    if obj.type != 'MESH':
        stats['skipped'].append(obj.name)
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    if len(obj.data.polygons) == 0:
        # display-WIRE room outline: remember its world bbox, drop the object
        corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
        mn = Vector((min(c.x for c in corners), min(c.y for c in corners), min(c.z for c in corners)))
        mx = Vector((max(c.x for c in corners), max(c.y for c in corners), max(c.z for c in corners)))
        room_outlines.append((obj.name, mn, mx))
        bpy.data.objects.remove(obj, do_unlink=True)
        continue
    is_glass = any(m and m.name == 'glass' for m in obj.data.materials)
    if is_glass and abs(obj.scale.y) < 0.05:
        obj.scale.y = GLASS_T
        bpy.context.view_layer.update()
    bake_transform(obj)
    clean_mesh(obj.data)
    if not obj.data.materials:
        obj.data.materials.append(mat_grey)          # consumer units have no material
    as_statplat(obj)
    stats['mesh'] += 1

print(f"[condo] converted: {stats['mesh']} meshes, {stats['curve']} tubes, "
      f"{len(room_outlines)} room outlines; dropped {_dropped['faces']} sub-threshold faces; "
      f"skipped hidden: {stats['skipped']}")

# ── 3b. Floors: darker shade of the owning unit's colour ───────────────────
# Floor and walls share one material per unit in the source, so from the
# doll-house camera the floor, wall faces and wall tops merge into one mass.
# Give each shell's floor-top faces (normal +Z at z≈0) their own material: the
# face's current colour scaled by FLOOR_SHADE (per face, so 640's 639-blue
# master suite keeps a blue — darker — floor). CONDO_FLOOR_SHADE overrides.
FLOOR_SHADE = float(os.environ.get('CONDO_FLOOR_SHADE', 0.55))


def darken_floors(obj, shade):
    me = obj.data
    if not me.materials or shade >= 0.999:
        return 0
    floor_mats = {}          # source material index → darkened material index
    n = 0
    for pg in me.polygons:
        if pg.normal.z < 0.9 or abs(pg.center.z) > 1e-3:
            continue
        src_i = pg.material_index
        if src_i not in floor_mats:
            src = me.materials[src_i]
            r, g, b, _a = src.diffuse_color
            dark = make_flat_material(f'floor-{src.name}-{shade:.2f}', (r * shade, g * shade, b * shade))
            me.materials.append(dark)
            floor_mats[src_i] = len(me.materials) - 1
        pg.material_index = floor_mats[src_i]
        n += 1
    return n


for shell_name in ('unit-639', 'unit-640'):
    shell = bpy.data.objects.get(shell_name)
    if shell:
        print(f"[condo] {shell_name}: {darken_floors(shell, FLOOR_SHADE)} floor faces at shade {FLOOR_SHADE}")

# ── 4. Room outlines → named `target` locators (bbox = room, no Jolt body) ───
target_proto = find_by_class('target')
assert target_proto is not None, "snowgoons scaffold has no target"
target_proto.name = 'CamTarget'
for name, mn, mx in room_outlines:
    t = target_proto.copy()
    t.data = None
    t.name = name
    centre = (mn + mx) / 2.0
    t.location = centre
    t.rotation_euler = (0.0, 0.0, 0.0)
    t.scale = (1.0, 1.0, 1.0)
    half = (mx - mn) / 2.0
    t['wf_original_bbox'] = (-half.x, -half.y, -half.z, half.x, half.y, half.z)
    t['wf_had_authored_bbox'] = True
    t['wf_original_mesh_name'] = ''
    t['wf_Model Type'] = 'None'
    scene.collection.objects.link(t)
stats['room'] = len(room_outlines)

# ── 5. Site: corridor outside the doors, the ground map far below, the sky dome ──
# The units are on the 6th floor (UNIT_Z = 15.75 m), so "outside the front door" is the
# building's open-air corridor, not the ground: a slab strip with a parapet. The ground is a
# textured quad at world z = 0 (condo_ground.tga, OSM flat map, ±GROUND_HALF m) and the sky
# an inverted sphere with an equirectangular panorama (condo_sky.tga) — both generated by
# make_site_textures.py from site-osm.json, both routed to the PERM atlas like the moon's
# skydome (Moves Between Rooms). Everything else is authored at z = 0 and lifted in § 9b.
import bmesh as _bmesh


def box_mesh(name, x0, y0, z0, x1, y1, z1):
    """Closed box with outward normals (exterior geometry — see level-building.md § winding)."""
    bm = _bmesh.new()
    _bmesh.ops.create_cube(bm, size=1.0)
    for v in bm.verts:
        v.co = ((x0 + x1) / 2 + v.co.x * (x1 - x0), (y0 + y1) / 2 + v.co.y * (y1 - y0), (z0 + z1) / 2 + v.co.z * (z1 - z0))
    _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    return me


def add_flat_actor(name, mesh, rgb):
    mesh.materials.append(make_flat_material(name, rgb))
    obj = bpy.data.objects.new(name, mesh)
    scene.collection.objects.link(obj)
    clean_mesh(mesh, recalc=False)
    as_statplat(obj)
    return obj


def make_textured_material(name, tga):
    """White BSDF base + image texture: the WF fragment shader samples the texture only
    when the vertex colour is white (`step(0.99, min(rgb))`, backend_modern.cc kFS)."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
    tex = mat.node_tree.nodes.new('ShaderNodeTexImage')
    tex.image = bpy.data.images.load(os.path.join(SCRIPT_DIR, tga))
    mat.node_tree.links.new(tex.outputs['Color'], bsdf.inputs['Base Color'])
    bsdf.inputs['Base Color'].default_value = (1.0, 1.0, 1.0, 1.0)
    mat.diffuse_color = (1.0, 1.0, 1.0, 1.0)
    return mat


for tga in ('condo_ground.tga', 'condo_sky.tga'):
    if not os.path.isfile(os.path.join(SCRIPT_DIR, tga)):
        raise SystemExit(f"[condo] missing {tga} — run `task condo-textures` (make_site_textures.py render)")

cx0, cy0, cx1, cy1 = CORRIDOR
corridor = add_flat_actor('corridor', box_mesh('corridor', cx0, cy0, -SLAB_T, cx1, cy1, 0.0), (0.62, 0.62, 0.60))
parapet = add_flat_actor('corridor-parapet',
                         box_mesh('corridor-parapet', cx0, cy0 - PARAPET_T, 0.0, cx1, cy0, PARAPET_H), (0.70, 0.70, 0.68))

# WF texture V runs top-down: gfx/material.cc CalcVRAMuv maps v = 0 to the texture's first
# (top) row and the exporter passes Blender's uv.y through unflipped — the opposite of
# Blender/GL, where v = 0 is the bottom row. So "image top" is v = 0 here.
# Ground map: one quad, UV so image top (north = +X) is v = 0 and image right (east = −Y) is u = 1.
_gm = bpy.data.meshes.new('site-map')
_g = GROUND_HALF
# Winding pinned to +Z in Blender's convention (CCW seen from above), the same way the corridor
# box comes out of create_cube + recalc, which WF_CULL=1 keeps; recalc on a lone open quad is a
# coin toss and the first attempt vanished under culling.
_gm.from_pydata([(-_g, -_g, 0.0), (_g, -_g, 0.0), (_g, _g, 0.0), (-_g, _g, 0.0)], [], [(0, 3, 2, 1)])
_uv = _gm.uv_layers.new(name='UVMap')
for li, loop in enumerate(_gm.loops):
    x, y, _z = _gm.vertices[loop.vertex_index].co
    _uv.data[li].uv = (0.5 - y / (2 * _g), 0.5 - x / (2 * _g))
_gm.update()
_gm.materials.append(make_textured_material('site-map', 'condo_ground.tga'))
site_map = bpy.data.objects.new('site-map', _gm)
scene.collection.objects.link(site_map)
clean_mesh(_gm, recalc=False)                     # triangulate only — keep the pinned winding
as_statplat(site_map)
site_map['wf_Moves Between Rooms'] = 'True'


def build_skydome(radius, segs=48, rings=24):
    """Lat/long sphere with explicit UVs: column j at compass θ = 360·j/segs, level position
    (R cosθ cosφ, −R sinθ cosφ, R sinφ) since +X is north and +Y west; u = θ/360, v = (90−φ)/180
    (WF v = 0 is the top row = zenith, see the site-map note above).
    One extra seam column (segs+1 vertex columns) so no face straddles u = 1 → 0. Faces are
    wound inward (the player is inside)."""
    verts, uvs = [], []
    for i in range(rings + 1):
        phi = math.radians(-90.0 + 180.0 * i / rings)
        for j in range(segs + 1):
            th = math.radians(360.0 * j / segs)
            verts.append((radius * math.cos(th) * math.cos(phi), -radius * math.sin(th) * math.cos(phi), radius * math.sin(phi)))
            uvs.append((j / segs, 1.0 - i / rings))
    faces = []
    cols = segs + 1
    for i in range(rings):
        for j in range(segs):
            a, b, c, d = i * cols + j, i * cols + j + 1, (i + 1) * cols + j + 1, (i + 1) * cols + j
            if i == 0:
                faces.append((a, d, c))          # pole triangles (a == b position-wise)
            elif i == rings - 1:
                faces.append((a, d, b))
            else:
                faces.append((a, d, c, b))
    me = bpy.data.meshes.new('skydome')
    me.from_pydata(verts, [], faces)
    uv = me.uv_layers.new(name='UVMap')
    for li, loop in enumerate(me.loops):
        uv.data[li].uv = uvs[loop.vertex_index]
    me.update()
    bm = _bmesh.new()
    bm.from_mesh(me)
    _bmesh.ops.recalc_face_normals(bm, faces=bm.faces)   # outward first …
    _bmesh.ops.reverse_faces(bm, faces=bm.faces)          # … then flip: inner surface visible
    bm.to_mesh(me)
    bm.free()
    me.update()
    return me


_sky = build_skydome(SKY_R)
_sky.materials.append(make_textured_material('skydome', 'condo_sky.tga'))
skydome = bpy.data.objects.new('skydome', _sky)
scene.collection.objects.link(skydome)
skydome.location = (0.0, -8.0, UNIT_Z)          # world-space: the viewpoint the panorama was painted from
clean_mesh(_sky, recalc=False)
as_statplat(skydome)
skydome['wf_Moves Between Rooms'] = 'True'
# Mass 0 ⇒ Actor::CanCollide() is false (actor.cc:1079: collisionTable[kind] && Mass > 0).
# Camera obstacle avoidance is a *bbox* overlap pass, and the dome's bbox is the whole
# level — with a mass the camera "hit" it every tick and climbed (BungeeCameraHandler
# ClimbRate) until every shot was 12 m higher than authored.
skydome['wf_Mass'] = 0.0
NOT_LIFTED = {site_map.name, skydome.name, 'room_condo', 'Matte'}   # world-space: ground, sky, room bounds, backdrop
print(f"[condo] site: corridor {cx1 - cx0:.0f}×{cy1 - cy0:.0f} m + parapet, site-map ±{_g:.0f} m, "
      f"skydome R={SKY_R:.0f} m {len(_sky.vertices)} verts {len(_sky.polygons)} tris; units → z={UNIT_Z}")

# ── 6. Player: 1.7 m figure, feet at local z=0, +X front marker ──────────────
def build_figure():
    mat_body = make_flat_material('figure-body', (0.20, 0.32, 0.55))
    mat_head = make_flat_material('figure-head', (0.90, 0.75, 0.60))
    mat_mark = make_flat_material('figure-front', (0.95, 0.25, 0.20))
    parts = []
    bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.20, depth=1.20, location=(0, 0, 0.60))
    parts.append((bpy.context.object, mat_body))
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.16, segments=10, ring_count=6, location=(0, 0, 1.50))
    parts.append((bpy.context.object, mat_head))
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0.20, 0, 1.10))
    mark = bpy.context.object
    mark.scale = (0.08, 0.16, 0.20)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    parts.append((mark, mat_mark))
    for o, m in parts:
        o.data.materials.clear()
        o.data.materials.append(m)
        for p in o.data.polygons:
            p.material_index = 0
    bpy.ops.object.select_all(action='DESELECT')
    for o, _ in parts:
        o.select_set(True)
    body = parts[0][0]
    bpy.context.view_layer.objects.active = body
    bpy.ops.object.join()
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
    min_z = min(v.co.z for v in body.data.vertices)
    for v in body.data.vertices:
        v.co.z -= min_z
    body.data.name = 'figure'
    return body


player = find_by_class('player')
assert player is not None, "snowgoons scaffold has no player"
_fig = build_figure()
player.name = 'Player'
player.data = _fig.data
bpy.data.objects.remove(_fig, do_unlink=True)
# The imported scaffold player carries snowgoons' authored bbox (`wf_original_bbox`,
# ±0.33 × ±0.36 × 0…2.0 m) and the exporter prefers it over the mesh — with it the
# Jolt capsule is 2.0 m tall and can't pass a 2.0 m door header. Drop it so the
# BOX3 (→ capsule radius 0.2, height 1.66) comes from the figure we just built.
for key in ('wf_original_bbox', 'wf_had_authored_bbox'):
    if key in player:
        del player[key]
player.location = PLAYER_SPAWN
player.scale = (1.0, 1.0, 1.0)
player.rotation_euler = (0.0, 0.0, math.pi / 2)      # face +Y: into the units, doom-stick strafe = screen X
player['wf_Mobility']              = 'Physics'
player['wf_Mass']                  = 70.0
player['wf_Model Type']            = 'Mesh'
player['wf_Visibility Mailbox']    = 1
# Calibrated on the bridge (motion profile of a straight walk): ground speed is
# the terminal velocity of `Running Acceleration` against `Running Deceleration`
# 0.85 — accel 8 → 0.31 m/s, 40 → 1.55 m/s, 80 → 3.0 m/s (≈ accel/26) — and
# `Max Ground Speed` never binds at these values. 40 = indoor walking pace.
# CONDO_ACCEL / CONDO_SPEED override for tour recordings (4 m/s ≈ accel 105).
player['wf_Running Acceleration']  = float(os.environ.get('CONDO_ACCEL', 40.0))
player['wf_Running Deceleration']  = float(os.environ.get('CONDO_DECEL', 0.85))   # 0.85 = long glide; tour uses more
player['wf_Max Ground Speed']      = float(os.environ.get('CONDO_SPEED', 4.0))
player['wf_Jumping Acceleration']  = 5.0          # a small hop, not a platformer jump
player['wf_Falling Acceleration']  = 9.81
player['wf_Air Acceleration']      = 0.0
player['wf_Max Air Speed']         = 4.0
player['wf_Horiz Air Drag']        = 1.5
player['wf_Turn Rate']             = 0.0          # LEFT/RIGHT strafe (doom-stick), no rotation
player['wf_Script Controls Input'] = 'True'

JOY_UP, JOY_DOWN, JOY_RIGHT, JOY_LEFT = 1 << 11, 1 << 12, 1 << 13, 1 << 14   # hal/sjoystic.h EJ_BUTTONB_*
MB_LEG, MB_HOLD_UNTIL, MB_DONE = 500, 501, 502   # global user mailboxes (2–999, shared)


def tour_forth(tour):
    """Compile the waypoint list into a per-tick zForth state machine.

    Global mailbox 500 holds the current leg. A move leg is a *servo*: it pushes
    the player toward the waypoint coordinate from either side (joystick bits by
    sign of the error) and advances only when the error is within `tol_m` AND the
    player's speed along that axis (X/YSPEED mailboxes) is below `stop_speed` —
    so momentum can never carry him past a doorway into a jamb (which "complete
    once past the target" did, run-dependently). A labelled waypoint adds a hold
    leg (bits 0) timed on INDEXOF_TIME via mailbox 501. The last leg sets mailbox
    502 = 1 so a recorder knows the tour is over. Position-based → replays the
    same at any frame rate.
    """
    hold = float(tour.get('hold_seconds', 0.5))
    tol = float(tour.get('tol_m', 0.12))
    stop_speed = float(tour.get('stop_speed', 0.4))
    legs = []                                   # (bits, axis, target, label)  bits = "+" direction bits
    px, py = tour['spawn'][0], tour['spawn'][1]
    for wp in tour['waypoints']:
        x, y = wp['at']
        dx, dy = x - px, y - py
        assert (abs(dx) < 1e-6) != (abs(dy) < 1e-6), f"leg to {wp['at']} must be axis-aligned (from {px, py})"
        legs.append(('X', x, None) if abs(dx) > 1e-6 else ('Y', y, None))
        if wp.get('room'):
            legs.append(('HOLD', float(wp.get('hold', hold)), wp['room']))   # per-waypoint `hold` overrides hold_seconds
        px, py = x, y
    lines = ["\\ wf", f"{MB_LEG} read-mailbox"]          # ( leg )
    for k, (kind, val, label) in enumerate(legs):
        nxt = k + 1
        if kind in ('X', 'Y'):
            pos_mb, spd_mb = (f'INDEXOF_{kind}_POS', f'INDEXOF_{kind}SPEED')
            plus, minus = (JOY_RIGHT, JOY_LEFT) if kind == 'X' else (JOY_UP, JOY_DOWN)
            # ( leg ) → err = pos − target; err > tol → push minus; err < −tol → push plus;
            # else stop, and advance once |speed| < stop_speed.
            lines.append(
                f"dup {k} = if {pos_mb} read-mailbox {val} - "
                f"dup {tol} > if drop {minus} INDEXOF_INPUT write-mailbox else "
                f"dup {-tol} < if drop {plus} INDEXOF_INPUT write-mailbox else "
                f"drop 0 INDEXOF_INPUT write-mailbox "
                f"{spd_mb} read-mailbox abs {stop_speed} < if drop {nxt} dup {MB_LEG} write-mailbox then "
                f"then then then")
        else:   # hold `val` seconds at the labelled room
            lines.append(
                f"dup {k} = if 0 INDEXOF_INPUT write-mailbox "
                f"{MB_HOLD_UNTIL} read-mailbox 0 = if INDEXOF_TIME read-mailbox {val} + {MB_HOLD_UNTIL} write-mailbox then "
                f"INDEXOF_TIME read-mailbox {MB_HOLD_UNTIL} read-mailbox >= if "
                f"0 {MB_HOLD_UNTIL} write-mailbox drop {nxt} dup {MB_LEG} write-mailbox then then")
    lines.append(f"dup {len(legs)} = if 0 INDEXOF_INPUT write-mailbox 1 {MB_DONE} write-mailbox then")
    lines.append("drop")
    return "\n".join(lines) + "\n", legs


if TOUR:
    _script, _legs = tour_forth(TOUR)
    player['wf_Script'] = _script
    player['wf_Falling Acceleration'] = 9.81
    print(f"[condo] tour: {len(_legs)} legs, {sum(1 for l in _legs if l[2])} room holds, "
          f"{len(_script)} bytes of Forth")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, LEVEL_NAME + '.legs.json'), 'w') as _f:
        json.dump([{'leg': i, 'kind': kind, 'target': val, 'room': lab} for i, (kind, val, lab) in enumerate(_legs)], _f, indent=1)
else:
    player['wf_Script'] = (
        "\\ wf\n"
        "INDEXOF_HARDWARE_JOYSTICK1_RAW read-mailbox INDEXOF_INPUT write-mailbox\n"
    )

# ── 7. Camera rig: relative doll-house shot ──────────────────────────────────
# BungeeCam: position = (camshot − Follow) + TrackObject; look-at = (Target − Follow)
# + TrackObject (movecam.cc SetCameraParametersFromShot / BungeeCameraHandler::update).
# With Follow = CamTarget at the origin the camshot's own position IS the offset.
target_proto.location = (0.0, 0.0, 0.0)
target_proto['wf_Model Type'] = 'None'
look_at = target_proto.copy()
look_at.data = None
look_at.name = 'LookAt'
look_at.location = LOOK_OFFSET
look_at['wf_Model Type'] = 'None'
scene.collection.objects.link(look_at)

camshot = find_by_class('camshot')
assert camshot is not None
camshot.name = 'cs_dollhouse'
camshot.location = CAM_OFFSET
camshot['wf_Position X'] = 'Relative'
camshot['wf_Position Y'] = 'Relative'
camshot['wf_Position Z'] = 'Relative'
camshot['wf_Rotation']   = 'Fixed'          # 'Track' would spin the offset by the player's heading
camshot['wf_FOV']        = 60.0
camshot['wf_Hither']     = 0.1
camshot['wf_Yon']        = 200.0
camshot['wf_Pan Time In Seconds'] = 0.5
camshot['wf_Model Type']   = 'None'
camshot['wf_Track Object'] = 'Player'
camshot['wf_Target']       = 'LookAt'
camshot['wf_Follow']       = 'CamTarget'

camera = find_by_class('camera')
assert camera is not None
camera.name = 'Camera'
camera.location = tuple(s + o for s, o in zip(PLAYER_SPAWN, CAM_OFFSET))   # start where the shot lands
camera['wf_Model Type'] = 'None'
camera['wf_FoggingColor']            = 0x000000    # indoor: no snowgoons Earth fog
camera['wf_FoggingStartDistance']    = 999.0
camera['wf_FoggingCompleteDistance'] = 1000.0

# ── 7b. Balcony camera: step onto 639's patio and the shot cuts to Bangkok ──────
# Two ActBoxOR zones write their camshot's object index to a mailbox every tick the
# player overlaps them (game/actboxor.cc — it never clears); the Director forwards the
# mailbox to INDEXOF_CAMSHOT and zeroes it. In bungee-cam mode the handler re-reads
# INDEXOF_CAMSHOT each tick and never clears it (movecam.cc BungeeCameraHandler), so
# the last written shot sticks: interior zone → cs_dollhouse, patio zone → cs_balcony.
# The zones are adjacent, not overlapping; the Director reads the patio's mailbox last
# so it wins on a boundary tick.
#
# cs_balcony is the player's POV: Relative offset (0, 1.5, 1.7) — 1.5 m ahead of the player
# at eye height, which on the patio puts the camera just past the pony wall in free air.
# That matters because the camera is a physics body that climbs whenever its bbox overlaps a
# collidable actor (BungeeCameraHandler ClimbRate): inside the patio it would hit the player
# or the walls and sail upward. movecam.cc SetCameraParametersFromShot: position =
# (camshot − Follow) + Player, direction = Target − camshot, both in world space.
MB_ZONE_INTERIOR, MB_ZONE_BALCONY, MB_BALCONY_T0 = 98, 99, 97   # 97: level time the player stepped onto the patio (0 = not there)
BALCONY_ROOMS = ('639-patio', '639-patio-recessed')
_bal = [(mn, mx) for name, mn, mx in room_outlines if name in BALCONY_ROOMS]
assert len(_bal) == len(BALCONY_ROOMS), f"balcony outlines missing: {[n for n, _, _ in room_outlines]}"
bal_min = Vector((min(mn.x for mn, _ in _bal), min(mn.y for mn, _ in _bal), 0.0))
bal_max = Vector((max(mx.x for _, mx in _bal), max(mx.y for _, mx in _bal), WALL_H))
BALCONY_CAM     = (0.0, 1.5, 1.7)       # POV: offset from the player — eye height, past the pony wall
BALCONY_LOOK0   = (-6.0, 9.5, -0.3)     # sweep start (world, relative to CamTarget): south-west, 14° down — the street
BALCONY_LOOK1   = (6.0, 9.5, 2.7)       # sweep end: north-west, 7° up — the towers and the sky
BALCONY_SWEEP_S = 5.0                   # the pan takes this long, then holds (tour patio holds add the same 5 s)


def add_locator(name, location, bbox_min=None, bbox_max=None):
    """target-class locator (no mesh, no Jolt body); an authored bbox makes it a zone."""
    o = target_proto.copy()
    o.data = None
    o.name = name
    o.location = location
    o.rotation_euler = (0.0, 0.0, 0.0)
    o.scale = (1.0, 1.0, 1.0)
    o['wf_Model Type'] = 'None'
    o['wf_original_mesh_name'] = ''
    if bbox_min is not None:
        half = (bbox_max - bbox_min) / 2.0
        o['wf_original_bbox'] = (-half.x, -half.y, -half.z, half.x, half.y, half.z)
        o['wf_had_authored_bbox'] = True
    scene.collection.objects.link(o)
    return o


# The look target is a scripted platform (the moon's launch_tracker pattern): while the
# player is on the patio it slides from LOOK0 to LOOK1 over BALCONY_SWEEP_S, timed from
# mailbox 97 (set by the Director on entry, zeroed on exit), so every visit tilts up from
# the balcony to the skyline. Writes world Y/Z through its own INDEXOF_Y_POS / Z_POS.
balcony_look = bpy.data.objects.new('BalconyLook', bpy.data.meshes.new('BalconyLook'))
scene.collection.objects.link(balcony_look)
attach_schema(balcony_look, 'platform')
balcony_look.location = BALCONY_LOOK0
balcony_look['wf_Mobility']   = 'Anchored'
balcony_look['wf_Model Type'] = 'None'
balcony_look['wf_Mass']       = 0.0
_lx0, _lz0 = BALCONY_LOOK0[0], BALCONY_LOOK0[2] + UNIT_Z
_lx1, _lz1 = BALCONY_LOOK1[0], BALCONY_LOOK1[2] + UNIT_Z
balcony_look['wf_Script'] = (
    "\\ wf\n"
    f"{MB_BALCONY_T0} read-mailbox dup 0 <> if INDEXOF_TIME read-mailbox swap - "      # ( elapsed )
    f"dup {BALCONY_SWEEP_S} > if drop {BALCONY_SWEEP_S} then {BALCONY_SWEEP_S} / "     # ( t 0..1 )
    f"dup {_lx1 - _lx0} * {_lx0} + INDEXOF_X_POS write-mailbox "
    f"{_lz1 - _lz0} * {_lz0} + INDEXOF_Z_POS write-mailbox "
    f"else drop {_lx0} INDEXOF_X_POS write-mailbox {_lz0} INDEXOF_Z_POS write-mailbox then\n"
)
cs_balcony = camshot.copy()
cs_balcony.data = None
cs_balcony.name = 'cs_balcony'
cs_balcony.location = BALCONY_CAM
for k in ('wf_Position X', 'wf_Position Y', 'wf_Position Z'):
    cs_balcony[k] = 'Relative'
cs_balcony['wf_Rotation'] = 'Fixed'
cs_balcony['wf_Target']   = 'BalconyLook'
cs_balcony['wf_Follow']   = 'CamTarget'
cs_balcony['wf_Track Object'] = 'Player'
cs_balcony['wf_Pan Time In Seconds'] = 0.7
scene.collection.objects.link(cs_balcony)


def add_zone(name, mn, mx, mailbox, shot_name):
    z = add_locator(name, (mn + mx) / 2.0, mn, mx)
    attach_schema(z, 'actboxor')
    z['wf_MovementClass']      = 17               # Actor::ActBoxOR_KIND (actboxor.cc:67 asserts it; the
                                                  # target prototype carries 3 and the exporter copies it)
    z['wf_Mobility']           = 'Anchored'
    z['wf_MailBox']            = mailbox
    z['wf_Object']             = shot_name
    z['wf_Activated By']       = 'Actor'
    z['wf_Activated By Actor'] = 'Player'
    z['wf_Activated By Class'] = ''
    return z


pad = 0.1
zone_balcony = add_zone('zone-balcony', bal_min - Vector((pad, pad, 0.5)), bal_max + Vector((pad, pad, 0.5)),
                        MB_ZONE_BALCONY, 'cs_balcony')
cx0, cy0, cx1, cy1 = CORRIDOR
zone_interior = add_zone('zone-interior', Vector((min(cx0, -8.2), cy0 - 0.5, -0.5)),
                         Vector((max(cx1, 8.2), bal_min.y - pad, WALL_H + 0.5)),
                         MB_ZONE_INTERIOR, 'cs_dollhouse')
print(f"[condo] balcony camera: zone y {bal_min.y - pad:.2f}…{bal_max.y + pad:.2f}, cs_balcony at {BALCONY_CAM}, "
      f"look {BALCONY_LOOK0} → {BALCONY_LOOK1} over {BALCONY_SWEEP_S} s")

# ── 8. Lights, matte, director, levelobj ─────────────────────────────────────
light = find_by_class('light')
assert light is not None
light.name = 'Sun'
light.location = (0.0, -8.0, 8.0)
light.rotation_euler = (math.pi / 2 - math.radians(SUN_ALT_DEG), 0.0, math.radians(SUN_AZ_DEG))
light['wf_lightType']  = 'Directional'
light['wf_lightRed']   = 1.0
light['wf_lightGreen'] = 1.0
light['wf_lightBlue']  = 0.96
light['wf_Model Type'] = 'None'
ambient = light.copy()
ambient.data = light.data.copy() if light.data else None
scene.collection.objects.link(ambient)
ambient.name = 'AmbientLight'
ambient.location = (0.0, -8.0, 8.0)
ambient['wf_lightType']  = 'Ambient'
ambient['wf_lightRed']   = 0.45
ambient['wf_lightGreen'] = 0.45
ambient['wf_lightBlue']  = 0.50

matte = find_by_class('matte')
assert matte is not None
matte.name = 'Matte'
matte.location = (0.0, -8.0, 14.0)
matte['wf_Matte Type']         = 'Color'
matte['wf_Background Color']   = 0x9FB8D0
matte['wf_Visibility Mailbox'] = 1
matte['wf_Model Type']         = 'None'

director = find_by_class('director')
assert director is not None, "snowgoons scaffold has no director (needed for the camera zones)"
director.name = 'Director'
director['wf_Model Type'] = 'None'
# Camera-zone multiplexer (replaces snowgoons' 100/99/98 version): forward each zone's
# mailbox to INDEXOF_CAMSHOT and zero it, patio last so it wins on a boundary tick.
# Mailbox 97 holds the level time the patio zone was entered (for BalconyLook's sweep) and
# is zeroed the first tick the zone stops writing.
director['wf_Script'] = (
    "\\ wf\n"
    f"{MB_ZONE_INTERIOR} read-mailbox dup 0 <> if INDEXOF_CAMSHOT write-mailbox 0 {MB_ZONE_INTERIOR} write-mailbox else drop then\n"
    f"{MB_ZONE_BALCONY} read-mailbox dup 0 <> if INDEXOF_CAMSHOT write-mailbox 0 {MB_ZONE_BALCONY} write-mailbox "
    f"{MB_BALCONY_T0} read-mailbox 0 = if INDEXOF_TIME read-mailbox {MB_BALCONY_T0} write-mailbox then "
    f"else drop 0 {MB_BALCONY_T0} write-mailbox then\n"
)

levelobj = find_by_class('levelobj')
assert levelobj is not None
levelobj.name = 'Level'
levelobj['wf_Num Mailboxes'] = NUM_MAILBOXES
levelobj['wf_Model Type'] = 'None'

# ── 9. Room bounds ───────────────────────────────────────────────────────────
room = find_by_class('room')
assert room is not None
room.name = 'room_condo'
room.location = ROOM_CENTRE
hx, hy, hz = ROOM_HALF
rel = (-hx, -hy, -hz, hx, hy, hz)
room['wf_original_bbox'] = rel
rv = [(rel[0], rel[1], rel[2]), (rel[3], rel[1], rel[2]), (rel[3], rel[4], rel[2]), (rel[0], rel[4], rel[2]),
      (rel[0], rel[1], rel[5]), (rel[3], rel[1], rel[5]), (rel[3], rel[4], rel[5]), (rel[0], rel[4], rel[5])]
rf = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
rmesh = bpy.data.meshes.new('RoomBounds')
rmesh.from_pydata(rv, [], rf)
rmesh.update()
old = room.data
room.data = rmesh
if old and old.users == 0:
    bpy.data.meshes.remove(old)
# The room mesh is only a bbox visualisation: hide it (eye off) and draw it as wire
# so it never occludes the level in the saved .blend. The exporter writes it anyway.
room.display_type = 'WIRE'
room.hide_render = True
room.hide_set(True)
# Other non-rendering infrastructure draws as wire too (level-building.md § Blender
# Viewport Display by Object Type).
for o in scene.objects:
    if o.get('wf_schema_path') and get_class(o) in ('camera', 'camshot', 'target', 'light',
                                                    'matte', 'levelobj', 'director'):
        o.display_type = 'WIRE'

# ── 9b. Lift to the 6th floor ────────────────────────────────────────────────
# Everything above was authored with the unit floor at z = 0 (slab_outline, darken_floors
# and the tour's spawn all assume it); the ground map and the dome are world-space already.
# The camera rig (cs_dollhouse, CamTarget, LookAt) is relative — position = (camshot − Follow)
# + TrackObject — so lifting all three by the same amount changes nothing.
for o in scene.objects:
    if o.get('wf_schema_path') and o.name not in NOT_LIFTED:
        o.location.z += UNIT_Z

# Every actor centre must be strictly inside the room bbox or levcomp drops it
# from the render list (troubleshooting § "falls outside every room bbox").
bpy.context.view_layer.update()          # matrix_world is stale until the depsgraph runs
lo = tuple(c - h + 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
hi = tuple(c + h - 0.05 for c, h in zip(ROOM_CENTRE, ROOM_HALF))
outside = [o.name for o in scene.objects
           if o.get('wf_schema_path') and get_class(o) != 'room'
           and not all(lo[i] < o.matrix_world.to_translation()[i] < hi[i] for i in range(3))]
assert not outside, f"actors outside room bbox {lo}..{hi}: {outside}"

# ── 10. Export ───────────────────────────────────────────────────────────────
wf_objects = [o for o in scene.objects if o.get('wf_schema_path')]
os.makedirs(OUT_DIR, exist_ok=True)
_wrapper = os.path.join(OUT_DIR, LEVEL_NAME + '-standalone.iff.txt')
if LEVEL_NAME != 'condo_639_640':
    if not os.path.exists(_wrapper):
        with open(os.path.join(SCRIPT_DIR, 'condo_639_640-standalone.iff.txt')) as _src, open(_wrapper, 'w') as _dst:
            _dst.write(_src.read().replace('condo_639_640', LEVEL_NAME))
    # textile-rs reads textures and textile.flags from the level dir, so a derived build
    # (the tour) gets fresh copies of the site textures every run.
    import shutil
    for _f in ('condo_ground.tga', 'condo_sky.tga', 'textile.flags'):
        shutil.copyfile(os.path.join(SCRIPT_DIR, _f), os.path.join(OUT_DIR, _f))
bpy.ops.wm.save_as_mainfile(filepath=OUT_BLEND)
print(f"[condo] saved assembled scene → {OUT_BLEND}")
print(f"[condo] exporting {len(wf_objects)} actors → {OUT_LEV}")
bpy.ops.wf.export_level(filepath=OUT_LEV)
print("[condo] done:", stats)
