// scripting_stub.cc — Lua 5.4 ScriptInterpreter for Linux builds
//
// Replaces scripting/scriptinterpreter.cc and scripting/tcl.cc entirely.
// Provides LuaInterpreter, exposing read_mailbox/write_mailbox as Lua C
// functions and the full INDEXOF_* / JOYSTICK_BUTTON_* constant namespace
// as Lua globals. A NullInterpreter is kept as a fallback for when scripts
// need to be silenced.

#include <scripting/scriptinterpreter.hp>
#include <math/scalar.hp>
#include "scripting_js.hp"
#include "scripting_wasm3.hp"

extern "C" {
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
}

#include <cstdio>

//=============================================================================
// Base-class implementations (formerly in scripting/scriptinterpreter.cc)

ScriptInterpreter::ScriptInterpreter(MailboxesManager& manager)
    : _mailboxesManager(manager)
{
}

ScriptInterpreter::~ScriptInterpreter()
{
}

void ScriptInterpreter::Validate()
{
}

void ScriptInterpreter::AddConstantArray(IntArrayEntry* /*entryList*/)
{
}

void ScriptInterpreter::DeleteConstantArray(IntArrayEntry* /*entryList*/)
{
}

//=============================================================================
// NullInterpreter — no-op fallback.

class NullInterpreter : public ScriptInterpreter
{
public:
    NullInterpreter(MailboxesManager& mgr) : ScriptInterpreter(mgr) {}
    ~NullInterpreter() {}

    Scalar RunScript(const void* /*script*/, int /*objectIndex*/) override
    {
        return Scalar::FromFloat(0.0f);
    }
};

//=============================================================================
// Mailbox name constants — same set TCL exposed, built from mailbox.inc plus
// a hardcoded joystick table (the joystick values live nowhere else).

static IntArrayEntry mailboxIndexArray[] =
{
#define Comment(val)
#define MAILBOXENTRY(name,value)  { "INDEXOF_" #name, value },
#include <mailbox/mailbox.inc>
    { NULL, 0 }
};
#undef MAILBOXENTRY
#undef Comment

static IntArrayEntry joystickArray[] =
{
    { "JOYSTICK_BUTTON_UP",    2048 },
    { "JOYSTICK_BUTTON_DOWN",  4096 },
    { "JOYSTICK_BUTTON_RIGHT", 8192 },
    { "JOYSTICK_BUTTON_LEFT",  16384 },
    { "JOYSTICK_BUTTON_A", 1 },
    { "JOYSTICK_BUTTON_B", 2 },
    { "JOYSTICK_BUTTON_C", 4 },
    { "JOYSTICK_BUTTON_D", 8 },
    { "JOYSTICK_BUTTON_E", 16 },
    { "JOYSTICK_BUTTON_F", 32 },
    { "JOYSTICK_BUTTON_G", 64 },
    { "JOYSTICK_BUTTON_H", 128 },
    { "JOYSTICK_BUTTON_I", 256 },
    { "JOYSTICK_BUTTON_J", 512 },
    { "JOYSTICK_BUTTON_K", 1024 },
    { NULL, 0 }
};

//=============================================================================
// LuaInterpreter

class LuaInterpreter : public ScriptInterpreter
{
public:
    LuaInterpreter(MailboxesManager& mgr);
    ~LuaInterpreter() override;

    Scalar RunScript(const void* script, int objectIndex) override;
    void   AddConstantArray(IntArrayEntry* entryList) override;
    void   DeleteConstantArray(IntArrayEntry* entryList) override;

    // exposed for the C closures
    MailboxesManager& mailboxes() { return _mailboxesManager; }
    int               currentObject() const { return _currentObjectIndex; }

private:
    lua_State* _L;
    int        _currentObjectIndex;
    int        _fennelEvalRef;  // LUA_REGISTRYINDEX ref to fennel.eval, or LUA_NOREF
};

// Recover the interpreter pointer from the C closure's first upvalue.
static inline LuaInterpreter* self(lua_State* L)
{
    return static_cast<LuaInterpreter*>(lua_touserdata(L, lua_upvalueindex(1)));
}

static int lua_read_mailbox(lua_State* L)
{
    LuaInterpreter* THIS = self(L);
    long mailbox  = static_cast<long>(luaL_checkinteger(L, 1));
    int  actorIdx = THIS->currentObject();
    if (lua_gettop(L) >= 2) {
        actorIdx = static_cast<int>(luaL_checkinteger(L, 2));
    }
    Mailboxes& mb = THIS->mailboxes().LookupMailboxes(actorIdx);
    Scalar v = mb.ReadMailbox(mailbox);
    std::fprintf(stderr, "  lua read_mailbox(%ld, actor=%d) -> %g\n",
                 mailbox, actorIdx, (double)v.AsFloat());
    lua_pushnumber(L, v.AsFloat());
    return 1;
}

static int lua_write_mailbox(lua_State* L)
{
    LuaInterpreter* THIS = self(L);
    long   mailbox  = static_cast<long>(luaL_checkinteger(L, 1));
    double value    = luaL_checknumber(L, 2);
    int    actorIdx = THIS->currentObject();
    if (lua_gettop(L) >= 3) {
        actorIdx = static_cast<int>(luaL_checkinteger(L, 3));
    }
    Mailboxes& mb = THIS->mailboxes().LookupMailboxes(actorIdx);
    std::fprintf(stderr, "  lua write_mailbox(%ld, %g, actor=%d)\n",
                 mailbox, value, actorIdx);
    mb.WriteMailbox(mailbox, Scalar::FromFloat(static_cast<float>(value)));
    return 0;
}

static void register_closure(lua_State* L, LuaInterpreter* self,
                             const char* name, lua_CFunction fn)
{
    lua_pushlightuserdata(L, self);
    lua_pushcclosure(L, fn, 1);
    lua_setglobal(L, name);
}

#ifdef WF_ENABLE_FENNEL
// Generated by build_game.sh from wftools/wf_viewer/stubs/fennel.lua
// (minified via scripts/minify_lua.py, then xxd -i'd into fennel_source.cc).
extern "C" const char kFennelSource[];
extern "C" const unsigned int kFennelSourceLen;
#endif

LuaInterpreter::LuaInterpreter(MailboxesManager& mgr)
    : ScriptInterpreter(mgr),
      _L(luaL_newstate()),
      _currentObjectIndex(0),
      _fennelEvalRef(LUA_NOREF)
{
    luaL_openlibs(_L);

    // Primary API. Lua identifiers forbid hyphens, so underscores.
    register_closure(_L, this, "read_mailbox",  lua_read_mailbox);
    register_closure(_L, this, "write_mailbox", lua_write_mailbox);

#ifdef WF_WITH_JS
    // JS runtime must be live before AddConstantArray (which forwards to JS).
    JsRuntimeInit(mgr);
#endif

#ifdef WF_WITH_WASM
    Wasm3RuntimeInit(mgr);
#endif

    AddConstantArray(mailboxIndexArray);
    AddConstantArray(joystickArray);

#ifdef WF_ENABLE_FENNEL
    // Compile-and-run the embedded fennel.lua, then stash fennel.eval in
    // the Lua registry so RunScript can reach it without a global lookup
    // per script run. Failure is non-fatal: ;-prefixed scripts will fall
    // through to the Lua path and surface as Lua syntax errors.
    if (luaL_loadbuffer(_L, kFennelSource, kFennelSourceLen, "fennel.lua") != LUA_OK
        || lua_pcall(_L, 0, 1, 0) != LUA_OK) {
        std::fprintf(stderr, "fennel: load failed: %s\n", lua_tostring(_L, -1));
        lua_pop(_L, 1);
    } else {
        lua_getfield(_L, -1, "eval");
        _fennelEvalRef = luaL_ref(_L, LUA_REGISTRYINDEX);
        lua_pop(_L, 1);  // pop fennel module
        std::fprintf(stderr, "fennel: loaded (%u bytes embedded)\n", kFennelSourceLen);
    }
#endif
}

LuaInterpreter::~LuaInterpreter()
{
#ifdef WF_WITH_JS
    JsRuntimeShutdown();
#endif
#ifdef WF_WITH_WASM
    Wasm3RuntimeShutdown();
#endif
    if (_L) {
        lua_close(_L);
        _L = nullptr;
    }
}

void LuaInterpreter::AddConstantArray(IntArrayEntry* entryList)
{
    IntArrayEntry* p = entryList;
    while (p->name) {
        lua_pushinteger(_L, p->value);
        lua_setglobal(_L, p->name);
        p++;
    }
#ifdef WF_WITH_JS
    JsAddConstantArray(entryList);
#endif
#ifdef WF_WITH_WASM
    Wasm3AddConstantArray(entryList);
#endif
}

void LuaInterpreter::DeleteConstantArray(IntArrayEntry* entryList)
{
    IntArrayEntry* p = entryList;
    while (p->name) {
        lua_pushnil(_L);
        lua_setglobal(_L, p->name);
        p++;
    }
#ifdef WF_WITH_JS
    JsDeleteConstantArray(entryList);
#endif
#ifdef WF_WITH_WASM
    Wasm3DeleteConstantArray(entryList);
#endif
}

Scalar LuaInterpreter::RunScript(const void* script, int objectIndex)
{
    _currentObjectIndex = objectIndex;
    const char* src = static_cast<const char*>(script);
    if (!src || !*src) {
        return Scalar::FromFloat(0.0f);
    }

#ifdef WF_WITH_JS
    // Leading `//` (after optional whitespace) routes to JavaScript. `//` is a
    // Lua syntax error (integer-division needs operands) so Lua can't mistake
    // a JS comment for its own code.
    {
        const char* p = src;
        while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
        if (p[0] == '/' && p[1] == '/') {
            return Scalar::FromFloat(JsRunScript(src, objectIndex));
        }
    }
#endif

#ifdef WF_WITH_WASM
    // Routes to wasm3 only for the full `#b64\n` marker. We don't claim
    // every `#`-prefixed script because cd.iff ships TCL shell fragments
    // that use `##` as a line comment; those still need to fall through
    // to the next language so behaviour matches pre-wasm builds.
    {
        const char* p = src;
        while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
        if (p[0] == '#' && p[1] == 'b' && p[2] == '6' && p[3] == '4'
            && p[4] == '\n') {
            return Scalar::FromFloat(Wasm3RunScript(src, objectIndex));
        }
    }
#endif

#ifdef WF_ENABLE_FENNEL
    // Leading `;` (after optional whitespace) routes to Fennel. `;` is a
    // Lisp comment and a Lua syntax error, so the discriminator is
    // unambiguous with zero markup overhead in level sources.
    if (_fennelEvalRef != LUA_NOREF) {
        const char* p = src;
        while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
        if (*p == ';') {
            lua_rawgeti(_L, LUA_REGISTRYINDEX, _fennelEvalRef);  // fennel.eval
            lua_pushstring(_L, src);
            if (lua_pcall(_L, 1, 1, 0) != LUA_OK) {
                std::fprintf(stderr, "fennel error: %s\n  script: %s\n",
                             lua_tostring(_L, -1), src);
                lua_pop(_L, 1);
                return Scalar::FromFloat(0.0f);
            }
            double result = lua_isnumber(_L, -1) ? lua_tonumber(_L, -1) : 0.0;
            lua_settop(_L, 0);
            return Scalar::FromFloat(static_cast<float>(result));
        }
    }
#endif

    if (luaL_dostring(_L, src) != LUA_OK) {
        const char* err = lua_tostring(_L, -1);
        std::fprintf(stderr, "lua error: %s\n", err ? err : "(unknown)");
        std::fprintf(stderr, "  script: %s\n", src);
        lua_pop(_L, 1);
        return Scalar::FromFloat(0.0f);
    }

    double result = 0.0;
    if (lua_gettop(_L) > 0 && lua_isnumber(_L, -1)) {
        result = lua_tonumber(_L, -1);
    }
    lua_settop(_L, 0);
    return Scalar::FromFloat(static_cast<float>(result));
}

//=============================================================================

ScriptInterpreter* ScriptInterpreterFactory(MailboxesManager& mailboxesManager, Memory& memory)
{
    return new (memory) LuaInterpreter(mailboxesManager);
}
