from pathlib import Path
import markdown
p=Path(__file__).resolve().parents[1]/'implementation-plan.md'
body=markdown.markdown(p.read_text(),extensions=['tables','fenced_code'])
css='''*{box-sizing:border-box}body{font:17px/1.65 system-ui,sans-serif;color:#243b45;background:#eeeae1;margin:0}main{overflow-wrap:anywhere;max-width:1180px;margin:28px auto;padding:48px;background:#fffdf8;border-radius:16px}h1,h2,h3{line-height:1.25}h1{font-size:38px;max-width:950px}h2{margin-top:2em;padding-top:20px;border-top:1px solid #ded9ce}h3{margin-top:1.8em}a{color:#226f70}table{border-collapse:collapse;width:100%;font-size:15px}th,td{padding:12px;border:1px solid #d5dace;text-align:left;vertical-align:top}th{background:#eaf0e7}pre{padding:18px;background:#edf4f4;overflow:auto}code{font-size:.9em}img{display:block;width:100%;height:auto;border-radius:12px;border:1px solid #ddd7ca;cursor:zoom-in;box-shadow:0 8px 24px #243b4510}img[src*="phone-placement"]{max-width:360px;margin:auto}main img[src*="phone-placement-landscape"]{width:100%;max-width:737px;margin:auto}button{font:inherit;cursor:pointer;padding:10px 16px;border:1px solid #b9ccc1;border-radius:8px;background:#fffdf8;color:#243b45}button[aria-pressed="true"]{background:#287c78;color:white}button:focus-visible,a:focus-visible{outline:3px solid #edb84f;outline-offset:4px}.demo{padding:24px;background:#f0f3e9;border-radius:14px;margin:22px 0}.demo nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.demo svg{width:100%;height:auto}.demo p{margin:10px 0 0}.banner{font-size:14px;letter-spacing:.05em;color:#287c78;font-weight:700}dialog{max-width:96vw;width:1400px;padding:18px;border:0;border-radius:12px;background:#fffdf8}dialog::backdrop{background:#162d39cc}dialog img{max-height:82vh;width:100%;object-fit:contain;box-shadow:none;border:0;cursor:default}dialog button{float:right;margin-bottom:10px}@media(max-width:700px){main{margin:0;padding:20px;border-radius:0}h1{font-size:29px}table{display:block;overflow-x:auto}}@media print{main{margin:0;padding:0}img{box-shadow:none}.demo{break-inside:avoid}dialog{display:none}}'''
# Self-contained illustration for interactive scoring, with historical occupancy.
grid=''.join(f'<rect id="c{r}-{c}" x="{35+c*31}" y="{42+r*31}" width="29" height="29" rx="3" fill="#eee9dc"/>' for r in range(9) for c in range(9))
demo='''<section class="demo" aria-label="Score-counting presentation prototype"><h3>Try the TV score reveal</h3><p>Presentation prototype only. Step through one player's saved round quilts and final deduction.</p><nav aria-label="Scoring steps">'''+''.join(f'<button type="button" data-step="{i}" aria-pressed="{str(i==0).lower()}">{s}</button>' for i,s in enumerate(['Round 1','Round 2','Round 3','Empty cells','Final total']))+'''</nav><svg viewBox="0 0 1050 360" role="img" aria-labelledby="scoreTitle"><title id="scoreTitle">Maya's score-counting walkthrough</title>'''+grid+'''<rect id="square" fill="none" stroke="#edb84f" stroke-width="4"/><rect id="strip" fill="none" stroke="#c87360" stroke-width="4"/><text x="360" y="86" font-family="system-ui" font-size="27" font-weight="700" fill="#243b45" id="stepTitle"></text><text x="360" y="136" font-family="system-ui" font-size="22" fill="#287c78" id="arithmetic"></text><text x="360" y="225" font-family="system-ui" font-size="18" fill="#637875" id="explanation"></text><text x="360" y="295" font-family="system-ui" font-size="39" font-weight="700" fill="#243b45" id="running"></text></svg><p aria-live="polite" id="stepCaption"></p></section>'''
needle='<h2>Design diagrams</h2>'
assert needle in body
body=body.replace(needle,demo+needle)
js='''const steps=[{w:3,h:3,title:'Maya · Round 1',math:'3 × 3 = 9',note:'Use the saved first-round quilt.',running:'Round 1: 9',cap:'The first saved quilt scores a 3 by 3 square: 9 points.'},{w:5,h:4,title:'Maya · Round 2',math:'4 × 4 + 1 extra column = 17',note:'Use the saved second-round quilt.',running:'Subtotal: 9 + 17 = 26',cap:'The second saved quilt scores a 4 by 5 rectangle: 17 points.'},{w:7,h:6,title:'Maya · Round 3',math:'6 × 6 + 1 extra column = 37',note:'Gold outlines the square; coral outlines the extra column.',running:'Subtotal: 9 + 17 + 37 = 63',cap:'The third round scores a 6 by 7 rectangle: 37 points.'},{w:7,h:6,title:'Maya · Count empty cells',math:'81 cells − 45 filled = 36 empty',note:'Empty cells are outlined in coral. Deduct one point each.',running:'63 − 36',cap:'The final quilt has 45 filled cells and 36 empty cells. Deduct 36.'},{w:7,h:6,title:'Maya · Final total',math:'9 + 17 + 37 − 36 = 27',note:'Next: count the next quilt, then reveal shared standings.',running:'27 points',cap:'Maya finishes with 27 points. Continue to the next player.'}];function setStep(i){const s=steps[i];for(let r=0;r<9;r++)for(let c=0;c<9;c++){const el=document.getElementById(`c${r}-${c}`),filled=(r<s.h&&c<s.w)||(i>=2&&r===8&&c<3);el.setAttribute('fill',filled?'#287c78':'#eee9dc');el.setAttribute('stroke',i===3&&!filled?'#c87360':'none');}const q=Math.min(s.w,s.h),square=document.getElementById('square'),strip=document.getElementById('strip');for(const [key,v]of Object.entries({x:33,y:40,width:q*31,height:q*31}))square.setAttribute(key,v);square.style.display=i<3?'':'none';for(const [key,v]of Object.entries({x:33+q*31,y:40,width:(s.w-q)*31,height:s.h*31}))strip.setAttribute(key,v);strip.style.display=i===1||i===2?'':'none';for(const [id,val]of Object.entries({stepTitle:s.title,arithmetic:s.math,explanation:s.note,running:s.running,stepCaption:s.cap}))document.getElementById(id).textContent=val;document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.step)===i));}document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>setStep(Number(b.dataset.step))));setStep(0);const modal=document.getElementById('enlarge');document.querySelectorAll('main img').forEach(img=>{img.tabIndex=0;img.setAttribute('aria-label',img.alt+'; activate to enlarge');const show=()=>{document.getElementById('fullImage').src=img.src;document.getElementById('fullImage').alt=img.alt;modal.showModal();};img.addEventListener('click',show);img.addEventListener('keydown',e=>{if(e.key==='Enter'){show();}});});document.getElementById('closeImage').addEventListener('click',()=>modal.close());'''
p.with_suffix('.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Patchwork Doodle · Visual implementation plan</title><style>'+css+'</style></head><body><main><div class="banner">PLAYABLE BROWSER PROTOTYPE · PHYSICAL CAST VALIDATION PENDING</div>'+body+'</main><dialog id="enlarge"><button id="closeImage">Close</button><img id="fullImage" alt=""></dialog><script>'+js+'</script></body></html>')
print(p.with_suffix('.html'))
