#!/usr/bin/env python3
"""gen-qr-logo.py: the World Foundry logo as pixel grids for the centre of the phone-controller QR code.

Reads the World Foundry logo, ../worldfoundry.org/src/assets/wflogo.png next to this repository (108 x 133: the word
WORLD in a black strip along the top, FOUNDRY in a black strip down the right, a red square where they meet, and the
picture of planets and the foundry), and writes wfsource/source/hal/phonepad/phonepad_logo.h with two grids that the
TV overlay (phonepad_overlay.cc) draws as coloured rectangles over the code:

  full    the whole logo
  planet  the picture alone: the WORLD and FOUNDRY strips cropped off, as a square from the top of the picture

How the strips are found (deterministic, from the pixels, no hand-entered coordinates): a pixel is "black" when
R + G + B < 120. The top strip ends at the first row, below a fully black row, whose left 3/4 is less than 20 % black;
the right strip starts at the first column right of the middle that is more than 90 % black below the top strip.
The picture is everything left of and below those; the planet square is its full width, from its top row down.

Both grids are halved with a 2 x 2 box mean and each cell is mapped to the nearest colour already in the logo, so no
new colours appear and the result is plain integer arithmetic (no resampler whose output could change with Pillow).

Usage:
  scripts/gen-qr-logo.py                 # write the header (task gen-qr-logo)
  scripts/gen-qr-logo.py --check         # exit 1 if the committed header differs from a fresh one
  scripts/gen-qr-logo.py --logo PNG --out HEADER
  -h, --help
"""
import argparse
import hashlib
import pathlib
import sys

from PIL import Image

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_LOGO = REPO.parent / "worldfoundry.org" / "src" / "assets" / "wflogo.png"
DEFAULT_OUT = REPO / "wfsource" / "source" / "hal" / "phonepad" / "phonepad_logo.h"


def is_black(p):
    return p[0] + p[1] + p[2] < 120


def find_strips(px, w, h):
    """(first picture row, first column of the right strip)."""
    left = (w * 3) // 4
    seen_black_row = False
    top = None
    for y in range(h):
        frac = sum(is_black(px[x, y]) for x in range(left)) / left
        if frac == 1.0:
            seen_black_row = True
        elif seen_black_row and frac < 0.2:
            top = y
            break
    if top is None:
        sys.exit("gen-qr-logo: no top strip found (the logo changed?)")
    right = None
    for x in range(w // 2, w):
        if sum(is_black(px[x, y]) for y in range(top, h)) / (h - top) > 0.9:
            right = x
            break
    if right is None:
        sys.exit("gen-qr-logo: no right strip found (the logo changed?)")
    return top, right


def halve(px, x0, y0, w, h, palette):
    """2 x 2 box mean of the w x h block at (x0, y0), each cell snapped to the nearest palette colour."""
    cells = []
    for y in range(h // 2):
        row = []
        for x in range(w // 2):
            ps = [px[x0 + 2 * x + i, y0 + 2 * y + j] for i in (0, 1) for j in (0, 1)]
            mean = [sum(p[c] for p in ps) / 4 for c in range(3)]
            row.append(min(range(len(palette)), key=lambda k: (sum((palette[k][c] - mean[c]) ** 2 for c in range(3)), k)))
        cells.append(row)
    return cells


def build(logo):
    data = pathlib.Path(logo).read_bytes()
    im = Image.open(logo).convert("RGB")
    w, h = im.size
    px = im.load()
    palette = sorted({px[x, y] for x in range(w) for y in range(h)})
    top, right = find_strips(px, w, h)
    full = halve(px, 0, 0, w, h, palette)
    side = right                                       # the picture's full width (its left black edge included)
    planet = halve(px, 0, top, side, min(side, h - top), palette)
    used = sorted({c for g in (full, planet) for row in g for c in row})
    remap = {old: new for new, old in enumerate(used)}
    full = [[remap[c] for c in row] for row in full]
    planet = [[remap[c] for c in row] for row in planet]
    pal = [palette[c] for c in used]

    def grid(name, g):
        lines = [f"constexpr int k{name}W = {len(g[0])}, k{name}H = {len(g)};",
                 f"constexpr uint8_t k{name}[k{name}W * k{name}H] = {{"]
        lines += ["    " + ",".join(f"{c:2d}" for c in row) + "," for row in g]
        lines.append("};")
        return "\n".join(lines)

    try:
        rel = pathlib.Path(logo).resolve().relative_to(REPO.parent)
        src = f"../{rel}"
    except ValueError:
        src = str(logo)
    return f"""// GENERATED by scripts/gen-qr-logo.py (task gen-qr-logo); do not edit by hand.
// Source: {src} ({w} x {h}), sha256 {hashlib.sha256(data).hexdigest()}
// Strips found: WORLD is rows 0..{top - 1}, FOUNDRY is columns {right}..{w - 1}; the planet square is
// columns 0..{side - 1}, rows {top}..{top + min(side, h - top) - 1}. Both grids are halved (2 x 2 box mean, nearest logo colour).
// Drawn by phonepad_overlay.cc in the middle of the phone-controller QR code (docs/plans/2026-09-30-aquarium-chromecast.md).

#ifndef HAL_PHONEPAD_PHONEPAD_LOGO_H
#define HAL_PHONEPAD_PHONEPAD_LOGO_H

#include <cstdint>

namespace phonepad
{{
namespace logo
{{

// 0xRRGGBBAA
constexpr uint32_t kPalette[{len(pal)}] = {{
    {", ".join(f"0x{r:02X}{g:02X}{b:02X}FFu" for r, g, b in pal)}
}};

// The whole logo.
{grid("Full", full)}

// The picture only (no WORLD / FOUNDRY strips), square.
{grid("Planet", planet)}

}}  // namespace logo
}}  // namespace phonepad

#endif  // HAL_PHONEPAD_PHONEPAD_LOGO_H
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--logo", default=str(DEFAULT_LOGO))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--check", action="store_true", help="compare with the committed header instead of writing")
    a = ap.parse_args()
    if not pathlib.Path(a.logo).exists():
        sys.exit(f"gen-qr-logo: {a.logo} not found (the worldfoundry.org checkout sits next to this repository)")
    text = build(a.logo)
    out = pathlib.Path(a.out)
    if a.check:
        if not out.exists() or out.read_text() != text:
            sys.exit(f"gen-qr-logo: {out} is stale; run task gen-qr-logo")
        print(f"gen-qr-logo: {out} is up to date")
        return
    out.write_text(text)
    print(f"gen-qr-logo: wrote {out}")


if __name__ == "__main__":
    main()
