#!/usr/bin/env python3
"""Extract the existing WF symbol and regenerate the embedded Linux window icon.

Requires Pillow. No generated artwork: the reusable master is an exact crop.
Run from any directory with: python3 scripts/gen-window-icon.py
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets/branding"
# Pillow crop coordinates: left/top inclusive, right/bottom exclusive.
# Remove WORLD above and FOUNDRY to the right, retaining the artwork edge.
CROP = (3, 24, 83, 130)
SIZES = (16, 32, 48, 64, 128)


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    mark = Image.open(ROOT / "wflogo.png").convert("RGBA").crop(CROP)
    mark.save(ASSETS / "world-foundry-mark.png")
    words = []
    for size in SIZES:
        scale = size / max(mark.size)
        scaled = mark.resize((round(mark.width * scale), round(mark.height * scale)),
                             Image.Resampling.LANCZOS)
        icon = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        icon.paste(scaled, ((size - scaled.width) // 2, (size - scaled.height) // 2))
        icon.save(ASSETS / f"world-foundry-icon-{size}.png")
        words.extend((size, size))
        rgba = icon.tobytes()
        words.extend((rgba[i + 3] << 24) | (rgba[i] << 16) |
                     (rgba[i + 1] << 8) | rgba[i + 2]
                     for i in range(0, len(rgba), 4))
    header = ROOT / "wfsource/source/gfx/gl/world_foundry_icon.h"
    lines = [
        "// Generated by scripts/gen-window-icon.py; do not edit.",
        "// Artwork: assets/branding/world-foundry-mark.png (cropped from wflogo.png).",
        "// Xlib format-32 properties use native unsigned long elements, even on LP64.",
        "#pragma once",
        "static const unsigned long kWorldFoundryWindowIcon[] = {",
    ]
    for offset in range(0, len(words), 8):
        lines.append("    " + ", ".join(f"0x{word:08x}UL" for word in words[offset:offset + 8]) + ",")
    header.write_text("\n".join(lines) + "\n};\n")
    print(f"Generated {mark.width}x{mark.height} mark; icons {SIZES}; {len(words)} X11 CARDINALs")


if __name__ == "__main__":
    main()
