// scripting_wasm3.cc — wasm3 interpreter plug for the `#` sigil.
//
// Compiled in only when WF_WASM_ENGINE_WASM3 is defined. Hosts a single
// IM3Environment + IM3Runtime; per-script it base64-decodes the module
// body, parses + loads + links the `env.read_mailbox` / `env.write_mailbox`
// imports, finds `main`, and calls it. Errors are non-fatal (logged).
//
// Spike deviations from docs/plans/2026-04-14-wasm3-scripting-engine.md:
//   * No constant-globals import surface — wasm3 v0.5.0 exposes
//     m3_FindGlobal for module-defined globals but has no linker API for
//     host-provided globals. Scripts bake INDEXOF_* values as i32 literals
//     for now. Follow-up: add an env.const(i32 id) -> i32 import keyed to
//     the existing IntArrayEntry tables.

#include "scripting_wasm3.hp"

#ifdef WF_WASM_ENGINE_WASM3

#include <mailbox/mailbox.hp>
#include <math/scalar.hp>

extern "C" {
#include "wasm3.h"
#include "m3_env.h"
}

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cstdlib>

namespace {

// Runtime-wide state. wasm3 runtimes are single-threaded and cheap; we keep
// one environment and one runtime for the whole engine lifetime, rebuilding
// modules per-script. Matches the JS plugs' shape.
IM3Environment    g_env       = nullptr;
IM3Runtime        g_runtime   = nullptr;
MailboxesManager* g_mailboxes = nullptr;
int               g_currentObjectIndex = 0;

constexpr uint32_t kStackSize    = 64 * 1024;
constexpr size_t   kMaxModuleSz  = 256 * 1024;

// Embedded selftest module: write_mailbox(0, 42); return read_mailbox(0).
// Generated by build_game.sh from wasm3-v0.5.0-wf/selftest.wasm via xxd -i.
extern "C" const unsigned char kWasmSelftest[];
extern "C" const unsigned int  kWasmSelftestLen;

// ------------------------------------------------------------------ base64

// Standard base64 alphabet. Returns number of bytes written, or -1 on bad
// input. Ignores whitespace. Output buffer must be at least 3*len/4 bytes.
int base64_decode(const char* in, size_t inLen, uint8_t* out, size_t outCap)
{
    static int8_t table[256];
    static bool   init = false;
    if (!init) {
        for (int i = 0; i < 256; i++) table[i] = -1;
        const char* a = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        for (int i = 0; i < 64; i++) table[(unsigned char)a[i]] = (int8_t)i;
        init = true;
    }
    uint32_t buf = 0;
    int bits = 0;
    size_t written = 0;
    for (size_t i = 0; i < inLen; i++) {
        unsigned char c = (unsigned char)in[i];
        if (c == '=' || c == '\n' || c == '\r' || c == ' ' || c == '\t') continue;
        int8_t v = table[c];
        if (v < 0) return -1;
        buf = (buf << 6) | (uint32_t)v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            if (written >= outCap) return -1;
            out[written++] = (uint8_t)((buf >> bits) & 0xFF);
        }
    }
    return (int)written;
}

// ------------------------------------------------------------------ imports

// Return slot layout (wasm3 packs args/returns in a single uint64_t stack):
//   _sp[0..numReturns-1]   result slots
//   _sp[numReturns..]      argument slots, one per arg
// read_mailbox signature is "f(i)" — 1 return (f32), 1 arg (i32).
// write_mailbox signature is "v(if)" — 0 returns, 2 args (i32, f32).

const void* hi_read_mailbox(IM3Runtime /*rt*/, IM3ImportContext /*ctx*/,
                            uint64_t* _sp, void* /*mem*/)
{
    // _sp[0] = return slot (f32), _sp[1] = mailbox id (i32)
    int32_t mailbox = (int32_t)_sp[1];
    if (!g_mailboxes) {
        *(float*)&_sp[0] = 0.0f;
        return m3Err_none;
    }
    Mailboxes& mb = g_mailboxes->LookupMailboxes(g_currentObjectIndex);
    float v = mb.ReadMailbox(mailbox).AsFloat();
    std::fprintf(stderr, "  wasm3 read_mailbox(%d, actor=%d) -> %g\n",
                 (int)mailbox, g_currentObjectIndex, (double)v);
    *(float*)&_sp[0] = v;
    return m3Err_none;
}

const void* hi_write_mailbox(IM3Runtime /*rt*/, IM3ImportContext /*ctx*/,
                             uint64_t* _sp, void* /*mem*/)
{
    // No return; args are _sp[0] = mailbox id (i32), _sp[1] = value (f32)
    int32_t mailbox = (int32_t)_sp[0];
    float   value   = *(float*)&_sp[1];
    if (!g_mailboxes) return m3Err_none;
    Mailboxes& mb = g_mailboxes->LookupMailboxes(g_currentObjectIndex);
    std::fprintf(stderr, "  wasm3 write_mailbox(%d, %g, actor=%d)\n",
                 (int)mailbox, (double)value, g_currentObjectIndex);
    mb.WriteMailbox(mailbox, Scalar::FromFloat(value));
    return m3Err_none;
}

M3Result link_host_imports(IM3Module module)
{
    M3Result r;
    r = m3_LinkRawFunction(module, "env", "read_mailbox",  "f(i)",  hi_read_mailbox);
    if (r && r != m3Err_functionLookupFailed) return r;
    r = m3_LinkRawFunction(module, "env", "write_mailbox", "v(if)", hi_write_mailbox);
    if (r && r != m3Err_functionLookupFailed) return r;
    return m3Err_none;
}

} // namespace

// -------------------------------------------------------------------- API

void wasm3_engine::Init(MailboxesManager& mgr)
{
    g_mailboxes = &mgr;
    g_env       = m3_NewEnvironment();
    if (!g_env) {
        std::fprintf(stderr, "wasm3: m3_NewEnvironment failed\n");
        return;
    }
    g_runtime = m3_NewRuntime(g_env, kStackSize, /*userdata*/nullptr);
    if (!g_runtime) {
        std::fprintf(stderr, "wasm3: m3_NewRuntime failed\n");
        return;
    }
    std::fprintf(stderr, "wasm3: runtime up (stack=%u)\n", kStackSize);

    // Opt-in startup selftest: parse+load+call a tiny module that returns
    // i32 42. Proves the wasm3 wiring (parse, load, find, call, result)
    // before any level script touches the engine. Host-import wiring is
    // not exercised here on purpose — at runtime-init time the
    // MailboxesManager has no actor yet, so import calls would assert;
    // real level scripts cover the import path.
    if (const char* dbg = std::getenv("WF_WASM_DEBUG"); dbg && *dbg == '1') {
        IM3Module mod = nullptr;
        M3Result  r   = m3_ParseModule(g_env, &mod,
                                       kWasmSelftest, kWasmSelftestLen);
        if (r) { std::fprintf(stderr, "wasm3: selftest parse: %s\n", r); return; }
        r = m3_LoadModule(g_runtime, mod);
        if (r) { std::fprintf(stderr, "wasm3: selftest load: %s\n", r); return; }
        IM3Function fn = nullptr;
        r = m3_FindFunction(&fn, g_runtime, "main");
        if (r || !fn) { std::fprintf(stderr, "wasm3: selftest find: %s\n",
                                     r ? r : "null"); return; }
        r = m3_CallV(fn);
        if (r) { std::fprintf(stderr, "wasm3: selftest call: %s\n", r); return; }
        int32_t got = 0;
        m3_GetResultsV(fn, &got);
        if (got == 42) {
            std::fprintf(stderr, "wasm3: selftest OK (parse/load/call)\n");
        } else {
            std::fprintf(stderr, "wasm3: selftest FAILED (got %d, want 42)\n",
                         (int)got);
        }
    }
}

void wasm3_engine::Shutdown()
{
    if (g_runtime) { m3_FreeRuntime(g_runtime); g_runtime = nullptr; }
    if (g_env)     { m3_FreeEnvironment(g_env); g_env     = nullptr; }
    g_mailboxes = nullptr;
}

void wasm3_engine::AddConstantArray(IntArrayEntry* /*entryList*/)
{
    // Deliberately empty — see file-top note on the constant-globals gap.
}

void wasm3_engine::DeleteConstantArray(IntArrayEntry* /*entryList*/)
{
}

float wasm3_engine::RunScript(const char* src, int objectIndex)
{
    if (!g_runtime || !src) return 0.0f;
    g_currentObjectIndex = objectIndex;

    // Skip whitespace, then the `#` sigil, then an optional `b64\n` subtype
    // tag. Current spike accepts only the b64 subtype (the format is
    // "#b64\n<base64>"); a bare `#` with a tag we don't recognise is an
    // error, so authors don't silently fall through to Lua.
    const char* p = src;
    while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
    if (*p != '#') return 0.0f;
    p++;
    const char* nl = std::strchr(p, '\n');
    if (!nl) {
        std::fprintf(stderr, "wasm3: missing newline after sigil\n");
        return 0.0f;
    }
    size_t tagLen = (size_t)(nl - p);
    if (tagLen != 3 || std::memcmp(p, "b64", 3) != 0) {
        std::fprintf(stderr, "wasm3: unknown sigil subtype (expected 'b64')\n");
        return 0.0f;
    }
    const char* b64Start = nl + 1;
    size_t      b64Len   = std::strlen(b64Start);

    // Decode into a heap buffer sized to the worst-case 3*len/4 ceiling.
    size_t   decCap = (b64Len / 4) * 3 + 3;
    if (decCap > kMaxModuleSz) {
        std::fprintf(stderr, "wasm3: module too large (%zu > %zu)\n",
                     decCap, kMaxModuleSz);
        return 0.0f;
    }
    uint8_t* bytes = (uint8_t*)std::malloc(decCap);
    if (!bytes) return 0.0f;
    int decoded = base64_decode(b64Start, b64Len, bytes, decCap);
    if (decoded < 0) {
        std::fprintf(stderr, "wasm3: base64 decode failed\n");
        std::free(bytes);
        return 0.0f;
    }

    IM3Module module = nullptr;
    M3Result  r      = m3_ParseModule(g_env, &module, bytes, (uint32_t)decoded);
    if (r) {
        std::fprintf(stderr, "wasm3: parse failed: %s\n", r);
        std::free(bytes);
        return 0.0f;
    }
    // wasm3 keeps a reference to the bytes buffer for the module's lifetime.
    // Transfer ownership to the runtime so we can't free it early; wasm3's
    // m3_LoadModule sets the module's "bytes-owned" flag via a private API
    // (ForEachModule_r / the module struct). We simply leak the buffer for
    // the spike: one module per script, ~hundreds of bytes each, negligible.

    r = m3_LoadModule(g_runtime, module);
    if (r) {
        std::fprintf(stderr, "wasm3: load failed: %s\n", r);
        m3_FreeModule(module);
        return 0.0f;
    }

    r = link_host_imports(module);
    if (r) {
        std::fprintf(stderr, "wasm3: link failed: %s\n", r);
        return 0.0f;
    }

    IM3Function fn = nullptr;
    r = m3_FindFunction(&fn, g_runtime, "main");
    if (r || !fn) {
        std::fprintf(stderr, "wasm3: no 'main' export: %s\n", r ? r : "null");
        return 0.0f;
    }

    r = m3_CallV(fn);
    if (r) {
        std::fprintf(stderr, "wasm3: trap in main: %s\n", r);
        return 0.0f;
    }

    // Return value (if any): grab first retval as i32 or f32.
    uint32_t retc = m3_GetRetCount(fn);
    if (retc == 0) return 0.0f;
    M3ValueType t = m3_GetRetType(fn, 0);
    if (t == c_m3Type_f32) {
        float v = 0.0f;
        m3_GetResultsV(fn, &v);
        return v;
    }
    if (t == c_m3Type_i32) {
        int32_t v = 0;
        m3_GetResultsV(fn, &v);
        return (float)v;
    }
    return 0.0f;
}

#endif // WF_WASM_ENGINE_WASM3
