




	
	int RenderPoly3DFlatColorLit( Primitive* primitive);
	int RenderPoly3DGouraudColorLit( Primitive* primitive);
	int RenderPoly3DFlatTextureLit( Primitive* primitive);
	int RenderPoly3DGouraudTextureLit( Primitive* primitive);

	int RenderPoly3DFlatColorPreLit( Primitive* primitive);
	int RenderPoly3DGouraudColorPreLit( Primitive* primitive);
	int RenderPoly3DFlatTexturePreLit( Primitive* primitive);
	int RenderPoly3DGouraudTexturePreLit( Primitive* primitive);







