[package]
name = "wf_attr_edit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
wf_oad = { path = "../wf_oad" }
wf_attr_schema = { path = "../wf_attr_schema" }
wf_attr_validate = { path = "../wf_attr_validate" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
