#!/usr/bin/env bash
# build.sh -- course JSON -> marble-madness-3d-standalone.iff, end to end.
#
#   bash wflevels/marble-madness-3d/build.sh [course.json]
#
# Steps:
#   1. blender --background --python gen_course.py -- <course.json>
#        -> marble-madness-3d.lev + one .iff per mesh datablock
#   2. task build-level -- marble-madness-3d   (wraps build_level_binary.sh)
#        -> wflevels/marble-madness-3d.iff and wflevels/marble-madness-3d-standalone.iff
#
# Default course is course-test.json (regenerated by make_test_course.py if absent).

set -euo pipefail

usage() {
    cat <<'EOF'
usage: build.sh [-h] [COURSE_JSON]

Build the marble-madness-3d level from a course-description JSON.

  COURSE_JSON   path to the course JSON (default: <script dir>/course-test.json)
  -h, --help    show this message and exit

Outputs:
  wflevels/marble-madness-3d/marble-madness-3d.lev
  wflevels/marble-madness-3d.iff
  wflevels/marble-madness-3d-standalone.iff   <- run this with `wf_game -L`
EOF
}

case "${1:-}" in
    -h|--help) usage; exit 0 ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
COURSE="${1:-$SCRIPT_DIR/course-test.json}"

if [[ ! -f "$COURSE" ]]; then
    if [[ "$COURSE" == "$SCRIPT_DIR/course-test.json" ]]; then
        echo "[mm3d] course-test.json missing -- regenerating"
        python3 "$SCRIPT_DIR/make_test_course.py" -o "$COURSE"
    else
        echo "no such course JSON: $COURSE" >&2
        exit 1
    fi
fi

command -v blender >/dev/null 2>&1 || { echo "blender not on PATH" >&2; exit 1; }

echo "[mm3d] 1/2  blender --background --python gen_course.py -- $COURSE"
# --python-exit-code 1: headless Blender otherwise exits 0 after a Python
# exception, which would let a broken scene through to the level build
# (docs/level-design-troubleshooting.md).
blender --background --python-exit-code 1 \
        --python "$SCRIPT_DIR/gen_course.py" -- "$COURSE"

echo "[mm3d] 2/2  task build-level -- marble-madness-3d"
cd "$REPO"
task build-level -- marble-madness-3d

echo
ls -l "$REPO/wflevels/marble-madness-3d.iff" "$REPO/wflevels/marble-madness-3d-standalone.iff"
